function setLineWidthContoursCallback(~, ~) 
%function setLineWidthContoursCallback()
%Set line contours width.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2020, Daniel Lafontaine, on behalf of the TriDFusion development team.
% 
% This file is part of The Triple Dimention Fusion (TriDFusion).
% 
% TriDFusion development has been led by:  Daniel Lafontaine
% 
% TriDFusion is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.
    
    if isPlotContours('get') == true 
        
        if size(dicomBuffer('get'), 3) == 1 % 2D Image
            imAxeFc = imAxeFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if ~isempty(imAxeFc)
                aLineWidth = get(imAxeFc, 'LineWidth');
                sLineWidth =  num2str(aLineWidth);
            else
                sLineWidth = '';
            end 
            
            dlgLineWidth = ...
                dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-125/2) ...
                                    380 ...
                                    125 ...
                                    ],...
                      'Color', viewerBackgroundColor('get'), ...
                      'Name', 'Set Line Width'...
                       ); 

             axeLineWidth = ...                  
                axes(dlgLineWidth, ...
                     'Units'   , 'pixels', ...
                     'Position', get(dlgLineWidth, 'Position'), ...
                     'Color'   , viewerBackgroundColor('get'),...
                     'XColor'  , viewerForegroundColor('get'),...
                     'YColor'  , viewerForegroundColor('get'),...
                     'ZColor'  , viewerForegroundColor('get'),...             
                     'Visible' , 'off'...             
                     );  
             axeLineWidth.Interactions = [zoomInteraction regionZoomInteraction rulerPanInteraction];
             axeLineWidth.Toolbar = [];

                 uicontrol(dlgLineWidth,...
                          'style'   , 'text',...
                          'string'  , 'Line Width:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 67 75 20]...
                          );
                           
          edtAxeLineWidth = ...
              uicontrol(dlgLineWidth,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sLineWidth,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 70 265 20]...
                        ); 
                    
             % Cancel or Proceed

             uicontrol(dlgLineWidth,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelLineWidthCallback...
                       );

             uicontrol(dlgLineWidth,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedLineWidthCallback...
                      );                    
                   
        else            
            
            imCoronalFc  = imCoronalFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
 
            if ~isempty(imCoronalFc)
                aCoronalLineWidth = get(imCoronalFc, 'LineWidth');
                sCoronalLineWidth = num2str(aCoronalLineWidth);
            else
                sCoronalLineWidth = '';
            end  
                        
            dlgLineWidth = ...
                dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-120/2) ...
                                    380 ...
                                    120 ...
                                    ],...
                      'Color', viewerBackgroundColor('get'), ...
                      'Name', 'Set Line Width'...
                       );      

                 uicontrol(dlgLineWidth,...
                          'style'   , 'text',...
                          'string'  , 'Line Width:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 67 75 20]...
                          );
                      
          edtPlaneLineWidth = ...
              uicontrol(dlgLineWidth,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sCoronalLineWidth,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 70 265 20]...
                        );                     
                    
             % Cancel or Proceed

             uicontrol(dlgLineWidth,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelLineWidthCallback...
                       );

             uicontrol(dlgLineWidth,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedLineWidthCallback...
                      );           

        end                              
    end
    
    function cancelLineWidthCallback(~, ~)
        
        delete(dlgLineWidth);
    end

    function proceedLineWidthCallback(~, ~) 
                
        if size(dicomBuffer('get'), 3) == 1 % 2D Image
            
            plotContoursLineWidth('set', str2num(edtAxeLineWidth.String));
            
            imAxeFc = imAxeFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if ~isempty(imAxeFc)
                set(imAxeFc, 'LineWidth',  str2num(edtAxeLineWidth.String));
            end 
        else         
            
            plotContoursLineWidth('set', str2num(edtPlaneLineWidth.String));

            imCoronalFc  = imCoronalFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imSagittalFc = imSagittalFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imAxialFc    = imAxialFcPtr   ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if link2DMip('get') == true
                imMipFc = imMipFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value'));   
            end            
            
            if ~isempty(imCoronalFc)
                set(imCoronalFc, 'LineWidth', str2num(edtPlaneLineWidth.String));
            end
            
            if ~isempty(imSagittalFc)
                set(imSagittalFc, 'LineWidth',  str2num(edtPlaneLineWidth.String));
            end

            if ~isempty(imAxialFc)
                set(imAxialFc, 'LineWidth',  str2num(edtPlaneLineWidth.String));
            end

            if link2DMip('get') == true
                if ~isempty(imMipFc)
                    set(imMipFc, 'LineWidth',  str2num(edtPlaneLineWidth.String));
                end
            end            
        end 
        
        delete(dlgLineWidth);
        
    end
end



