function setLevelListContoursCallback(~, ~) 
%function setLevelListContoursCallback()
%Show\Hide image contours level list.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2020, Daniel Lafontaine, on behalf of the TriDFusion development team.
% 
% This file is part of The Triple Dimention Fusion (TriDFusion).
% 
% TriDFusion development has been led by:  Daniel Lafontaine
% 
% TriDFusion is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.
    
    if isPlotContours('get') == true 
        
        if size(dicomBuffer('get', [], get(uiSeriesPtr('get'), 'Value')), 3) == 1 % 2D Image

            imAxeFc = imAxeFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if ~isempty(imAxeFc)
                aLevelList = get(imAxeFc, 'LevelList');
                sLevelList =  num2str(aLevelList);
            else
                sLevelList = '';
            end 

            if viewerUIFigure('get') == true
        
                dlgLevelList = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-170/2) ...
                                    380 ...
                                    170 ...
                                    ],...
                           'Resize'     , 'off', ...
                           'Color'      , viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name'       , 'Plot Contours Level List'...
                           );
            else

                dlgLevelList = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-170/2) ...
                                        380 ...
                                        170 ...
                                        ],...
                          'Color', viewerBackgroundColor('get'), ...
                          'Name', 'Plot Contours Level List'...
                           ); 
            end

            setObjectIcon(dlgLevelList);

            aDlgPosition = get(dlgLevelList, 'Position');

            axeLevelList = ...    
                axes(dlgLevelList, ...
                     'Units'   , 'pixels', ...
                     'Position', [0 0 aDlgPosition(3) aDlgPosition(4)], ...
                     'Color'   , viewerBackgroundColor('get'),...
                     'XColor'  , viewerForegroundColor('get'),...
                     'YColor'  , viewerForegroundColor('get'),...
                     'ZColor'  , viewerForegroundColor('get'),...             
                     'Visible' , 'off'...             
                     );  
             axeLevelList.Interactions = [];
             deleteAxesToolbar(axeLevelList);
             disableDefaultInteractivity(axeLevelList);

                 uicontrol(dlgLevelList,...
                          'style'   , 'text',...
                          'string'  , 'Input example: 0 100 200 300 400 500 600 700 800',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 120 340 20]...
                          );
                      
                 uicontrol(dlgLevelList,...
                          'style'   , 'text',...
                          'string'  , 'Axe:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 67 75 20]...
                          );
                           
          edtAxeLevelList = ...
              uicontrol(dlgLevelList,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sLevelList,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 70 265 20]...
                        ); 
                    
             % Cancel or Proceed

             uicontrol(dlgLevelList,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelLevelListCallback...
                       );

             uicontrol(dlgLevelList,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedLevelListCallback...
                      );                    
                   
        else            
            imCoronalFc  = imCoronalFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imSagittalFc = imSagittalFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imAxialFc    = imAxialFcPtr   ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if link2DMip('get') == true
                imMipFc = imMipFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value'));   
            end  

            if ~isempty(imCoronalFc)
                aCoronalLevelList = get(imCoronalFc, 'LevelList');
                sCoronalLevelList = num2str(aCoronalLevelList);
            else
                sCoronalLevelList = '';
            end  
            
            if ~isempty(imSagittalFc)
                aSagittalLevelList = get(imSagittalFc, 'LevelList');
                sSagittalLevelList = num2str(aSagittalLevelList);
            else
                sSagittalLevelList = '';                
            end  
                
            if ~isempty(imAxialFc)
                aAxialLevelList = get(imAxialFc, 'LevelList');
                sAxialLevelList = num2str(aAxialLevelList);
            else
                sAxialLevelList = '';                
            end  
            
            if link2DMip('get') == true
                if ~isempty(imMipFc)
                    aMipLevelList = get(imMipFc, 'LevelList');
                    sMipLevelList = num2str(aMipLevelList);
                else
                    sMipLevelList = '';                
                end                  
            else 
                sMipLevelList = '';                
            end 

            if viewerUIFigure('get') == true
        
                dlgLevelList = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-245/2) ...
                                    380 ...
                                    245 ...
                                    ],...
                           'Resize'     , 'off', ...
                           'Color'      , viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name'       , 'Plot Contours Level List'...
                           );
            else

                dlgLevelList = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-245/2) ...
                                    380 ...
                                    245 ...
                                    ],...
                          'Color', viewerBackgroundColor('get'), ...
                          'Name' , 'Plot Contours Level List'...
                           ); 
            end

            setObjectIcon(dlgLevelList);

            aDlgPosition = get(dlgLevelList, 'Position');

            axeLevelList = ...    
                axes(dlgLevelList, ...
                     'Units'   , 'pixels', ...
                     'Position', [0 0 aDlgPosition(3) aDlgPosition(4)], ...
                     'Color'   , viewerBackgroundColor('get'),...
                     'XColor'  , viewerForegroundColor('get'),...
                     'YColor'  , viewerForegroundColor('get'),...
                     'ZColor'  , viewerForegroundColor('get'),...             
                     'Visible' , 'off'...             
                     );  
             axeLevelList.Interactions = [];
             deleteAxesToolbar(axeLevelList);
             disableDefaultInteractivity(axeLevelList);    

                 uicontrol(dlgLevelList,...
                          'style'   , 'text',...
                          'string'  , 'Input example: 0 100 200 300 400 500 600 700 800',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 195 340 20]...
                          );

                 uicontrol(dlgLevelList,...
                          'style'   , 'text',...
                          'string'  , 'Coronal:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 142 75 20]...
                          );
                      
          edtCoronalLevelList = ...
              uicontrol(dlgLevelList,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sCoronalLevelList,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 145 265 20]...
                        ); 
                    
                 uicontrol(dlgLevelList,...
                          'style'   , 'text',...
                          'string'  , 'Sagittal:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 117 75 20]...
                          );
                      
          edtSagittalLevelList = ...
              uicontrol(dlgLevelList,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sSagittalLevelList,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 120 265 20]...
                        ); 
                    
                 uicontrol(dlgLevelList,...
                          'style'   , 'text',...
                          'string'  , 'Axial:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 93 75 20]...
                          );
                      
          edtAxialLevelList = ...
              uicontrol(dlgLevelList,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sAxialLevelList,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 95 265 20]...
                        ); 
                    
                 uicontrol(dlgLevelList,...
                          'style'   , 'text',...
                          'string'  , 'MIP:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 67 75 20]...
                          );
                      
          if link2DMip('get') == true
              sMipLevelEnable = 'on';
          else
              sMipLevelEnable = 'off';
          end
                      
          edtMipLevelList = ...
              uicontrol(dlgLevelList,...
                        'style'     , 'edit',...
                        'Enable'    , sMipLevelEnable, ...
                        'Background', 'white',...
                        'string'    , sMipLevelList,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 70 265 20]...
                        ); 
                    
             % Cancel or Proceed

             uicontrol(dlgLevelList,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelLevelListCallback...
                       );

             uicontrol(dlgLevelList,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedLevelListCallback...
                      );           

        end                              
    end
    
    function cancelLevelListCallback(~, ~)
        
        delete(dlgLevelList);
    end

    function proceedLevelListCallback(~, ~) 
        
        if size(dicomBuffer('get'), 3) == 1 % 2D Image
            imAxeFc = imAxeFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if ~isempty(imAxeFc)
                set(imAxeFc, 'LevelList',  str2num(edtAxeLevelList.String));
            end 
        else            
            imCoronalFc  = imCoronalFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imSagittalFc = imSagittalFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imAxialFc    = imAxialFcPtr   ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if link2DMip('get') == true
                imMipFc = imMipFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value'));   
            end            
            
            if ~isempty(imCoronalFc)
                set(imCoronalFc, 'LevelList', str2num(edtCoronalLevelList.String));
            end
            
            if ~isempty(imSagittalFc)
                set(imSagittalFc, 'LevelList',  str2num(edtSagittalLevelList.String));
            end

            if ~isempty(imAxialFc)
                set(imAxialFc, 'LevelList',  str2num(edtAxialLevelList.String));
            end

            if link2DMip('get') == true
                if ~isempty(imMipFc)
                    set(imMipFc, 'LevelList',  str2num(edtMipLevelList.String));
                end
            end            
        end 
        
        delete(dlgLevelList);
        
    end
end



