function setLevelStepContoursCallback(~, ~) 
%function setLevelStepContoursCallback()
%Set contours level tep.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2020, Daniel Lafontaine, on behalf of the TriDFusion development team.
% 
% This file is part of The Triple Dimention Fusion (TriDFusion).
% 
% TriDFusion development has been led by:  Daniel Lafontaine
% 
% TriDFusion is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.
    
    if isPlotContours('get') == true 
        
        if size(dicomBuffer('get'), 3) == 1 % 2D Image
            imAxeFc = imAxeFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if ~isempty(imAxeFc)
                aLevelStep = get(imAxeFc, 'LevelStep');
                sLevelStep =  num2str(aLevelStep);
            else
                sLevelStep = '';
            end 
            
            dlgLevelStep = ...
                dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-125/2) ...
                                    380 ...
                                    125 ...
                                    ],...
                      'Color', viewerBackgroundColor('get'), ...
                      'Name', 'Set Level Step'...
                       ); 

             axeLevelStep = ...       
                axes(dlgLevelStep, ...
                     'Units'   , 'pixels', ...
                     'Position', get(dlgLevelStep, 'Position'), ...
                     'Color'   , viewerBackgroundColor('get'),...
                     'XColor'  , viewerForegroundColor('get'),...
                     'YColor'  , viewerForegroundColor('get'),...
                     'ZColor'  , viewerForegroundColor('get'),...             
                     'Visible' , 'off'...             
                     );  
             axeLevelStep.Interactions = [zoomInteraction regionZoomInteraction rulerPanInteraction];
             axeLevelStep.Toolbar = [];

                 uicontrol(dlgLevelStep,...
                          'style'   , 'text',...
                          'string'  , 'Axe:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 67 75 20]...
                          );
                           
          edtAxeLevelStep = ...
              uicontrol(dlgLevelStep,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sLevelStep,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 70 265 20]...
                        ); 
                    
             % Cancel or Proceed

             uicontrol(dlgLevelStep,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelLevelStepCallback...
                       );

             uicontrol(dlgLevelStep,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedLevelStepCallback...
                      );                    
                   
        else            
            imCoronalFc  = imCoronalFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imSagittalFc = imSagittalFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imAxialFc    = imAxialFcPtr   ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if link2DMip('get') == true
                imMipFc = imMipFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value'));   
            end  

            if ~isempty(imCoronalFc)
                aCoronalLevelStep = get(imCoronalFc, 'LevelStep');
                sCoronalLevelStep = num2str(aCoronalLevelStep);
            else
                sCoronalLevelStep = '';
            end  
            
            if ~isempty(imSagittalFc)
                aSagittalLevelStep = get(imSagittalFc, 'LevelStep');
                sSagittalLevelStep = num2str(aSagittalLevelStep);
            else
                sSagittalLevelStep = '';                
            end  
                
            if ~isempty(imAxialFc)
                aAxialLevelStep = get(imAxialFc, 'LevelStep');
                sAxialLevelStep = num2str(aAxialLevelStep);
            else
                sAxialLevelStep = '';                
            end  
            
            if link2DMip('get') == true
                if ~isempty(imMipFc)
                    aMipLevelStep = get(imMipFc, 'LevelStep');
                    sMipLevelStep = num2str(aMipLevelStep);
                else
                    sMipLevelStep = '';                
                end                  
            else 
                sMipLevelStep = '';                
            end 
            
            dlgLevelStep = ...
                dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-195/2) ...
                                    380 ...
                                    195 ...
                                    ],...
                      'Color', viewerBackgroundColor('get'), ...
                      'Name', 'Set Level Step'...
                       );      

                 uicontrol(dlgLevelStep,...
                          'style'   , 'text',...
                          'string'  , 'Coronal:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 142 75 20]...
                          );
                      
          edtCoronalLevelStep = ...
              uicontrol(dlgLevelStep,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sCoronalLevelStep,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 145 265 20]...
                        ); 
                    
                 uicontrol(dlgLevelStep,...
                          'style'   , 'text',...
                          'string'  , 'Sagittal:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 117 75 20]...
                          );
                      
          edtSagittalLevelStep = ...
              uicontrol(dlgLevelStep,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sSagittalLevelStep,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 120 265 20]...
                        ); 
                    
                 uicontrol(dlgLevelStep,...
                          'style'   , 'text',...
                          'string'  , 'Axial:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 93 75 20]...
                          );
                      
          edtAxialLevelStep = ...
              uicontrol(dlgLevelStep,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sAxialLevelStep,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 95 265 20]...
                        ); 
                    
                 uicontrol(dlgLevelStep,...
                          'style'   , 'text',...
                          'string'  , 'MIP:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 67 75 20]...
                          );
                      
          if link2DMip('get') == true
              sMipStepEnable = 'on';
          else
              sMipStepEnable = 'off';
          end
                      
          edtMipLevelStep = ...
              uicontrol(dlgLevelStep,...
                        'style'     , 'edit',...
                        'Enable'    , sMipStepEnable, ...
                        'Background', 'white',...
                        'string'    , sMipLevelStep,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 70 265 20]...
                        ); 
                    
             % Cancel or Proceed

             uicontrol(dlgLevelStep,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelLevelStepCallback...
                       );

             uicontrol(dlgLevelStep,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedLevelStepCallback...
                      );           

        end                              
    end
    
    function cancelLevelStepCallback(~, ~)
        
        delete(dlgLevelStep);
    end

    function proceedLevelStepCallback(~, ~) 
        
        if size(dicomBuffer('get'), 3) == 1 % 2D Image
            imAxeFc = imAxeFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if ~isempty(imAxeFc)
                set(imAxeFc, 'LevelStep',  str2num(edtAxeLevelStep.String));
            end 
        else            
            imCoronalFc  = imCoronalFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imSagittalFc = imSagittalFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imAxialFc    = imAxialFcPtr   ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if link2DMip('get') == true
                imMipFc = imMipFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value'));   
            end            
            
            if ~isempty(imCoronalFc)
                set(imCoronalFc, 'LevelStep', str2num(edtCoronalLevelStep.String));
            end
            
            if ~isempty(imSagittalFc)
                set(imSagittalFc, 'LevelStep',  str2num(edtSagittalLevelStep.String));
            end

            if ~isempty(imAxialFc)
                set(imAxialFc, 'LevelStep',  str2num(edtAxialLevelStep.String));
            end

            if link2DMip('get') == true
                if ~isempty(imMipFc)
                    set(imMipFc, 'LevelStep',  str2num(edtMipLevelStep.String));
                end
            end            
        end 
        
        delete(dlgLevelStep);
        
    end
end



