function setTextListContoursCallback(~, ~) 
%function setTextListContoursCallback()
%Show\Hide image contours text list.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2020, Daniel Lafontaine, on behalf of the TriDFusion development team.
% 
% This file is part of The Triple Dimention Fusion (TriDFusion).
% 
% TriDFusion development has been led by:  Daniel Lafontaine
% 
% TriDFusion is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.
    
    if isPlotContours('get') == true 
        
        if size(dicomBuffer('get', [], get(uiSeriesPtr('get'), 'Value')), 3) == 1 % 2D Image

            imAxeFc = imAxeFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if ~isempty(imAxeFc)
                aTextList = get(imAxeFc, 'TextList');
                sTextList =  num2str(aTextList);
            else
                sTextList = '';
            end 
            
            if viewerUIFigure('get') == true
        
                dlgTextList = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-170/2) ...
                                        380 ...
                                        170 ...
                                        ],...
                           'Resize'     , 'off', ...
                           'Color'      , viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name'       , 'Plot Contours Text List'...
                           );
            else
    
                dlgTextList = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-170/2) ...
                                        380 ...
                                        170 ...
                                        ],...
                          'Color', viewerBackgroundColor('get'), ...
                          'Name', 'Plot Contours Text List'...
                           ); 
            end
    
            setObjectIcon(dlgTextList);

            aDlgPosition = get(dlgTextList, 'Position');

            axeTextList = ...     
                axes(dlgTextList, ...
                     'Units'   , 'pixels', ...
                     'Position', [0 0 aDlgPosition(3) aDlgPosition(4)], ...
                     'Color'   , viewerBackgroundColor('get'),...
                     'XColor'  , viewerForegroundColor('get'),...
                     'YColor'  , viewerForegroundColor('get'),...
                     'ZColor'  , viewerForegroundColor('get'),...             
                     'Visible' , 'off'...             
                     );
            axeTextList.Interactions = [];
            deleteAxesToolbar(axeTextList);
            disableDefaultInteractivity(axeTextList);

                 uicontrol(dlgTextList,...
                          'style'   , 'text',...
                          'string'  , 'Input example: 0 100 200 300 400 500 600 700 800',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 120 340 20]...
                          );
                      
                 uicontrol(dlgTextList,...
                          'style'   , 'text',...
                          'string'  , 'Axe:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 67 75 20]...
                          );
                           
          edtAxeTextList = ...
              uicontrol(dlgTextList,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sTextList,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 70 265 20]...
                        ); 
                    
             % Cancel or Proceed

             uicontrol(dlgTextList,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelTextListCallback...
                       );

             uicontrol(dlgTextList,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedTextListCallback...
                      );                    
                   
        else            
            imCoronalFc  = imCoronalFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imSagittalFc = imSagittalFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imAxialFc    = imAxialFcPtr   ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if link2DMip('get') == true
                imMipFc = imMipFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value'));   
            end  

            if ~isempty(imCoronalFc)
                aCoronalTextList = get(imCoronalFc, 'TextList');
                sCoronalTextList = num2str(aCoronalTextList);
            else
                sCoronalTextList = '';
            end  
            
            if ~isempty(imSagittalFc)
                aSagittalTextList = get(imSagittalFc, 'TextList');
                sSagittalTextList = num2str(aSagittalTextList);
            else
                sSagittalTextList = '';                
            end  
                
            if ~isempty(imAxialFc)
                aAxialTextList = get(imAxialFc, 'TextList');
                sAxialTextList = num2str(aAxialTextList);
            else
                sAxialTextList = '';                
            end  
            
            if link2DMip('get') == true
                if ~isempty(imMipFc)
                    aMipTextList = get(imMipFc, 'TextList');
                    sMipTextList = num2str(aMipTextList);
                else
                    sMipTextList = '';                
                end                  
            else 
                sMipTextList = '';                
            end 
                 
            if viewerUIFigure('get') == true
        
                dlgTextList = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-245/2) ...
                                    380 ...
                                    245 ...
                                    ],...
                           'Resize'     , 'off', ...
                           'Color'      , viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name'       , 'Plot Contours Text List'...
                           );
            else
    
                dlgTextList = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-245/2) ...
                                    380 ...
                                    245 ...
                                    ],...
                          'Color', viewerBackgroundColor('get'), ...
                          'Name', 'Plot Contours Text List'...
                           ); 
            end
    
            setObjectIcon(dlgTextList);

            aDlgPosition = get(dlgTextList, 'Position');

            axeTextList = ...     
                axes(dlgTextList, ...
                     'Units'   , 'pixels', ...
                     'Position', [0 0 aDlgPosition(3) aDlgPosition(4)], ...
                     'Color'   , viewerBackgroundColor('get'),...
                     'XColor'  , viewerForegroundColor('get'),...
                     'YColor'  , viewerForegroundColor('get'),...
                     'ZColor'  , viewerForegroundColor('get'),...             
                     'Visible' , 'off'...             
                     );
            axeTextList.Interactions = [];
            deleteAxesToolbar(axeTextList);
            disableDefaultInteractivity(axeTextList);

                 uicontrol(dlgTextList,...
                          'style'   , 'text',...
                          'string'  , 'Input example: 0 100 200 300 400 500 600 700 800',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 195 340 20]...
                          );

                 uicontrol(dlgTextList,...
                          'style'   , 'text',...
                          'string'  , 'Coronal:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 142 75 20]...
                          );
                      
          edtCoronalTextList = ...
              uicontrol(dlgTextList,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sCoronalTextList,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 145 265 20]...
                        ); 
                    
                 uicontrol(dlgTextList,...
                          'style'   , 'text',...
                          'string'  , 'Sagittal:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 117 75 20]...
                          );
                      
          edtSagittalTextList = ...
              uicontrol(dlgTextList,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sSagittalTextList,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 120 265 20]...
                        ); 
                    
                 uicontrol(dlgTextList,...
                          'style'   , 'text',...
                          'string'  , 'Axial:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 93 75 20]...
                          );
                      
          edtAxialTextList = ...
              uicontrol(dlgTextList,...
                        'style'     , 'edit',...
                        'Background', 'white',...
                        'string'    , sAxialTextList,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 95 265 20]...
                        ); 
                    
                 uicontrol(dlgTextList,...
                          'style'   , 'text',...
                          'string'  , 'MIP:',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 67 75 20]...
                          );
                      
          if link2DMip('get') == true
              sMipTextEnable = 'on';
          else
              sMipTextEnable = 'off';
          end
                      
          edtMipTextList = ...
              uicontrol(dlgTextList,...
                        'style'     , 'edit',...
                        'Enable'    , sMipTextEnable, ...
                        'Background', 'white',...
                        'string'    , sMipTextList,...
                        'BackgroundColor', viewerBackgroundColor('get'), ...
                        'ForegroundColor', viewerForegroundColor('get'), ...                 
                        'position'  , [95 70 265 20]...
                        ); 
                    
             % Cancel or Proceed

             uicontrol(dlgTextList,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelTextListCallback...
                       );

             uicontrol(dlgTextList,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedTextListCallback...
                      );           

        end                              
    end
    
    function cancelTextListCallback(~, ~)
        
        delete(dlgTextList);
    end

    function proceedTextListCallback(~, ~) 
        
        if size(dicomBuffer('get'), 3) == 1 % 2D Image
            imAxeFc = imAxeFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if ~isempty(imAxeFc)
                set(imAxeFc, 'TextList',  str2num(edtAxeTextList.String));
            end 
        else            
            imCoronalFc  = imCoronalFcPtr ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imSagittalFc = imSagittalFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            imAxialFc    = imAxialFcPtr   ('get', [], get(uiFusedSeriesPtr('get'), 'Value')); 
            if link2DMip('get') == true
                imMipFc = imMipFcPtr('get', [], get(uiFusedSeriesPtr('get'), 'Value'));   
            end            
            
            if ~isempty(imCoronalFc)
                set(imCoronalFc, 'TextList', str2num(edtCoronalTextList.String));
            end
            
            if ~isempty(imSagittalFc)
                set(imSagittalFc, 'TextList',  str2num(edtSagittalTextList.String));
            end

            if ~isempty(imAxialFc)
                set(imAxialFc, 'TextList',  str2num(edtAxialTextList.String));
            end

            if link2DMip('get') == true
                if ~isempty(imMipFc)
                    set(imMipFc, 'TextList',  str2num(edtMipTextList.String));
                end
            end            
        end 
        
        delete(dlgTextList);
        
    end
end



