function setPatientDoseCallback(~, ~)
%function setPatientDoseCallback(~, ~)
%Get\Set Patient Dose Information.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2020, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    FIG_PDOSE_X = 480;
    FIG_PDOSE_Y = 490;

    atDoseMetaData = dicomMetaData('get');

    if isfield(atDoseMetaData{1}, 'RadiopharmaceuticalInformationSequence')

         if viewerUIFigure('get') == true

            dlgPatientDose = ...
                uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-FIG_PDOSE_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-FIG_PDOSE_Y/2) ...
                                    FIG_PDOSE_X ...
                                    FIG_PDOSE_Y ...
                                    ],...
                       'Resize', 'off', ...
                       'Color', viewerBackgroundColor('get'),...
                       'WindowStyle', 'modal', ...
                       'Name' , 'Patient Dose Information'...
                       );
        else
            dlgPatientDose = ...
                dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-FIG_PDOSE_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-FIG_PDOSE_Y/2) ...
                                    FIG_PDOSE_X ...
                                    FIG_PDOSE_Y ...
                                    ],...
                      'MenuBar', 'none',...
                      'Resize', 'off', ...
                      'NumberTitle','off',...
                      'MenuBar', 'none',...
                      'Color', viewerBackgroundColor('get'), ...
                      'Name', 'Patient Dose Information',...
                      'Toolbar','none'...
                       );
        end

        setObjectIcon(dlgPatientDose);

        axePatientDose = ...
            axes(dlgPatientDose, ...
                 'Units'   , 'pixels', ...
                 'Position', [0 0 FIG_PDOSE_X FIG_PDOSE_Y], ...
                 'Color'   , viewerBackgroundColor('get'),...
                 'XColor'  , viewerForegroundColor('get'),...
                 'YColor'  , viewerForegroundColor('get'),...
                 'ZColor'  , viewerForegroundColor('get'),...
                 'Visible' , 'off'...
                 );
        axePatientDose.Interactions = [];
        % axePatientDose.Toolbar.Visible = 'off';
        deleteAxesToolbar(axePatientDose);
        disableDefaultInteractivity(axePatientDose);

        patWeight   = atDoseMetaData{1}.PatientWeight;
        patSize     = atDoseMetaData{1}.PatientSize;
        seriesDate  = atDoseMetaData{1}.SeriesDate;
        seriesTime  = atDoseMetaData{1}.SeriesTime;
        acqDate     = atDoseMetaData{1}.AcquisitionDate;
        acqTime     = atDoseMetaData{1}.AcquisitionTime;
        injDose     = atDoseMetaData{1}.RadiopharmaceuticalInformationSequence.Item_1.RadionuclideTotalDose;
        injDateTime = atDoseMetaData{1}.RadiopharmaceuticalInformationSequence.Item_1.RadiopharmaceuticalStartDateTime;
        halfLife    = atDoseMetaData{1}.RadiopharmaceuticalInformationSequence.Item_1.RadionuclideHalfLife;

             uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Warning: Proceed with modification will affect SUV values',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', 'red', ...
                     'position', [20 440 440 20]...
                     );

            uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Patient Weight (kilograms)',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 387 280 20]...
                     );

      edtPatWeight = ...
          uicontrol(dlgPatientDose,...
                    'style'     , 'edit',...
                    'Background', 'white',...
                    'string'    , num2str(patWeight),...
                    'BackgroundColor', viewerBackgroundColor('get'), ...
                    'ForegroundColor', viewerForegroundColor('get'), ...
                    'position'  , [300 390 160 20]...
                    );

            uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Patient Size (meters)',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 362 280 20]...
                     );

      edtPatSize = ...
          uicontrol(dlgPatientDose,...
                    'style'     , 'edit',...
                    'Background', 'white',...
                    'string'    , num2str(patSize),...
                    'BackgroundColor', viewerBackgroundColor('get'), ...
                    'ForegroundColor', viewerForegroundColor('get'), ...
                    'position'  , [300 365 160 20]...
                    );

        % Series Date

            uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Series Date',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 337 280 20]...
                     );

           uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Format (yyyyMMdd)',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 312 280 20]...
                     );

      edtSeriesDate = ...
          uicontrol(dlgPatientDose,...
                    'style'     , 'edit',...
                    'Background', 'white',...
                    'string'    , seriesDate,...
                    'BackgroundColor', viewerBackgroundColor('get'), ...
                    'ForegroundColor', viewerForegroundColor('get'), ...
                    'position'  , [300 315 160 20]...
                    );

        % Series Time

           uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Series Time',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 287 280 20]...
                     );

           uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Format (HHmmss)',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 262 280 20]...
                     );

      edtSeriesTime = ...
          uicontrol(dlgPatientDose,...
                    'style'     , 'edit',...
                    'Background', 'white',...
                    'string'    , seriesTime,...
                    'BackgroundColor', viewerBackgroundColor('get'), ...
                    'ForegroundColor', viewerForegroundColor('get'), ...
                    'position'  , [300 265 160 20]...
                    );

        % Acquisition Date

            uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Acquisition Date',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 237 280 20]...
                     );

           uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Format (yyyyMMdd)',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 212 280 20]...
                     );

      edtAcqDate = ...
          uicontrol(dlgPatientDose,...
                    'style'     , 'edit',...
                    'Background', 'white',...
                    'string'    , acqDate,...
                    'BackgroundColor', viewerBackgroundColor('get'), ...
                    'ForegroundColor', viewerForegroundColor('get'), ...
                    'position'  , [300 215 160 20]...
                    );

        % Acquisition Time

           uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Acquisition Time',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 187 280 20]...
                     );

           uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Format (HHmmss)',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 162 280 20]...
                     );

      edtAcqTime = ...
          uicontrol(dlgPatientDose,...
                    'style'     , 'edit',...
                    'Background', 'white',...
                    'string'    , acqTime,...
                    'BackgroundColor', viewerBackgroundColor('get'), ...
                    'ForegroundColor', viewerForegroundColor('get'), ...
                    'position'  , [300 165 160 20]...
                    );

        % Radionuclide Total Dose

%         if strcmpi(atDoseMetaData{1}.Modality, 'nm')
% %            sMeasured = 'Mbq';
%             sMeasured = 'bq';
%         else
            sMeasured = 'bq';
        % end

           uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , sprintf('Radionuclide Total Dose (%s)', sMeasured),...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 137 280 20]...
                     );

      edtInjDose = ...
          uicontrol(dlgPatientDose,...
                    'style'     , 'edit',...
                    'Background', 'white',...
                    'string'    , injDose,...
                    'BackgroundColor', viewerBackgroundColor('get'), ...
                    'ForegroundColor', viewerForegroundColor('get'), ...
                    'position'  , [300 140 160 20]...
                    );

        % Radiopharmaceutical Start Date Time

           uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Radiopharmaceutical Start Date Time',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 112 280 20]...
                     );

           uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Format (yyyyMMddHHmmss.SS)',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 87 280 20]...
                     );

      edtInjDateTime = ...
          uicontrol(dlgPatientDose,...
                    'style'     , 'edit',...
                    'Background', 'white',...
                    'string'    , injDateTime,...
                    'BackgroundColor', viewerBackgroundColor('get'), ...
                    'ForegroundColor', viewerForegroundColor('get'), ...
                    'position'  , [300 90 160 20]...
                    );

        % Radiopharmaceutical Half Life

           uicontrol(dlgPatientDose,...
                     'style'   , 'text',...
                     'string'  , 'Radionuclide Half-Life',...
                     'horizontalalignment', 'left',...
                     'BackgroundColor', viewerBackgroundColor('get'), ...
                     'ForegroundColor', viewerForegroundColor('get'), ...
                     'position', [20 62 280 20]...
                     );

      edtHalfLife = ...
          uicontrol(dlgPatientDose,...
                    'style'     , 'edit',...
                    'Background', 'white',...
                    'string'    , halfLife,...
                    'BackgroundColor', viewerBackgroundColor('get'), ...
                    'ForegroundColor', viewerForegroundColor('get'), ...
                    'position'  , [300 65 160 20]...
                    );

         % Cancel or Proceed

         uicontrol(dlgPatientDose,...
                   'String','Cancel',...
                   'Position',[385 7 75 25],...
                   'BackgroundColor', viewerBackgroundColor('get'), ...
                   'ForegroundColor', viewerForegroundColor('get'), ...
                   'Callback', @cancelPatientDoseCallback...
                   );

         uicontrol(dlgPatientDose,...
                  'String','Proceed',...
                  'Position',[300 7 75 25],...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...
                  'Callback', @proceedPatientDoseCallback...
                  );

    end

    function cancelPatientDoseCallback(~, ~)
        delete(dlgPatientDose);
    end

    function proceedPatientDoseCallback(~, ~)

        atDoseMetaData = dicomMetaData('get');

        if isempty(get(edtPatWeight  , 'String'))
            patWeight = [];
        else
            patWeight = str2double(get(edtPatWeight  , 'String'));
        end

        if isempty(get(edtPatSize  , 'String'))
            patSize = [];
        else
            patSize = str2double(get(edtPatSize    , 'String'));
        end

        seriesDate  = get(edtSeriesDate , 'String');
        seriesTime  = get(edtSeriesTime , 'String');
        acqDate     = get(edtAcqDate    , 'String');
        acqTime     = get(edtAcqTime    , 'String');
        injDose     = get(edtInjDose    , 'String');
        injDateTime = get(edtInjDateTime, 'String');
        halfLife    = get(edtHalfLife   , 'String');

        for hh=1:numel(atDoseMetaData)

            atDoseMetaData{hh}.PatientWeight   = patWeight;
            atDoseMetaData{hh}.PatientSize     = patSize;
            atDoseMetaData{hh}.SeriesDate      = seriesDate;
            atDoseMetaData{hh}.SeriesTime      = seriesTime;
            atDoseMetaData{hh}.AcquisitionDate = acqDate;
            atDoseMetaData{hh}.AcquisitionTime = acqTime;
            atDoseMetaData{hh}.RadiopharmaceuticalInformationSequence.Item_1.RadionuclideTotalDose = injDose;
            atDoseMetaData{hh}.RadiopharmaceuticalInformationSequence.Item_1.RadiopharmaceuticalStartDateTime = injDateTime;
            atDoseMetaData{hh}.RadiopharmaceuticalInformationSequence.Item_1.RadionuclideHalfLife = halfLife;
        end

        dicomMetaData('set', atDoseMetaData);

        setQuantification(get(uiSeriesPtr('get'), 'Value'));

         sUnitDisplay = getSerieUnitValue(get(uiSeriesPtr('get'), 'Value'));
         if strcmpi(sUnitDisplay, 'SUV')
             tQuant = quantificationTemplate('get');
             if tQuant.tSUV.dScale
                lMin = suvWindowLevel('get', 'min')/tQuant.tSUV.dScale;
                lMax = suvWindowLevel('get', 'max')/tQuant.tSUV.dScale;

                windowLevel('set', 'min', lMin);
                windowLevel('set', 'max', lMax);

                getInitWindowMinMax('set', lMax, lMin);

                sliderWindowLevelValue('set', 'min', 0.5);
                sliderWindowLevelValue('set', 'max', 0.5);

                if switchTo3DMode('get')     == false && ...
                   switchToIsoSurface('get') == false && ...
                   switchToMIPMode('get')    == false

                    if size(dicomBuffer('get'), 3) == 1
                        set(axePtr('get', [], get(uiSeriesPtr('get'), 'Value')), 'CLim', [lMin lMax]);
                    else
                        set(axes1Ptr('get', [], get(uiSeriesPtr('get'), 'Value')), 'CLim', [lMin lMax]);
                        set(axes2Ptr('get', [], get(uiSeriesPtr('get'), 'Value')), 'CLim', [lMin lMax]);
                        set(axes3Ptr('get', [], get(uiSeriesPtr('get'), 'Value')), 'CLim', [lMin lMax]);
                        if isVsplash('get') == false
                            set(axesMipPtr('get', [], get(uiSeriesPtr('get'), 'Value')), 'CLim', [lMin lMax]);
                        end
                    end
                end
             end
         end

        refreshImages();

        delete(dlgPatientDose);
    end

end
