function createLiverTumorZoningCallback(hObject, ~)
%function createLiverTumorZoningCallback(hObject, ~)
%Split liver in 8 zones and export the statistics.This tool os calld from
%the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2025, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    if exist('hObject', 'var')

        DLG_HAI_ZONING_X = 380;
        DLG_HAI_ZONING_Y = 120;

        if viewerUIFigure('get') == true
    
            dlgHaiZoningZone = ...
                uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_HAI_ZONING_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_HAI_ZONING_Y/2) ...
                                    DLG_HAI_ZONING_X ...
                                    DLG_HAI_ZONING_Y ...
                                    ],...
                       'Resize', 'off', ...
                       'Color', viewerBackgroundColor('get'),...
                       'WindowStyle', 'modal', ...
                       'Name' , 'Create Liver Tumor Zoning'...
                       );
        else      
            dlgHaiZoningZone = ...
                dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_HAI_ZONING_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_HAI_ZONING_Y/2) ...
                                    DLG_HAI_ZONING_X ...
                                    DLG_HAI_ZONING_Y ...
                                    ],...
                       'MenuBar', 'none',...
                       'Resize', 'off', ...    
                       'NumberTitle','off',...
                       'MenuBar', 'none',...
                       'Color', viewerBackgroundColor('get'), ...
                       'Name', 'Create Liver Tumor Zoning',...
                       'Toolbar','none'...               
                       );
        end

        setObjectIcon(dlgHaiZoningZone);

         % Margin Distance (mm)
    
            uicontrol(dlgHaiZoningZone,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'VOIs Expansion Margin (mm)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 65 250 20]...
                      );
    
        edtHaiZoningMarginDistanceValue = ...
            uicontrol(dlgHaiZoningZone, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 65 75 20], ...
                      'String'  , num2str(haiZoningMarginDistanceValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtHaiZoningMarginDistanceValueCallback ...
                      );        
    
         % Cancel or Proceed
    
         uicontrol(dlgHaiZoningZone,...
                   'String','Cancel',...
                   'Position',[285 7 75 25],...
                   'BackgroundColor', viewerBackgroundColor('get'), ...
                   'ForegroundColor', viewerForegroundColor('get'), ...                
                   'Callback', @cancelHaiZoningCallback...
                   );
    
         uicontrol(dlgHaiZoningZone,...
                  'String','Proceed',...
                  'Position',[200 7 75 25],...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...               
                  'Callback', @proceedHaiZoningCallback...
                  );   

    else
        
        createLiverTumorZoning(haiZoningMarginDistanceValue('get'), true);
    
        % Exit the compiled executable
        
        close(fiMainWindowPtr('get'));  
    end 

    function edtHaiZoningMarginDistanceValueCallback(hObject, ~)

        dValue = str2double(get(hObject, 'String'));

        if dValue < 0

            dValue = 0;

            set(hObject, 'String', num2str(dValue));
        end

        haiZoningMarginDistanceValue('set', dValue);

    end

    function cancelHaiZoningCallback(~, ~)

        delete(dlgHaiZoningZone);
    end

    function proceedHaiZoningCallback(~, ~)

        dMarginSize = str2double(get(edtHaiZoningMarginDistanceValue, 'String'));

        delete(dlgHaiZoningZone);

        createLiverTumorZoning(dMarginSize, true);
    end
end