function createTumorAblationZoneCallback(hObject, ~)
%function createTumorAblationZoneCallback(hObject, ~)
%Add a Marginal VOI Around an Existing VOI, the function is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2024, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    if exist('hObject', 'var')

        DLG_ABLATION_ZONE_X = 380;
        DLG_ABLATION_ZONE_Y = 145;

        if viewerUIFigure('get') == true
    
            dlgLiverAblationZone = ...
                uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_ABLATION_ZONE_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_ABLATION_ZONE_Y/2) ...
                                    DLG_ABLATION_ZONE_X ...
                                    DLG_ABLATION_ZONE_Y ...
                                    ],...
                       'Resize', 'off', ...
                       'Color', viewerBackgroundColor('get'),...
                       'WindowStyle', 'modal', ...
                       'Name' , 'Create Liver Tumor Ablation Zone'...
                       );
        else      
            dlgLiverAblationZone = ...
                dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_ABLATION_ZONE_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_ABLATION_ZONE_Y/2) ...
                                    DLG_ABLATION_ZONE_X ...
                                    DLG_ABLATION_ZONE_Y ...
                                    ],...
                       'MenuBar', 'none',...
                       'Resize', 'off', ...    
                       'NumberTitle','off',...
                       'MenuBar', 'none',...
                       'Color', viewerBackgroundColor('get'), ...
                       'Name', 'Create Liver Tumor Ablation Zone',...
                       'Toolbar','none'...               
                       );
        end

        setObjectIcon(dlgLiverAblationZone);

        % Joint Type

            uicontrol(dlgLiverAblationZone,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , ' Joint styles at segment endpoints',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 95 250 20]...
                      );


        switch lower(liverAblationMarginJointType('get'))

            case 'round'
                dJointTypeoffset = 1;

            case 'miter'
                dJointTypeoffset = 2;

            otherwise
                dJointTypeoffset = 3;
        end

        popLiverAblationJointType = ...
            uicontrol(dlgLiverAblationZone, ...
                      'enable'  , 'on',...
                      'Style'   , 'popup', ...
                      'position', [285 95 75 20],...
                      'String'  , {'Round', 'Miter', 'Square'}, ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Value'   , dJointTypeoffset, ...
                      'Callback', @popLiverAblationJointTypeCallback...
                      );

         % Margin Distance (mm)
    
            uicontrol(dlgLiverAblationZone,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Margin Distance (mm)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 65 250 20]...
                      );
    
        edtLiverAblationMarginDistanceValue = ...
            uicontrol(dlgLiverAblationZone, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 65 75 20], ...
                      'String'  , num2str(liverAblationMarginDistanceValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtLiverAblationMarginDistanceValueCallback ...
                      );        
    
         % Cancel or Proceed
    
         uicontrol(dlgLiverAblationZone,...
                   'String','Cancel',...
                   'Position',[285 7 75 25],...
                   'BackgroundColor', viewerBackgroundColor('get'), ...
                   'ForegroundColor', viewerForegroundColor('get'), ...                
                   'Callback', @cancelLiverAblationMarginCallback...
                   );
    
         uicontrol(dlgLiverAblationZone,...
                  'String','Proceed',...
                  'Position',[200 7 75 25],...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...               
                  'Callback', @proceedLiverAblationMarginCallback...
                  );   

    else
        
        createTumorAblationZone(liverAblationMarginDistanceValue('get'), liverAblationMarginJointType('get'));

        % Export RT-structure

        writeRTStructCallback();
    
        % Exit the compiled executable
        
        close(fiMainWindowPtr('get'));  
    end

    function popLiverAblationJointTypeCallback(~, ~)

        asJointType = get(popLiverAblationJointType, 'string');
        dJointTypeOffset = get(popLiverAblationJointType, 'value');

        liverAblationMarginJointType('set', lower(asJointType{dJointTypeOffset}));

    end


    function edtLiverAblationMarginDistanceValueCallback(~, ~)

        dObjectValue = str2double(get(edtLiverAblationMarginDistanceValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 1;

            set(edtLiverAblationMarginDistanceValue, 'String', num2str(dObjectValue));
        end

        liverAblationMarginDistanceValue('set', dObjectValue);

    end

    function cancelLiverAblationMarginCallback(~, ~)

        delete(dlgLiverAblationZone);
    end

    function proceedLiverAblationMarginCallback(~, ~)

        dMarginSize = str2double(get(edtLiverAblationMarginDistanceValue, 'String'));

        asJointType = get(popLiverAblationJointType, 'string');
        dJointTypeOffset = get(popLiverAblationJointType, 'value');

        sJointType = lower(asJointType{dJointTypeOffset});

        delete(dlgLiverAblationZone);

        createTumorAblationZone(dMarginSize, sJointType);
    end
end