function normalLiverLobedRatioCallback(hObject, ~)
%function normalLiverLobedRatioCallback(hObject, ~)
%Split liver in 8 zones and export the statistics.This tool os calld from
%the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2025, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    if exist('hObject', 'var')

        DLG_HAI_RATIO_X = 380;
        DLG_HAI_RATIO_Y = 145;

        if viewerUIFigure('get') == true
    
            dlgHaiRatioZone = ...
                uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_HAI_RATIO_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_HAI_RATIO_Y/2) ...
                                    DLG_HAI_RATIO_X ...
                                    DLG_HAI_RATIO_Y ...
                                    ],...
                       'Resize', 'off', ...
                       'Color', viewerBackgroundColor('get'),...
                       'WindowStyle', 'modal', ...
                       'Name' , 'Normal Liver Step Ratio Analysist'...
                       );
        else      
            dlgHaiRatioZone = ...
                dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_HAI_RATIO_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_HAI_RATIO_Y/2) ...
                                    DLG_HAI_RATIO_X ...
                                    DLG_HAI_RATIO_Y ...
                                    ],...
                       'MenuBar', 'none',...
                       'Resize', 'off', ...    
                       'NumberTitle','off',...
                       'MenuBar', 'none',...
                       'Color', viewerBackgroundColor('get'), ...
                       'Name', 'Normal Liver Step Ratio Analysist',...
                       'Toolbar','none'...               
                       );
        end

        setObjectIcon(dlgHaiRatioZone);     

         % Margin Distance (mm)
    
            uicontrol(dlgHaiRatioZone,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'VOIs Expansion Margin (mm)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 90 250 20]...
                      );
    
        edtHaiPercentOfNormalMarginDistanceValue = ...
            uicontrol(dlgHaiRatioZone, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 90 75 20], ...
                      'String'  , num2str(haiZoningMarginDistanceValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtHaiPercentOfNormalMarginDistanceValueCallback ...
                      );  


         % Percent of normal liver
    
            uicontrol(dlgHaiRatioZone,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Percent of normal liver',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 65 250 20]...
                      );
    
        edtHaiPercentOfNormalLiverValue = ...
            uicontrol(dlgHaiRatioZone, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 65 75 20], ...
                      'String'  , num2str(haiPercentOfNormalLiverValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtHaiPercentOfNormalLiverValueCallback ...
                      );   

         % Cancel or Proceed
    
         uicontrol(dlgHaiRatioZone,...
                   'String','Cancel',...
                   'Position',[285 7 75 25],...
                   'BackgroundColor', viewerBackgroundColor('get'), ...
                   'ForegroundColor', viewerForegroundColor('get'), ...                
                   'Callback', @cancelHaiRatioCallback...
                   );
    
         uicontrol(dlgHaiRatioZone,...
                  'String','Proceed',...
                  'Position',[200 7 75 25],...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...               
                  'Callback', @proceedHaiRatioCallback...
                  );   

    else
        
        normalLiverLobedRatio(haiZoningMarginDistanceValue('get'), haiPercentOfNormalLiverValue('get'), false);
    
        % Exit the compiled executable
        
        close(fiMainWindowPtr('get'));  
    end 

    function edtHaiPercentOfNormalMarginDistanceValueCallback(hObject, ~)

        dValue = str2double(get(hObject, 'String'));

        if dValue < 0

            dValue = 0;

            set(hObject, 'String', num2str(dValue));
        end

        haiZoningMarginDistanceValue('set', dValue);

    end

    function edtHaiPercentOfNormalLiverValueCallback(hObject, ~)

        dValue = str2double(get(hObject, 'String'));

        if dValue < 0

            dValue = 0;

            set(hObject, 'String', num2str(dValue));
        end

        haiPercentOfNormalLiverValue('set', dValue);

    end

    function cancelHaiRatioCallback(~, ~)

        delete(dlgHaiRatioZone);
    end

    function proceedHaiRatioCallback(~, ~)

        dMarginSize = str2double(get(edtHaiPercentOfNormalMarginDistanceValue, 'String'));
        dPercentOfNormalLiver = str2double(get(edtHaiPercentOfNormalLiverValue, 'String'));

        delete(dlgHaiRatioZone);

        normalLiverLobedRatio(dMarginSize, dPercentOfNormalLiver, true);
    end
end