function setSegmentationLu177Callback(hObject, ~)
%function setSegmentationLu177Callback()
%Run Lu177 Tumor Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2023, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    if exist('hObject', 'var')

        DLG_Lu177_PERCENT_X = 380;
        DLG_Lu177_PERCENT_Y = 160;

        if viewerUIFigure('get') == true
    
            dlgLu177Segmentation = ...
                uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_Lu177_PERCENT_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_Lu177_PERCENT_Y/2) ...
                                    DLG_Lu177_PERCENT_X ...
                                    DLG_Lu177_PERCENT_Y ...
                                    ],...
                       'Resize', 'off', ...
                       'Color', viewerBackgroundColor('get'),...
                       'WindowStyle', 'modal', ...
                       'Name' , 'PSMA - Lu177 Segmentation'...
                       );
        else       
            dlgLu177Segmentation = ...
                dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_Lu177_PERCENT_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_Lu177_PERCENT_Y/2) ...
                                    DLG_Lu177_PERCENT_X ...
                                    DLG_Lu177_PERCENT_Y ...
                                    ],...
                       'MenuBar', 'none',...
                       'Resize', 'off', ...    
                       'NumberTitle','off',...
                       'MenuBar', 'none',...
                       'Color', viewerBackgroundColor('get'), ...
                       'Name', 'PSMA - Lu177 Segmentation',...
                       'Toolbar','none'...               
                       );
        end

        setObjectIcon(dlgLu177Segmentation);

    %     % Boundary percent of max
    % 
    %         uicontrol(dlgLu177Segmentation,...
    %                   'style'   , 'text',...
    %                   'Enable'  , 'On',...
    %                   'string'  , 'Boundary percent of max',...
    %                   'horizontalalignment', 'left',...
    %                   'BackgroundColor', viewerBackgroundColor('get'), ...
    %                   'ForegroundColor', viewerForegroundColor('get'), ...                   
    %                   'position', [20 162 250 20]...
    %                   );
    % 
    %     edtLu177BoundaryPercentOfMaxValue = ...
    %         uicontrol(dlgLu177Segmentation, ...
    %                   'Style'   , 'Edit', ...
    %                   'Position', [285 165 75 20], ...
    %                   'String'  , num2str(Lu177SegmentationBoundaryPercentValue('get')), ...
    %                   'Enable'  , 'on', ...
    %                   'BackgroundColor', viewerBackgroundColor('get'), ...
    %                   'ForegroundColor', viewerForegroundColor('get'), ...
    %                   'CallBack', @edtLu177BoundaryPercentOfMaxValueCallback ...
    %                   ); 
    
        % Bone mask threshold
    
            uicontrol(dlgLu177Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Bone mask threshold (HU)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 112 250 20]...
                      );
    
        edtLu177BoneMaskThresholdValue = ...
            uicontrol(dlgLu177Segmentation, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 115 75 20], ...
                      'String'  , num2str(Lu177SegmentationBoneMaskThresholdValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtLu177BoneMaskThresholdValueCallback ...
                      ); 
    
         % Smallest Contour (ml)
    
            uicontrol(dlgLu177Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Smallest Contour (ml)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 90 250 20]...
                      );
    
        edtLu177SmalestVoiValue = ...
            uicontrol(dlgLu177Segmentation, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 90 75 20], ...
                      'String'  , num2str(Lu177SmalestVoiValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtLu177SmalestVoiValueCallback ...
                      );        
    
        % Pixel Edge
    
            uicontrol(dlgLu177Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Pixel Edge',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkLu177PixelEdgeCallback, ...
                      'position', [40 65 150 20]...
                      );
    
        chkLu177PixelEdge = ...
            uicontrol(dlgLu177Segmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , pixelEdge('get'),...
                      'position', [20 65 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkLu177PixelEdgeCallback...
                      );
    
         % Cancel or Proceed
    
         uicontrol(dlgLu177Segmentation,...
                   'String','Cancel',...
                   'Position',[285 7 75 25],...
                   'BackgroundColor', viewerBackgroundColor('get'), ...
                   'ForegroundColor', viewerForegroundColor('get'), ...                
                   'Callback', @cancelLu177SegmentationCallback...
                   );
    
         uicontrol(dlgLu177Segmentation,...
                  'String','Continue',...
                  'Position',[200 7 75 25],...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...               
                  'Callback', @proceedLu177SegmentationCallback...
                  );    

    else % Execute the segmentation using the default values

        setSegmentationLu177(Lu177SegmentationBoneMaskThresholdValue('get'), ...
                             Lu177SmalestVoiValue('get'), ...
                             pixelEdge('get'), ...
                             true); 
    end

    function edtLu177SmalestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtLu177SmalestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtLu177SmalestVoiValue, 'String', num2str(dObjectValue));
        end

        Lu177SmalestVoiValue('set', dObjectValue);

    end

    function chkLu177PixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkLu177PixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkLu177PixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkLu177PixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox
        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end

%     function edtLu177BoundaryPercentOfMaxValueCallback(~, ~)     
% 
%         dBoundaryPercent = str2double(get(edtLu177BoundaryPercentOfMaxValue, 'String'));
% 
%         if dBoundaryPercent <= 0
% 
%             dBoundaryPercent = 10;
%             set(edtLu177BoundaryPercentOfMaxValue, 'String', num2str(dBoundaryPercent));
% 
%         elseif dBoundaryPercent >= 100
%             
%             dBoundaryPercent = 10;
%             set(edtLu177BoundaryPercentOfMaxValue, 'String', num2str(dBoundaryPercent));           
%         end
% 
%         Lu177SegmentationBoundaryPercentValue('set', dBoundaryPercent);
% 
%     end

    function edtLu177BoneMaskThresholdValueCallback(~, ~)     

        dBoneMaskThreshold = str2double(get(edtLu177BoneMaskThresholdValue, 'String'));

        if dBoneMaskThreshold <= 0

            dBoneMaskThreshold = 100;
            set(edtLu177BoneMaskThresholdValue, 'String', num2str(dBoneMaskThreshold));        
        end

        Lu177SegmentationBoneMaskThresholdValue('set', dBoneMaskThreshold);

    end

    function cancelLu177SegmentationCallback(~, ~)   

        delete(dlgLu177Segmentation);
    end
    
    function proceedLu177SegmentationCallback(~, ~)

        dSmalestVoiValue   = str2double(get(edtLu177SmalestVoiValue, 'String'));
        dPixelEdge         = get(chkLu177PixelEdge, 'value');
%         dBoundaryPercent   = str2double(get(edtLu177BoundaryPercentOfMaxValue, 'String'))/100;
        dBoneMaskThreshold = str2double(get(edtLu177BoneMaskThresholdValue, 'String'));

        delete(dlgLu177Segmentation);

        setSegmentationLu177(dBoneMaskThreshold, dSmalestVoiValue, dPixelEdge, false); 
    end

end