function setSegmentationGa68Callback(hObject, ~)
%function setSegmentationGa68Callback(hObject)
%Run Ga68 Tumor Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2023, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    if exist('hObject', 'var')

        DLG_Ga68_PERCENT_X = 380;
        DLG_Ga68_PERCENT_Y = 480;

        if viewerUIFigure('get') == true
    
            dlgGa68Segmentation = ...
                uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_Ga68_PERCENT_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_Ga68_PERCENT_Y/2) ...
                                    DLG_Ga68_PERCENT_X ...
                                    DLG_Ga68_PERCENT_Y ...
                                    ],...
                       'Resize', 'off', ...
                       'Color', viewerBackgroundColor('get'),...
                       'WindowStyle', 'modal', ...
                       'Name' , 'PSMA - Ga68 Segmentation'...
                       );
        else      
            dlgGa68Segmentation = ...
                dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_Ga68_PERCENT_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_Ga68_PERCENT_Y/2) ...
                                    DLG_Ga68_PERCENT_X ...
                                    DLG_Ga68_PERCENT_Y ...
                                    ],...
                       'MenuBar', 'none',...
                       'Resize', 'off', ...    
                       'NumberTitle','off',...
                       'MenuBar', 'none',...
                       'Color', viewerBackgroundColor('get'), ...
                       'Name', 'PSMA - Ga68 Segmentation',...
                       'Toolbar','none'...               
                       );
        end

        setObjectIcon(dlgGa68Segmentation);

    %     % Boundary percent of max
    % 
    %         uicontrol(dlgGa68Segmentation,...
    %                   'style'   , 'text',...
    %                   'Enable'  , 'On',...
    %                   'string'  , 'Boundary percent of max',...
    %                   'horizontalalignment', 'left',...
    %                   'BackgroundColor', viewerBackgroundColor('get'), ...
    %                   'ForegroundColor', viewerForegroundColor('get'), ...                   
    %                   'position', [20 162 250 20]...
    %                   );
    % 
    %     edtGa68BoundaryPercentOfMaxValue = ...
    %         uicontrol(dlgGa68Segmentation, ...
    %                   'Style'   , 'Edit', ...
    %                   'Position', [285 165 75 20], ...
    %                   'String'  , num2str(PSMASegmentationBoundaryPercentValue('get')), ...
    %                   'Enable'  , 'on', ...
    %                   'BackgroundColor', viewerBackgroundColor('get'), ...
    %                   'ForegroundColor', viewerForegroundColor('get'), ...
    %                   'CallBack', @edtGa68BoundaryPercentOfMaxValueCallback ...
    %                   ); 
            % Exclude organs from AI analysis
    
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Exclude AI organs from segmentation (slower)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68ExcludeOrgansCallback, ...
                      'position', [40 440 300 20]...
                      );

        chkGa68ExcludeOrgans = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , PSMAExcludeOrgansFromSegmentation('get'),...
                      'position', [20 440 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68ExcludeOrgansCallback...
                      );

        % Brain

        bExcludeOrgans = get(chkGa68ExcludeOrgans, 'value');

        if bExcludeOrgans == true
            sTxtOrgansEnable = 'Inactive';
            sChkOrgansEnable = 'on';
        else
            sTxtOrgansEnable = 'on';
            sChkOrgansEnable = 'off';
        end

        txtGa68Brain = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , sTxtOrgansEnable,...
                      'string'  , 'Brain',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68BrainCallback, ...
                      'position', [60 415 150 20]...
                      );
    
        chkGa68Brain = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , sChkOrgansEnable,...
                      'value'   , excludePSMABrain('get'),...
                      'position', [40 415 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68BrainCallback...
                      );
    
        % Spleen
    
        txtGa68Spleen = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , sTxtOrgansEnable,...
                      'string'  , 'Spleen',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68SpleenCallback, ...
                      'position', [60 390 150 20]...
                      );
    
        chkGa68Spleen = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'checkbox',...
                      'Enable'  , sChkOrgansEnable,...
                      'value'   , excludePSMASpleen('get'),...
                      'position', [40 390 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68SpleenCallback...
                      );
        % Liver
    
        txtGa68Liver = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , sTxtOrgansEnable,...
                      'string'  , 'Liver',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68LiverCallback, ...
                      'position', [60 365 150 20]...
                      );
    
        chkGa68Liver = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'checkbox',...
                      'Enable'  , sChkOrgansEnable,...
                      'value'   , excludePSMALiver('get'),...
                      'position', [40 365 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68LiverCallback...
                      );

        % Kidney left
    
        txtGa68KidneyLeft = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , sTxtOrgansEnable,...
                      'string'  , 'Kidney left',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68KidneyLeftCallback, ...
                      'position', [60 340 150 20]...
                      );
    
        chkGa68KidneyLeft = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'checkbox',...
                      'Enable'  , sChkOrgansEnable,...
                      'value'   , excludePSMAKidneyLeft('get'),...
                      'position', [40 340 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68KidneyLeftCallback...
                      );
    
        % Kidney right
    
        txtGa68KidneyRight = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , sTxtOrgansEnable,...
                      'string'  , 'Kidney right',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68KidneyRightCallback, ...
                      'position', [60 315 150 20]...
                      );
    
        chkGa68KidneyRight = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'checkbox',...
                      'Enable'  , sChkOrgansEnable,...
                      'value'   , excludePSMAKidneyRight('get'),...
                      'position', [40 315 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68KidneyRightCallback...
                      );

        % Stomach

         txtGa68Stomach = ...
           uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , sTxtOrgansEnable,...
                      'string'  , 'Stomach',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68StomachCallback, ...
                      'position', [60 290 150 20]...
                      );
    
        chkGa68Stomach = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'checkbox',...
                      'Enable'  , sChkOrgansEnable,...
                      'value'   , excludePSMAStomach('get'),...
                      'position', [40 290 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68StomachCallback...
                      );

        % Duodenum
    
         txtGa68Duodenum = ...
           uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , sTxtOrgansEnable,...
                      'string'  , 'Duodenum',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DuodenumCallback, ...
                      'position', [60 265 150 20]...
                      );
    
        chkGa68Duodenum = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'checkbox',...
                      'Enable'  , sChkOrgansEnable,...
                      'value'   , excludePSMADuodenum('get'),...
                      'position', [40 265 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DuodenumCallback...
                      );
        % Colon
    
         txtGa68Colon = ...
           uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , sTxtOrgansEnable,...
                      'string'  , 'Colon',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68ColonCallback, ...
                      'position', [60 240 150 20]...
                      );
    
        chkGa68Colon = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'checkbox',...
                      'Enable'  , sChkOrgansEnable,...
                      'value'   , excludePSMAColon('get'),...
                      'position', [40 240 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68ColonCallback...
                      );

        % Small bowel
    
         txtGa68SmallBowel = ...
           uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , sTxtOrgansEnable,...
                      'string'  , 'Small bowel',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68SmallBowelCallback, ...
                      'position', [60 215 150 20]...
                      );
    
        chkGa68SmallBowel = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'checkbox',...
                      'Enable'  , sChkOrgansEnable,...
                      'value'   , excludePSMASmallBowel('get'),...
                      'position', [40 215 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68SmallBowelCallback...
                      );
    
        % Urinary bladder
    
        txtGa68UrinaryBladder = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , sTxtOrgansEnable,...
                      'string'  , 'Urinary bladder',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68UrinaryBladderCallback, ...
                      'position', [60 190 150 20]...
                      );
    
        chkGa68UrinaryBladder = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'checkbox',...
                      'Enable'  , sChkOrgansEnable,...
                      'value'   , excludePSMAUrinaryBladder('get'),...
                      'position', [40 190 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68UrinaryBladderCallback...
                      ); 
  
        % Options

        % Organs margin (pixel)
    
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Organ margins (pixel)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 140 250 20]...
                      );
    
        edtGa68ExcludeMarginValue = ...
            uicontrol(dlgGa68Segmentation, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 140 75 20], ...
                      'String'  , num2str(PSMAExcludeOrganMarginsValue('get')), ...
                      'Enable'  , sChkOrgansEnable, ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtGa68ExcludeMarginValueCallback ...
                      );   

            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Bone mask threshold (HU)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 115 250 20]...
                      );
    
        edtGa68BoneMaskThresholdValue = ...
            uicontrol(dlgGa68Segmentation, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 115 75 20], ...
                      'String'  , num2str(PSMASegmentationBoneMaskThresholdValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtGa68BoneMaskThresholdValueCallback ...
                     );

         % Smallest Contour (ml)
    
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Smallest Contour (ml)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 90 250 20]...
                      );
    
        edtGa68SmalestVoiValue = ...
            uicontrol(dlgGa68Segmentation, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 90 75 20], ...
                      'String'  , num2str(PSMASmalestVoiValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtGa68SmalestVoiValueCallback ...
                      );        
    
        % Pixel Edge
    
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Pixel Edge',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68PixelEdgeCallback, ...
                      'position', [40 65 150 20]...
                      );
    
        chkGa68PixelEdge = ...
            uicontrol(dlgGa68Segmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , pixelEdge('get'),...
                      'position', [20 65 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68PixelEdgeCallback...
                      );
    
         % Cancel or Proceed
    
         uicontrol(dlgGa68Segmentation,...
                   'String','Cancel',...
                   'Position',[285 7 75 25],...
                   'BackgroundColor', viewerBackgroundColor('get'), ...
                   'ForegroundColor', viewerForegroundColor('get'), ...                
                   'Callback', @cancelGa68SegmentationCallback...
                   );
    
         uicontrol(dlgGa68Segmentation,...
                  'String','Continue',...
                  'Position',[200 7 75 25],...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...               
                  'Callback', @proceedGa68SegmentationCallback...
                  );    
    else

        if PSMAExcludeOrgansFromSegmentation('get') == true
            [sSegmentatorScript, ~] = validateSegmentatorInstallation();
            if isempty(sSegmentatorScript)
                return;
            end
        else
            sSegmentatorScript = [];
        end

        % Other Organs

        tGa68.exclude.organ.brain       = excludePSMABrain('get');
        tGa68.exclude.organ.kidneyLeft  = excludePSMAKidneyLeft('get');
        tGa68.exclude.organ.kidneyRight = excludePSMAKidneyRight('get');
        tGa68.exclude.organ.spleen      = excludePSMASpleen('get');
        tGa68.exclude.organ.liver       = excludePSMALiver('get');

        % Gastrointestinal Tract Name

        tGa68.exclude.gastrointestinal.smallBowel     = excludePSMASmallBowel('get');
        tGa68.exclude.gastrointestinal.urinaryBladder = excludePSMAUrinaryBladder('get');
        tGa68.exclude.gastrointestinal.duodenum       = excludePSMADuodenum('get');
        tGa68.exclude.gastrointestinal.stomach        = excludePSMAStomach('get');
        tGa68.exclude.gastrointestinal.colon          = excludePSMAColon('get');

        % Options

        tGa68.options.excludeOrgansFromSegmentation = PSMAExcludeOrgansFromSegmentation('get');
        tGa68.options.excludeOrganMargins           = PSMAExcludeOrganMarginsValue('get');
        tGa68.options.boneMaskThresholdValue        = PSMASegmentationBoneMaskThresholdValue('get');
        tGa68.options.smalestVoiValue               = PSMASmalestVoiValue('get');
        tGa68.options.pixelEdge                     = pixelEdge('get');

        setSegmentationPSMA(sSegmentatorScript, tGa68, true); 

    end

    function chkGa68ExcludeOrgansCallback(hObject, ~)
        
        bObjectValue = get(chkGa68ExcludeOrgans, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68ExcludeOrgans, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68ExcludeOrgans, 'Value');

        PSMAExcludeOrgansFromSegmentation('set', bObjectValue);

        if bObjectValue == true

            set(txtGa68Brain         , 'enable', 'inactive');
            set(txtGa68KidneyLeft    , 'enable', 'inactive');
            set(txtGa68KidneyRight   , 'enable', 'inactive');
            set(txtGa68Spleen        , 'enable', 'inactive');
            set(txtGa68SmallBowel    , 'enable', 'inactive');
            set(txtGa68UrinaryBladder, 'enable', 'inactive');
            set(txtGa68Liver         , 'enable', 'inactive');  
            set(txtGa68Duodenum      , 'enable', 'inactive');  
            set(txtGa68Stomach       , 'enable', 'inactive');  
            set(txtGa68Colon         , 'enable', 'inactive');

            set(chkGa68Brain         , 'enable', 'on');
            set(chkGa68KidneyLeft    , 'enable', 'on');
            set(chkGa68KidneyRight   , 'enable', 'on');
            set(chkGa68Spleen        , 'enable', 'on');
            set(chkGa68SmallBowel    , 'enable', 'on');
            set(chkGa68UrinaryBladder, 'enable', 'on');  
            set(chkGa68Liver         , 'enable', 'on');  
            set(chkGa68Duodenum      , 'enable', 'on');  
            set(chkGa68Stomach       , 'enable', 'on');  
            set(chkGa68Colon         , 'enable', 'on');  

            set(edtGa68ExcludeMarginValue, 'enable', 'on');  
        else
            set(txtGa68Brain         , 'enable', 'on');
            set(txtGa68KidneyLeft    , 'enable', 'on');
            set(txtGa68KidneyRight   , 'enable', 'on');
            set(txtGa68Spleen        , 'enable', 'on');
            set(txtGa68SmallBowel    , 'enable', 'on');
            set(txtGa68UrinaryBladder, 'enable', 'on');
            set(txtGa68Liver         , 'enable', 'on');  
            set(txtGa68Duodenum      , 'enable', 'on');  
            set(txtGa68Stomach       , 'enable', 'on');  
            set(txtGa68Colon         , 'enable', 'on');

            set(chkGa68Brain         , 'enable', 'off');
            set(chkGa68KidneyLeft    , 'enable', 'off');
            set(chkGa68KidneyRight   , 'enable', 'off');
            set(chkGa68Spleen        , 'enable', 'off');
            set(chkGa68SmallBowel    , 'enable', 'off');
            set(chkGa68UrinaryBladder, 'enable', 'off');            
            set(chkGa68Liver         , 'enable', 'off');  
            set(chkGa68Duodenum      , 'enable', 'off');  
            set(chkGa68Stomach       , 'enable', 'off');  
            set(chkGa68Colon         , 'enable', 'off');

            set(edtGa68ExcludeMarginValue, 'enable', 'off');  
      
        end
        
    end

    % Exclude organs from analysis

    % Brain

    function chkGa68BrainCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68Brain, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68Brain, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68Brain, 'Value');

        excludePSMABrain('set', bObjectValue);

    end

    % Kidney Left

    function chkGa68KidneyLeftCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68KidneyLeft, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68KidneyLeft, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68KidneyLeft, 'Value');

        excludePSMAKidneyLeft('set', bObjectValue);

    end

    % Kidney Right

    function chkGa68KidneyRightCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68KidneyRight, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68KidneyRight, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68KidneyRight, 'Value');

        excludePSMAKidneyRight('set', bObjectValue);

    end

    % Small Bowel

    function chkGa68SmallBowelCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68SmallBowel, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68SmallBowel, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68SmallBowel, 'Value');

        excludePSMASmallBowel('set', bObjectValue);

    end


    % Spleen

    function chkGa68SpleenCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68Spleen, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68Spleen, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68Spleen, 'Value');

        excludePSMASpleen('set', bObjectValue);

    end

    function chkGa68UrinaryBladderCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68UrinaryBladder, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68UrinaryBladder, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68UrinaryBladder, 'Value');

        excludePSMAUrinaryBladder('set', bObjectValue);

    end 

    function chkGa68DuodenumCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68Duodenum, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68Duodenum, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68Duodenum, 'Value');

        excludePSMADuodenum('set', bObjectValue);

    end 

    function chkGa68StomachCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68Stomach, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68Stomach, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68Stomach, 'Value');

        excludePSMAStomach('set', bObjectValue);

    end 

    function chkGa68ColonCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68Colon, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68Colon, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68Colon, 'Value');

        excludePSMAColon('set', bObjectValue);

    end

    function chkGa68LiverCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68Liver, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68Liver, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68Liver, 'Value');

        excludePSMALiver('set', bObjectValue);

    end 

    function edtGa68SmalestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtGa68SmalestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtGa68SmalestVoiValue, 'String', num2str(dObjectValue));
        end

        PSMASmalestVoiValue('set', dObjectValue);

    end

    function chkGa68PixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68PixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68PixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68PixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox
        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end

%     function edtGa68BoundaryPercentOfMaxValueCallback(~, ~)     
% 
%         dBoundaryPercent = str2double(get(edtGa68BoundaryPercentOfMaxValue, 'String'));
% 
%         if dBoundaryPercent <= 0
% 
%             dBoundaryPercent = 10;
%             set(edtGa68BoundaryPercentOfMaxValue, 'String', num2str(dBoundaryPercent));
% 
%         elseif dBoundaryPercent >= 100
%             
%             dBoundaryPercent = 10;
%             set(edtGa68BoundaryPercentOfMaxValue, 'String', num2str(dBoundaryPercent));           
%         end
% 
%         PSMASegmentationBoundaryPercentValue('set', dBoundaryPercent);
% 
%     end
    
    function edtGa68ExcludeMarginValueCallback(~, ~)     

        dMargin = str2double(get(edtGa68ExcludeMarginValue, 'String'));

        if dMargin <= 0

            dMargin = 1;
            set(edtGa68ExcludeMarginValue, 'String', num2str(dMargin));        
        end

        PSMAExcludeOrganMarginsValue('set', dMargin);

    end

    function edtGa68BoneMaskThresholdValueCallback(~, ~)     

        dBoneMaskThreshold = str2double(get(edtGa68BoneMaskThresholdValue, 'String'));

        if dBoneMaskThreshold <= 0

            dBoneMaskThreshold = 100;
            set(edtGa68BoneMaskThresholdValue, 'String', num2str(dBoneMaskThreshold));        
        end

        PSMASegmentationBoneMaskThresholdValue('set', dBoneMaskThreshold);

    end

    function cancelGa68SegmentationCallback(~, ~)   

        delete(dlgGa68Segmentation);
    end
    
    function proceedGa68SegmentationCallback(~, ~)

        if get(chkGa68ExcludeOrgans, 'value') == true

            [sSegmentatorScript, ~] = validateSegmentatorInstallation();

            if isempty(sSegmentatorScript)
                delete(dlgGa68Segmentation);
               return;
            end
        else
            sSegmentatorScript = [];
        end

        % Other Organs

        tGa68.exclude.organ.brain       = get(chkGa68Brain      , 'value');
        tGa68.exclude.organ.kidneyLeft  = get(chkGa68KidneyLeft , 'value');
        tGa68.exclude.organ.kidneyRight = get(chkGa68KidneyRight, 'value');
        tGa68.exclude.organ.spleen      = get(chkGa68Spleen     , 'value');
        tGa68.exclude.organ.liver       = get(chkGa68Liver      , 'value');

        % Gastrointestinal Tract Name

        tGa68.exclude.gastrointestinal.smallBowel     = get(chkGa68SmallBowel    , 'value');
        tGa68.exclude.gastrointestinal.urinaryBladder = get(chkGa68UrinaryBladder, 'value');
        tGa68.exclude.gastrointestinal.duodenum       = get(chkGa68Duodenum, 'value');
        tGa68.exclude.gastrointestinal.stomach        = get(chkGa68Stomach, 'value');
        tGa68.exclude.gastrointestinal.colon          = get(chkGa68Colon, 'value');

        % Options

        tGa68.options.excludeOrgansFromSegmentation = get(chkGa68ExcludeOrgans, 'value');
        tGa68.options.excludeOrganMargins           = str2double(get(edtGa68ExcludeMarginValue, 'String'));
        tGa68.options.boneMaskThresholdValue        = str2double(get(edtGa68BoneMaskThresholdValue, 'String'));
        tGa68.options.smalestVoiValue               = str2double(get(edtGa68SmalestVoiValue, 'String'));
        tGa68.options.pixelEdge                     = get(chkGa68PixelEdge, 'value');

        delete(dlgGa68Segmentation);

        setSegmentationPSMA(sSegmentatorScript, tGa68, false); 
    end

end

