function setSegmentationFDCFPyLCallback(hObject, ~)
%function setSegmentationFDCFPyLCallback(hObject)
%Run FDCFPyL Tumor Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2023, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    if exist('hObject', 'var')

        DLG_FDCFPyL_PERCENT_X = 380;
        DLG_FDCFPyL_PERCENT_Y = 160;

        if viewerUIFigure('get') == true
    
            dlgFDCFPyLSegmentation = ...
                uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_FDCFPyL_PERCENT_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_FDCFPyL_PERCENT_Y/2) ...
                                    DLG_FDCFPyL_PERCENT_X ...
                                    DLG_FDCFPyL_PERCENT_Y ...
                                    ],...
                       'Resize', 'off', ...
                       'Color', viewerBackgroundColor('get'),...
                       'WindowStyle', 'modal', ...
                       'Name' , 'PSMA - 18F-FDCFPyL Segmentation'...
                       );
        else      
            dlgFDCFPyLSegmentation = ...
                dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_FDCFPyL_PERCENT_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_FDCFPyL_PERCENT_Y/2) ...
                                    DLG_FDCFPyL_PERCENT_X ...
                                    DLG_FDCFPyL_PERCENT_Y ...
                                    ],...
                       'MenuBar', 'none',...
                       'Resize', 'off', ...    
                       'NumberTitle','off',...
                       'MenuBar', 'none',...
                       'Color', viewerBackgroundColor('get'), ...
                       'Name', 'PSMA - 18F-FDCFPyL Segmentation',...
                       'Toolbar','none'...               
                       );
        end

        setObjectIcon(dlgFDCFPyLSegmentation);

    %     % Boundary percent of max
    % 
    %         uicontrol(dlgFDCFPyLSegmentation,...
    %                   'style'   , 'text',...
    %                   'Enable'  , 'On',...
    %                   'string'  , 'Boundary percent of max',...
    %                   'horizontalalignment', 'left',...
    %                   'BackgroundColor', viewerBackgroundColor('get'), ...
    %                   'ForegroundColor', viewerForegroundColor('get'), ...                   
    %                   'position', [20 162 250 20]...
    %                   );
    % 
    %     edtFDCFPyLBoundaryPercentOfMaxValue = ...
    %         uicontrol(dlgFDCFPyLSegmentation, ...
    %                   'Style'   , 'Edit', ...
    %                   'Position', [285 165 75 20], ...
    %                   'String'  , num2str(PSMASegmentationBoundaryPercentValue('get')), ...
    %                   'Enable'  , 'on', ...
    %                   'BackgroundColor', viewerBackgroundColor('get'), ...
    %                   'ForegroundColor', viewerForegroundColor('get'), ...
    %                   'CallBack', @edtFDCFPyLBoundaryPercentOfMaxValueCallback ...
    %                   ); 
    
        % Bone mask threshold
    
            uicontrol(dlgFDCFPyLSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Bone mask threshold (HU)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 115 250 20]...
                      );
    
        edtFDCFPyLBoneMaskThresholdValue = ...
            uicontrol(dlgFDCFPyLSegmentation, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 115 75 20], ...
                      'String'  , num2str(PSMASegmentationBoneMaskThresholdValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtFDCFPyLBoneMaskThresholdValueCallback ...
                      ); 
    
         % Smallest Contour (ml)
    
            uicontrol(dlgFDCFPyLSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Smallest Contour (ml)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 90 250 20]...
                      );
    
        edtFDCFPyLSmalestVoiValue = ...
            uicontrol(dlgFDCFPyLSegmentation, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 90 75 20], ...
                      'String'  , num2str(PSMASmalestVoiValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtFDCFPyLSmalestVoiValueCallback ...
                      );        
    
        % Pixel Edge
    
            uicontrol(dlgFDCFPyLSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Pixel Edge',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkFDCFPyLPixelEdgeCallback, ...
                      'position', [40 65 150 20]...
                      );
    
        chkFDCFPyLPixelEdge = ...
            uicontrol(dlgFDCFPyLSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , pixelEdge('get'),...
                      'position', [20 65 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkFDCFPyLPixelEdgeCallback...
                      );
    
         % Cancel or Proceed
    
         uicontrol(dlgFDCFPyLSegmentation,...
                   'String','Cancel',...
                   'Position',[285 7 75 25],...
                   'BackgroundColor', viewerBackgroundColor('get'), ...
                   'ForegroundColor', viewerForegroundColor('get'), ...                
                   'Callback', @cancelFDCFPyLSegmentationCallback...
                   );
    
         uicontrol(dlgFDCFPyLSegmentation,...
                  'String','Continue',...
                  'Position',[200 7 75 25],...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...               
                  'Callback', @proceedFDCFPyLSegmentationCallback...
                  );    
    else
        setSegmentationPSMA(PSMASegmentationBoneMaskThresholdValue('get'), ...
                            PSMASmalestVoiValue('get'), ...
                            pixelEdge('get'), ...
                            true); 

    end

    function edtFDCFPyLSmalestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtFDCFPyLSmalestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtFDCFPyLSmalestVoiValue, 'String', num2str(dObjectValue));
        end

        PSMASmalestVoiValue('set', dObjectValue);

    end

    function chkFDCFPyLPixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkFDCFPyLPixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDCFPyLPixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDCFPyLPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox
        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end

%     function edtFDCFPyLBoundaryPercentOfMaxValueCallback(~, ~)     
% 
%         dBoundaryPercent = str2double(get(edtFDCFPyLBoundaryPercentOfMaxValue, 'String'));
% 
%         if dBoundaryPercent <= 0
% 
%             dBoundaryPercent = 10;
%             set(edtFDCFPyLBoundaryPercentOfMaxValue, 'String', num2str(dBoundaryPercent));
% 
%         elseif dBoundaryPercent >= 100
%             
%             dBoundaryPercent = 10;
%             set(edtFDCFPyLBoundaryPercentOfMaxValue, 'String', num2str(dBoundaryPercent));           
%         end
% 
%         PSMASegmentationBoundaryPercentValue('set', dBoundaryPercent);
% 
%     end

    function edtFDCFPyLBoneMaskThresholdValueCallback(~, ~)     

        dBoneMaskThreshold = str2double(get(edtFDCFPyLBoneMaskThresholdValue, 'String'));

        if dBoneMaskThreshold <= 0

            dBoneMaskThreshold = 100;
            set(edtFDCFPyLBoneMaskThresholdValue, 'String', num2str(dBoneMaskThreshold));        
        end

        PSMASegmentationBoneMaskThresholdValue('set', dBoneMaskThreshold);

    end

    function cancelFDCFPyLSegmentationCallback(~, ~)   

        delete(dlgFDCFPyLSegmentation);
    end
    
    function proceedFDCFPyLSegmentationCallback(~, ~)

        dSmalestVoiValue   = str2double(get(edtFDCFPyLSmalestVoiValue, 'String'));
        dPixelEdge         = get(chkFDCFPyLPixelEdge, 'value');
%         dBoundaryPercent   = str2double(get(edtFDCFPyLBoundaryPercentOfMaxValue, 'String'))/100;
        dBoneMaskThreshold = str2double(get(edtFDCFPyLBoneMaskThresholdValue, 'String'));

        delete(dlgFDCFPyLSegmentation);

        setSegmentationPSMA(dBoneMaskThreshold, dSmalestVoiValue, dPixelEdge, false); 
    end

end