function [sSeriesDescriptionReturnValue, bBypassDialogReturnValue] = getViewerSeriesDescriptionDialog(sSeriesDescription, bBypassDialog)
% function [sSeriesDescriptionReturnValue, bBypassDialogReturnValue] = getViewerSeriesDescriptionDialog(sSeriesDescription, bBypassDialog)
% getViewerSeriesDescriptionDialog Create a dialog and return a new label.
%
%   [sSeriesDescriptionReturnValue, bBypassDialogReturnValue] =
%   getViewerSeriesDescriptionDialog(sSeriesDescription, bBypassDialog) creates a
%   modal dialog for editing the series description. Option settings must fit
%   on one line and can contain one semicolon at most. Options can be strings,
%   cell arrays of strings, or numerical arrays.
%
%   Inputs:
%       sSeriesDescription - Initial series description (string).
%       bBypassDialog      - (optional) Logical flag; if true, bypass the dialog.
%
%   Outputs:
%       sSeriesDescriptionReturnValue - Updated series description.
%       bBypassDialogReturnValue      - Logical flag indicating whether to
%                                       bypass the dialog in future.
%
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2022, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.cIf not, see <http://www.gnu.org/licenses/>.

    try

    if exist('bBypassDialog', 'var')

        if bBypassDialog == false

            dDialogYSize = 145;
        else
            progressBar(1, 'Bypass: getViewerSeriesDescriptionDialog()');        

            bBypassDialogReturnValue = bBypassDialog;             
            sSeriesDescriptionReturnValue = sSeriesDescription;
            return;
        end
    else
        dDialogYSize = 120;
    end

    if viewerUIFigure('get') == true

        dlgRtStructSeriesDescription = ...
            uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                                  (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-120/2) ...
                                  380 ...
                                  dDialogYSize ...
                                  ],...
                   'Resize'     , 'off', ...
                   'Color'      , viewerBackgroundColor('get'),...
                   'WindowStyle', 'modal', ...
                   'Name'       , 'Edit Series Description'...
                   );
    else

        dlgRtStructSeriesDescription = ...
            dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                               (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-120/2) ...
                               380 ...
                               dDialogYSize ...
                               ],...
               'MenuBar'    , 'none',...
               'Resize'     , 'off', ...    
               'NumberTitle', 'off',...
               'MenuBar'    , 'none',...
               'Color'      , viewerBackgroundColor('get'), ...
               'Name'       , 'Edit Series Description',...
               'Toolbar'    ,'none'...   
               );  
    end

    setObjectIcon(dlgRtStructSeriesDescription);              

        axes(dlgRtStructSeriesDescription, ...
             'Units'   , 'pixels', ...
             'Position', get(dlgRtStructSeriesDescription, 'Position'), ...
             'Color'   , viewerBackgroundColor('get'),...
             'XColor'  , viewerForegroundColor('get'),...
             'YColor'  , viewerForegroundColor('get'),...
             'ZColor'  , viewerForegroundColor('get'),...             
             'Visible' , 'off'...             
             ); 
         
    if exist('bBypassDialog', 'var')
         
        chkBypassDialog = ...
            uicontrol(dlgRtStructSeriesDescription,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , 0,...
                      'position', [20 90 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                    
                      'Callback', @chkBypassDialogCallback...
                      );

             uicontrol(dlgRtStructSeriesDescription,...
                      'style'   , 'text',...
                      'string'  , 'Dont display again',...
                      'horizontalalignment', 'left',...
                      'position', [40 87 200 20],...
                      'Enable', 'Inactive',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                    
                      'ButtonDownFcn', @chkBypassDialogCallback...
                      );  
    end
    
     uicontrol(dlgRtStructSeriesDescription,...
              'style'   , 'text',...
              'enable'  , 'On',...
              'string'  , 'Series Description',...
              'horizontalalignment', 'left',...
              'BackgroundColor', viewerBackgroundColor('get'), ...
              'ForegroundColor', viewerForegroundColor('get'), ...                     
              'position', [20 62 140 20]...
              );


    edtRtStructSeriesDescription = ...
        uicontrol(dlgRtStructSeriesDescription,...
                 'enable'    , 'on',...
                 'style'     , 'edit',...
                 'Background', 'white',...
                 'string'    , sSeriesDescription,...
                 'BackgroundColor', viewerBackgroundColor('get'), ...
                 'ForegroundColor', viewerForegroundColor('get'), ...                    
                 'position'  , [160 65 200 20]...
                 );


    % Cancel or Proceed

    uiCancelViewerSeriesDescription = ...
        uicontrol(dlgRtStructSeriesDescription,...
                   'String','Cancel',...
                   'Position',[285 7 75 25],...
                   'BackgroundColor', viewerBackgroundColor('get'), ...
                   'ForegroundColor', viewerForegroundColor('get'), ...                  
                   'Callback', @cancelViewerSeriesDescriptionCallback...
                   );

         uicontrol(dlgRtStructSeriesDescription,...
                  'String','Ok',...
                  'Position',[200 7 75 25],...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...                 
                  'Callback', @okViewerSeriesDescriptionCallback...
                  );  
              
    bBypassDialogReturnValue = false;             
    sSeriesDescriptionReturnValue = [];
    
    waitfor(uiCancelViewerSeriesDescription); 

    catch ME
        logErrorToFile(ME);
        progressBar(1, 'Error: getViewerSeriesDescriptionDialog()' );        
    end

    function chkBypassDialogCallback(hObject, ~)
        
        if strcmpi(hObject.Style, 'checkbox')

            bNewVal = get(chkBypassDialog, 'Value');
        else
            bNewVal = ~get(chkBypassDialog, 'Value');
        end       

        set(chkBypassDialog, 'Value', bNewVal);

    end
    
    function cancelViewerSeriesDescriptionCallback(~, ~)

        delete(dlgRtStructSeriesDescription);

    end % cancelViewerSeriesDescriptionCallback()

    function okViewerSeriesDescriptionCallback(~, ~)

        sSeriesDescriptionReturnValue = get(edtRtStructSeriesDescription, 'String');
        
        if exist('bBypassDialog', 'var')

            bBypassDialogReturnValue = get(chkBypassDialog, 'Value');
        end

        % Close and exit dialog function

        cancelViewerSeriesDescriptionCallback(); 

    end % okViewerSeriesDescriptionCallback()  

end