function [sSeriesDescriptionReturnValue, bBypassDialogReturnValue] = getViewerSeriesDescriptionDialog(sSeriesDescription, bBypassDialog)
%function [sSeriesDescriptionReturnValue, bBypassDialogReturnValue] = getViewerSeriesDescriptionDialog(sSeriesDescription, bBypassDialog)
%Create a dialog and return a new label.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Note: option settings must fit on one line and can contain one semicolon at most.
%Options can be strings, cell arrays of strings, or numerical arrays.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2022, Daniel Lafontaine, on behalf of the TriDFusion development team.
% 
% This file is part of The Triple Dimention Fusion (TriDFusion).
% 
% TriDFusion development has been led by:  Daniel Lafontaine
% 
% TriDFusion is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    if exist('bBypassDialog', 'var')
        if bBypassDialog == false
            dDialogYSize = 145;
        else
            bBypassDialogReturnValue = bBypassDialog;             
            sSeriesDescriptionReturnValue = sSeriesDescription;
            return;
        end
    else
        dDialogYSize = 120;
    end

    dlgRtStructSeriesDescription = ...
        dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-380/2) ...
                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-120/2) ...
                        380 ...
                        dDialogYSize ...
                        ],...
           'MenuBar', 'none',...
           'Resize', 'off', ...    
           'NumberTitle','off',...
           'MenuBar', 'none',...
           'Color', viewerBackgroundColor('get'), ...
           'Name', 'Edit Label',...
           'Toolbar','none'...   
           );            
           
        axes(dlgRtStructSeriesDescription, ...
             'Units'   , 'pixels', ...
             'Position', get(dlgRtStructSeriesDescription, 'Position'), ...
             'Color'   , viewerBackgroundColor('get'),...
             'XColor'  , viewerForegroundColor('get'),...
             'YColor'  , viewerForegroundColor('get'),...
             'ZColor'  , viewerForegroundColor('get'),...             
             'Visible' , 'off'...             
             ); 
         
    if exist('bBypassDialog', 'var')
         
        chkBypassDialog = ...
            uicontrol(dlgRtStructSeriesDescription,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , 0,...
                      'position', [20 90 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                    
                      'Callback', @chkBypassDialogCallback...
                      );

             uicontrol(dlgRtStructSeriesDescription,...
                      'style'   , 'text',...
                      'string'  , 'Dont display again',...
                      'horizontalalignment', 'left',...
                      'position', [40 87 200 20],...
                      'Enable', 'Inactive',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                    
                      'ButtonDownFcn', @chkBypassDialogCallback...
                      );  
    end
    
     uicontrol(dlgRtStructSeriesDescription,...
              'style'   , 'text',...
              'enable'  , 'On',...
              'string'  , 'Series Description',...
              'horizontalalignment', 'left',...
              'BackgroundColor', viewerBackgroundColor('get'), ...
              'ForegroundColor', viewerForegroundColor('get'), ...                     
              'position', [20 62 140 20]...
              );


    edtRtStructSeriesDescription = ...
        uicontrol(dlgRtStructSeriesDescription,...
                 'enable'    , 'on',...
                 'style'     , 'edit',...
                 'Background', 'white',...
                 'string'    , sSeriesDescription,...
                 'BackgroundColor', viewerBackgroundColor('get'), ...
                 'ForegroundColor', viewerForegroundColor('get'), ...                    
                 'position'  , [160 65 200 20]...
                 );


    % Cancel or Proceed

    uicancelViewerSeriesDescription = ...
        uicontrol(dlgRtStructSeriesDescription,...
                   'String','Cancel',...
                   'Position',[285 7 75 25],...
                   'BackgroundColor', viewerBackgroundColor('get'), ...
                   'ForegroundColor', viewerForegroundColor('get'), ...                  
                   'Callback', @cancelViewerSeriesDescriptionCallback...
                   );

         uicontrol(dlgRtStructSeriesDescription,...
                  'String','Ok',...
                  'Position',[200 7 75 25],...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...                 
                  'Callback', @okViewerSeriesDescriptionCallback...
                  );  
              
    bBypassDialogReturnValue = false;             
    sSeriesDescriptionReturnValue = [];
    
    waitfor(uicancelViewerSeriesDescription); 
    
    function chkBypassDialogCallback(hObject, ~)
        
        if get(chkBypassDialog, 'Value') == 1
           if strcmpi(hObject.Style, 'checkbox')
                set(chkBypassDialog, 'Value', 1);
            else
                set(chkBypassDialog, 'Value', 0);
           end            
        else
           if strcmpi(hObject.Style, 'checkbox')
                set(chkBypassDialog, 'Value', 0);
            else
                set(chkBypassDialog, 'Value', 1);
           end  
        end         
    end
    
    function cancelViewerSeriesDescriptionCallback(~, ~)

        delete(dlgRtStructSeriesDescription);

    end % cancelViewerSeriesDescriptionCallback()

    function okViewerSeriesDescriptionCallback(~, ~)

        sSeriesDescriptionReturnValue = get(edtRtStructSeriesDescription, 'String');
        
        if exist('bBypassDialog', 'var')
            bBypassDialogReturnValue = get(chkBypassDialog, 'Value');
        end

        % Close and exit dialog function

        cancelViewerSeriesDescriptionCallback(); 

    end % okViewerSeriesDescriptionCallback()         
          
end