function resizeFigure(~, ~) 
%function resizeFigure(~, ~)
%Resize Main Figure.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2020, Daniel Lafontaine, on behalf of the TriDFusion development team.
% 
% This file is part of The Triple Dimention Fusion (TriDFusion).
% 
% TriDFusion development has been led by:  Daniel Lafontaine
% 
% TriDFusion is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>. 

   uiSegMainPanel = uiSegMainPanelPtr('get');
   if ~isempty(uiSegMainPanel)
        set(uiSegMainPanel, ...
            'position', [0 ...
                         addOnWidth('get')+30 ...
                         300 ...
                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                         ] ...
           );

        uiSegPanelSlider = uiSegPanelSliderPtr('get');
        if ~isempty(uiSegPanelSlider)

            aMainSegPanelPosition = get(uiSegMainPanel, 'position');
            set(uiSegPanelSlider, ...
                'position', [280 ...
                             0 ...
                             20 ...
                             aMainSegPanelPosition(4) ...
                             ]...
               );                
        end              
    end            

    uiKernelMainPanel = uiKernelMainPanelPtr('get');
    if ~isempty(uiKernelMainPanel)
        set(uiKernelMainPanel, ...
            'position', [0 ...
                         addOnWidth('get')+30 ...
                         300 ...
                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                         ] ...
           );

        uiKernelPanelSlider = uiKernelPanelSliderPtr('get');
        if ~isempty(uiKernelPanelSlider)
            aMainKernelPanelPosition = get(uiKernelMainPanel, 'position');
            set(uiKernelPanelSlider, ...
                'position', [280 ...
                             0 ...
                             20 ...
                             aMainKernelPanelPosition(4) ...
                             ]...
               );                
        end 
    end
    
    uiRoiMainPanel = uiRoiMainPanelPtr('get');
    if ~isempty(uiRoiMainPanel)
        set(uiRoiMainPanel, ...
            'position', [0 ...
                         addOnWidth('get')+30 ...
                         300 ...
                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                         ] ...
           );

        uiRoiPanelSlider = uiRoiPanelSliderPtr('get');
        if ~isempty(uiRoiPanelSlider)
            aMainRoiPanelPosition = get(uiRoiMainPanel, 'position');
            set(uiRoiPanelSlider, ...
                'position', [280 ...
                             0 ...
                             20 ...
                             aMainRoiPanelPosition(4) ...
                             ]...
               );                
        end 
    end
    
    uiCorWindow = uiCorWindowPtr('get');
    if ~isempty(uiCorWindow)
        if viewSegPanel('get')
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')
                set(uiCorWindow, ...
                    'position', [uiSegMainPanel.Position(3) ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiSegMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                   
            else
                if isVsplash('get') == true    
                    set(uiCorWindow, ...
                        'position', [uiSegMainPanel.Position(3) ...
                                     addOnWidth('get')+30+15 ...
                                     (getMainWindowSize('xsize')/4)-(uiSegMainPanel.Position(3)/2) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );                     
                else
                    set(uiCorWindow, ...
                        'position', [uiSegMainPanel.Position(3) ...
                                     addOnWidth('get')+30+15 ...
                                     (getMainWindowSize('xsize')/5)-(uiSegMainPanel.Position(3)/2) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );  
                end
            end
        elseif viewKernelPanel('get')
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')
                set(uiCorWindow, ...
                    'position', [uiKernelMainPanel.Position(3) ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                     
            else
                if isVsplash('get') == true    
                    set(uiCorWindow, ...
                        'position', [uiKernelMainPanel.Position(3) ...
                                     addOnWidth('get')+30+15 ...
                                     (getMainWindowSize('xsize')/4)-(uiKernelMainPanel.Position(3)/2) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );                      
                else
                    set(uiCorWindow, ...
                        'position', [uiKernelMainPanel.Position(3) ...
                                     addOnWidth('get')+30+15 ...
                                     (getMainWindowSize('xsize')/5)-(uiKernelMainPanel.Position(3)/2) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );  
                end
            end
        elseif viewRoiPanel('get')
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')
                set(uiCorWindow, ...
                    'position', [uiRoiMainPanel.Position(3) ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiRoiMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                     
            else
                if isVsplash('get') == true
                    set(uiCorWindow, ...
                        'position', [uiRoiMainPanel.Position(3) ...
                                     addOnWidth('get')+30+15 ...
                                     (getMainWindowSize('xsize')/4)-(uiRoiMainPanel.Position(3)/2) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );                      
                else
                    set(uiCorWindow, ...
                        'position', [uiRoiMainPanel.Position(3) ...
                                     addOnWidth('get')+30+15 ...
                                     (getMainWindowSize('xsize')/5)-(uiRoiMainPanel.Position(3)/2) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );  
                end
            end            
        else
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')    
                set(uiCorWindow, ...
                    'position', [0 ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize') ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                   
            else
                if isVsplash('get') == true
                    set(uiCorWindow, ...
                        'position', [0 ...
                                     addOnWidth('get')+30+15 ...
                                     getMainWindowSize('xsize')/4 ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );                    
                else               
                    set(uiCorWindow, ...
                        'position', [0 ...
                                     addOnWidth('get')+30+15 ...
                                     getMainWindowSize('xsize')/5 ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );
                end
            end
        end

        txt1 = axesText('get', 'axes1');
        if ~isempty(txt1)
            if isvalid(txt1.Parent)
                set(txt1.Parent, ...
                    'Position', [5 ...
                                 uiCorWindow.Position(4)-15 ...
                                 70 ...
                                 30 ...
                                 ]...
                    );         
            end
        end
    end   

    uiSagWindow = uiSagWindowPtr('get');
    if ~isempty(uiSagWindow)
        if viewSegPanel('get') 
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all') 
               set(uiSagWindow, ...
                    'position', [uiSegMainPanel.Position(3) ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiSegMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                     
            else    
               if isVsplash('get') == true
                   set(uiSagWindow, ...
                        'position', [(uiSegMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                     addOnWidth('get')+30+15 ...
                                     (getMainWindowSize('xsize')/4)-(uiSegMainPanel.Position(3)/2) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );                    
               else 
                   set(uiSagWindow, ...
                        'position', [(uiSegMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/5) ...
                                     addOnWidth('get')+30+15 ...
                                     (getMainWindowSize('xsize')/5)-(uiSegMainPanel.Position(3)/2) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );  
               end
            end
        elseif viewKernelPanel('get') 
           if isVsplash('get') == true && ...
              ~strcmpi(vSplahView('get'), 'all') 
               set(uiSagWindow, ...
                    'position', [uiKernelMainPanel.Position(3) ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                  
           else
               if isVsplash('get') == true
                   set(uiSagWindow, ...
                        'position', [(uiKernelMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                     addOnWidth('get')+30+15 ...
                                     (getMainWindowSize('xsize')/4)-(uiKernelMainPanel.Position(3)/2) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );                   
               else               
                   set(uiSagWindow, ...
                        'position', [(uiKernelMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/5) ...
                                     addOnWidth('get')+30+15 ...
                                     (getMainWindowSize('xsize')/5)-(uiKernelMainPanel.Position(3)/2) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );
               end
           end
        elseif viewRoiPanel('get') 
           if isVsplash('get') == true && ...
              ~strcmpi(vSplahView('get'), 'all') 
               set(uiSagWindow, ...
                    'position', [uiRoiMainPanel.Position(3) ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiRoiMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                  
           else
               if isVsplash('get') == true
                   set(uiSagWindow, ...
                        'position', [(uiRoiMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                     addOnWidth('get')+30+15 ...
                                     (getMainWindowSize('xsize')/4)-(uiRoiMainPanel.Position(3)/2) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );                   
               else
                   set(uiSagWindow, ...
                        'position', [(uiRoiMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/5) ...
                                     addOnWidth('get')+30+15 ...
                                     (getMainWindowSize('xsize')/5)-(uiRoiMainPanel.Position(3)/2) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );
               end
           end           
        else
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all') 
                set(uiSagWindow, ...
                    'position', [0 ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize') ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );
            else
                if isVsplash('get') == true
                    set(uiSagWindow, ...
                        'position', [getMainWindowSize('xsize')/4 ...
                                     addOnWidth('get')+30+15 ...
                                     getMainWindowSize('xsize')/4 ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );                    
                else                
                    set(uiSagWindow, ...
                        'position', [getMainWindowSize('xsize')/5 ...
                                     addOnWidth('get')+30+15 ...
                                     getMainWindowSize('xsize')/5 ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );
                end
           end
        end

        txt2 = axesText('get', 'axes2');
        if ~isempty(txt2)
            if isvalid(txt2.Parent)
                set(txt2.Parent, ...
                    'Position', [5 ...
                                 uiSagWindow.Position(4)-15 ...
                                 70 ...
                                 30]...
                    );  
            end
        end
    end  

    uiTraWindow = uiTraWindowPtr('get');
    if ~isempty(uiTraWindow)

        if isVsplash('get') == true && ...
           ~strcmpi(vSplahView('get'), 'all')                 
            if viewSegPanel('get') 
                set(uiTraWindow, ...
                    'position', [uiSegMainPanel.Position(3)  ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiSegMainPanel.Position(3)/2)...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );  
            elseif viewKernelPanel('get') 
                set(uiTraWindow, ...
                    'position', [uiKernelMainPanel.Position(3)  ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2)...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );     
            elseif viewRoiPanel('get') 
                set(uiTraWindow, ...
                    'position', [uiRoiMainPanel.Position(3)  ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiRoiMainPanel.Position(3)/2)...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                   
            else
                set(uiTraWindow, ...
                    'position', [0 ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize') ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                                        
            end  
         
        else
            if isVsplash('get') == true   
                set(uiTraWindow, ...
                    'position', [(getMainWindowSize('xsize')/2) ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')/2 ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                
            else
                set(uiTraWindow, ...
                    'position', [(getMainWindowSize('xsize')/2.5) ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')/2.5 ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );
            end
        end
        
        txt3 = axesText('get', 'axes3');
        if ~isempty(txt3)
            if isvalid(txt3.Parent)
                set(txt3.Parent, ...
                    'Position', [25 ...
                                 uiTraWindow.Position(4)-getTopWindowSize('ysize') ...
                                 100 ...
                                 200 ...
                                 ]...
                    );                                               
            end
        end
    end  
    
    uiMipWindow = uiMipWindowPtr('get');
    if ~isempty(uiTraWindow)

        set(uiMipWindow, ...
            'position', [(getMainWindowSize('xsize')/1.25) ...
                         addOnWidth('get')+30+15 ...
                         getMainWindowSize('xsize')/5 ...
                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                         ]...
           );
       
        txtMip = axesText('get', 'axesMip');
        if ~isempty(txtMip)
            if isvalid(txtMip.Parent)
                set(txtMip.Parent, ...
                    'Position', [5 ...
                                 uiMipWindow.Position(4)-5 ...
                                 70 ...
                                 30]...
                    );                   
            end
        end       
    end  
    
    uiSliderCor = uiSliderCorPtr('get');
    if ~isempty(uiSliderCor)                               
        if viewSegPanel('get') 
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')     
                set(uiSliderCor, ...
                    'position', [uiSegMainPanel.Position(3)...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-(uiSegMainPanel.Position(3)/2) ...
                                 15 ...
                                 ] ...
                   );                   
            else
                if isVsplash('get') == true   
                    set(uiSliderCor, ...
                        'position', [uiSegMainPanel.Position(3)...
                                     addOnWidth('get')+30 ...
                                     (getMainWindowSize('xsize')/4)-(uiSegMainPanel.Position(3)/2) ...
                                     15 ...
                                     ] ...
                       );                    
                else
                    set(uiSliderCor, ...
                        'position', [uiSegMainPanel.Position(3)...
                                     addOnWidth('get')+30 ...
                                     (getMainWindowSize('xsize')/5)-(uiSegMainPanel.Position(3)/2) ...
                                     15 ...
                                     ] ...
                       );
                end
            end
       elseif viewKernelPanel('get') 
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')     
                set(uiSliderCor, ...
                    'position', [uiKernelMainPanel.Position(3)...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                 15 ...
                                 ] ...
                   );                   
            else       
                if isVsplash('get') == true 
                    set(uiSliderCor, ...
                        'position', [uiKernelMainPanel.Position(3)...
                                     addOnWidth('get')+30 ...
                                     (getMainWindowSize('xsize')/4)-(uiKernelMainPanel.Position(3)/2) ...
                                     15 ...
                                     ] ...
                       );                       
                else
                    set(uiSliderCor, ...
                        'position', [uiKernelMainPanel.Position(3)...
                                     addOnWidth('get')+30 ...
                                     (getMainWindowSize('xsize')/5)-(uiKernelMainPanel.Position(3)/2) ...
                                     15 ...
                                     ] ...
                       );    
                end
            end
       elseif viewRoiPanel('get') 
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')     
                set(uiSliderCor, ...
                    'position', [uiRoiMainPanel.Position(3)...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-(uiRoiMainPanel.Position(3)/2) ...
                                 15 ...
                                 ] ...
                   );                   
            else    
                if isVsplash('get') == true 
                    set(uiSliderCor, ...
                        'position', [uiRoiMainPanel.Position(3)...
                                     addOnWidth('get')+30 ...
                                     (getMainWindowSize('xsize')/4)-(uiRoiMainPanel.Position(3)/2) ...
                                     15 ...
                                     ] ...
                       );                     
                else
                    set(uiSliderCor, ...
                        'position', [uiRoiMainPanel.Position(3)...
                                     addOnWidth('get')+30 ...
                                     (getMainWindowSize('xsize')/5)-(uiRoiMainPanel.Position(3)/2) ...
                                     15 ...
                                     ] ...
                       );    
                end
            end            
        else
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')   
                set(uiSliderCor, ...
                    'Position', [0 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize') ...
                                 15 ...
                                 ]...
                   );                    
            else
                if isVsplash('get') == true 
                    set(uiSliderCor, ...
                        'Position', [0 ...
                                     addOnWidth('get')+30 ...
                                     getMainWindowSize('xsize')/4 ...
                                     15 ...
                                     ]...
                       );                     
                else               
                    set(uiSliderCor, ...
                        'Position', [0 ...
                                     addOnWidth('get')+30 ...
                                     getMainWindowSize('xsize')/5 ...
                                     15 ...
                                     ]...
                       );                                            
                end
            end
        end
    end    

    uiSliderSag = uiSliderSagPtr('get');
    if ~isempty(uiSliderSag)                 
        if viewSegPanel('get') 
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')  
                set(uiSliderSag, ...
                    'position', [uiSegMainPanel.Position(3) ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-(uiSegMainPanel.Position(3)/2) ...
                                 15 ...
                                 ] ...
                    );                    
            else
                if isVsplash('get') == true 
                    set(uiSliderSag, ...
                        'position', [(uiSegMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                     addOnWidth('get')+30 ...
                                     (getMainWindowSize('xsize')/4)-(uiSegMainPanel.Position(3)/2) ...
                                     15 ...
                                     ] ...
                        );                     
                else
                    set(uiSliderSag, ...
                        'position', [(uiSegMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/5) ...
                                     addOnWidth('get')+30 ...
                                     (getMainWindowSize('xsize')/5)-(uiSegMainPanel.Position(3)/2) ...
                                     15 ...
                                     ] ...
                        ); 
                end
            end
        elseif viewKernelPanel('get') 
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')  
               set(uiSliderSag, ...
                   'position', [uiKernelMainPanel.Position(3) ...
                                addOnWidth('get')+30 ...
                                getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                15 ...
                                ] ...
                   );                     
            else
               if isVsplash('get') == true
                   set(uiSliderSag, ...
                       'position', [(uiKernelMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                    addOnWidth('get')+30 ...
                                    (getMainWindowSize('xsize')/4)-(uiKernelMainPanel.Position(3)/2) ...
                                    15 ...
                                    ] ...
                       );                     
               else 
                   set(uiSliderSag, ...
                       'position', [(uiKernelMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/5) ...
                                    addOnWidth('get')+30 ...
                                    (getMainWindowSize('xsize')/5)-(uiKernelMainPanel.Position(3)/2) ...
                                    15 ...
                                    ] ...
                       );  
               end
            end
        elseif viewRoiPanel('get') 
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')  
               set(uiSliderSag, ...
                   'position', [uiRoiMainPanel.Position(3) ...
                                addOnWidth('get')+30 ...
                                getMainWindowSize('xsize')-(uiRoiMainPanel.Position(3)/2) ...
                                15 ...
                                ] ...
                   );                     
            else
               if isVsplash('get') == true
                   set(uiSliderSag, ...
                       'position', [(uiRoiMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                    addOnWidth('get')+30 ...
                                    (getMainWindowSize('xsize')/4)-(uiRoiMainPanel.Position(3)/2) ...
                                    15 ...
                                    ] ...
                       );                    
               else                
                   set(uiSliderSag, ...
                       'position', [(uiRoiMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/5) ...
                                    addOnWidth('get')+30 ...
                                    (getMainWindowSize('xsize')/5)-(uiRoiMainPanel.Position(3)/2) ...
                                    15 ...
                                    ] ...
                       );  
               end
            end            
        else
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')  
                set(uiSliderSag, ...
                    'Position', [0 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize') ...
                                 15 ...
                                 ]...
                   );                      
            else
                if isVsplash('get') == true
                    set(uiSliderSag, ...
                        'Position', [(getMainWindowSize('xsize')/4) ...
                                      addOnWidth('get')+30 ...
                                      getMainWindowSize('xsize')/4 ...
                                      15 ...
                                      ]...
                        );                     
                else 
                    set(uiSliderSag, ...
                        'Position', [(getMainWindowSize('xsize')/5) ...
                                      addOnWidth('get')+30 ...
                                      getMainWindowSize('xsize')/5 ...
                                      15 ...
                                      ]...
                        );               
                end
            end
        end         
    end

    uiSliderTra = uiSliderTraPtr('get');
    if ~isempty(uiSliderTra)   
        if isVsplash('get') == true && ...
           ~strcmpi(vSplahView('get'), 'all')  
            if viewSegPanel('get') 
                set(uiSliderTra, ...
                    'Position', [uiSegMainPanel.Position(3) ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-(uiSegMainPanel.Position(3)/2) ...
                                 15 ...
                                 ]...
                    );                           
            elseif viewKernelPanel('get') 
                set(uiSliderTra, ...
                    'Position', [uiKernelMainPanel.Position(3) ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                 15 ...
                                 ]...
                    );  
            elseif viewRoiPanel('get') 
                set(uiSliderTra, ...
                    'Position', [uiRoiMainPanel.Position(3) ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-(uiRoiMainPanel.Position(3)/2) ...
                                 15 ...
                                 ]...
                    );                  
            else
                set(uiSliderTra, ...
                    'Position', [0 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize') ...
                                 15 ...
                                 ]...
                    );                          
            end

        else
            if isVsplash('get') == true
                set(uiSliderTra, ...
                    'Position', [(getMainWindowSize('xsize')/2) ...
                                  addOnWidth('get')+30 ...
                                  getMainWindowSize('xsize')/2 ...
                                  15 ...
                                  ]...
                    );                 
            else
                set(uiSliderTra, ...
                    'Position', [(getMainWindowSize('xsize')/2.5) ...
                                  addOnWidth('get')+30 ...
                                  getMainWindowSize('xsize')/2.5 ...
                                  15 ...
                                  ]...
                    );     
            end
        end
    end
    
    uiSliderMip = uiSliderMipPtr('get');
    if ~isempty(uiSliderMip)  
        set(uiSliderMip, ...
            'Position', [(getMainWindowSize('xsize')/1.25) ...
                          addOnWidth('get')+30 ...
                          getMainWindowSize('xsize')/5 ...
                          15 ...
                          ]...
            );          
    end
        
    uiTopWindow = uiTopWindowPtr('get');
    if ~isempty(uiTopWindow)

        set(uiTopWindow, ...
            'position', [0 ...
                        getMainWindowSize('ysize')-getTopWindowSize('ysize') ...
                        getMainWindowSize('xsize') ...
                        getTopWindowSize('ysize') ...
                        ]...
            );
    end  

    uiOneWindow = uiOneWindowPtr('get');
    if ~isempty(uiOneWindow)
        if switchTo3DMode('get')     == true || ...
           switchToIsoSurface('get') == true || ...
           switchToMIPMode('get')    == true

            ui3DGateWindow = ui3DGateWindowObject('get');

            if view3DPanel('get') == false
                set(uiOneWindow, ...
                    'position', [0 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize') ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                 ]...
                   );    

                if ~isempty(ui3DGateWindow)
                    for ww=1:numel(ui3DGateWindow)
                        set(ui3DGateWindow{ww}, ...
                            'position', [0 ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize') ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                         ]...
                           );  
                    end
               end
            else
                set(uiOneWindow, ...
                    'position', [680 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-680 ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                 ]...
                   );   

                if ~isempty(ui3DGateWindow)
                    for ww=1:numel(ui3DGateWindow)
                        set(ui3DGateWindow{ww}, ...
                            'position', [680 ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize')-680 ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                         ]...
                           );                                  
                    end
                end
            end
        else
            if viewSegPanel('get') == true 
                set(uiOneWindow, ...
                    'position', [uiSegMainPanel.Position(3) ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-uiSegMainPanel.Position(3) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                 ]...
                   );     
            elseif viewKernelPanel('get') == true 
                set(uiOneWindow, ...
                    'position', [uiKernelMainPanel.Position(3) ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-uiKernelMainPanel.Position(3) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                 ]...
                   );     
            elseif viewRoiPanel('get') == true 
                set(uiOneWindow, ...
                    'position', [uiRoiMainPanel.Position(3) ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-uiRoiMainPanel.Position(3) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                 ]...
                   );                 
            else                    
                set(uiOneWindow, ...
                    'position', [0 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize') ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                 ]...
                   );
            end

            txt = axesText('get', 'axe');
            if ~isempty(txt)
                if isvalid(txt.Parent)
                    set(txt.Parent, ...
                        'Position', [5 ...
                                     uiOneWindow.Position(4)-getTopWindowSize('ysize') ...
                                     100 ...
                                     200 ...
                                     ]...
                        );                                               
                end
            end
        end
    end  

    uiMain3DPanel = uiMain3DPanelPtr('get');
    if ~isempty(uiMain3DPanel)
        if switchTo3DMode('get')     == true || ...
           switchToIsoSurface('get') == true || ...
           switchToMIPMode('get')    == true            
            set(uiMain3DPanel, ...
                'position', [0 ...
                             addOnWidth('get')+30 ...
                             680 ...
                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                             ]...
               );                
        end

        ui3DPanelSlider = ui3DPanelSliderPtr('get');
        if ~isempty(ui3DPanelSlider)
            if switchTo3DMode('get')     == true || ...
               switchToIsoSurface('get') == true || ...
               switchToMIPMode('get')    == true     
                aMain3DPanelPosition = get(uiMain3DPanel, 'position');
                set(ui3DPanelSlider, ...
                    'position', [660 ...
                                 0 ...
                                 20 ...
                                 aMain3DPanelPosition(4) ...
                                 ]...
                   );                
            end
        end            
    end            
 
    uiProgressWindow = uiProgressWindowPtr('get');
    if ~isempty(uiProgressWindow)
        set(uiProgressWindow, ...
            'position', [0 ...
                         0 ...
                         getMainWindowSize('xsize') ...
                         30 ...
                         ]...
           );
    end 

    if isFusion('get') == true

        uiAlphaSlider = uiAlphaSliderPtr('get');
        if ~isempty(uiAlphaSlider) 

            aFigurePosition = uiAlphaSlider.Parent.Position;                                                                 
            if size(dicomBuffer('get'), 3) == 1
                if viewSegPanel('get') == true 
                    set(uiAlphaSlider, ...
                        'Position', [uiSegMainPanel.Position(3)+10 ...
                                     35 ...
                                     aFigurePosition(3)-uiSegMainPanel.Position(3)-20 ...
                                     15 ...
                                     ] ...
                        );                    
                elseif viewKernelPanel('get') == true 
                    set(uiAlphaSlider, ...
                        'Position', [uiKernelMainPanel.Position(3)+10 ...
                                     35 ...
                                     aFigurePosition(3)-uiKernelMainPanel.Position(3)-20 ...
                                     15 ...
                                     ] ...
                        );      
                elseif viewRoiPanel('get') == true 
                    set(uiAlphaSlider, ...
                        'Position', [uiRoiMainPanel.Position(3)+10 ...
                                     35 ...
                                     aFigurePosition(3)-uiRoiMainPanel.Position(3)-20 ...
                                     15 ...
                                     ] ...
                        );                     
                else
                    set(uiAlphaSlider, ...
                        'Position', [10 ...
                                     35 ...
                                     aFigurePosition(3)-20 ...
                                     15 ...
                                     ] ...
                        );
                end
            else
                if isVsplash('get') == true && ...
                   ~strcmpi(vSplahView('get'), 'all')
                    if viewSegPanel('get') == true 
                        
                        set(uiAlphaSlider, ...
                            'Position', [uiSegMainPanel.Position(3)+10 ...
                                         addOnWidth('get')+50 ...
                                         aFigurePosition(3)-uiSegMainPanel.Position(3)-20 ...
                                         15 ...
                                         ] ...
                            );
                    elseif viewKernelPanel('get') == true 
                        
                        set(uiAlphaSlider, ...
                            'Position', [uiKernelMainPanel.Position(3)+10 ...
                                         addOnWidth('get')+50 ...
                                         aFigurePosition(3)-uiKernelMainPanel.Position(3)-20 ...
                                         15 ...
                                         ] ...
                            );
                    elseif viewRoiPanel('get') == true 
                        
                        set(uiAlphaSlider, ...
                            'Position', [uiRoiMainPanel.Position(3)+10 ...
                                         addOnWidth('get')+50 ...
                                         aFigurePosition(3)-uiRoiMainPanel.Position(3)-20 ...
                                         15 ...
                                         ] ...
                            );                        
                    else
                        set(uiAlphaSlider, ...
                            'Position', [10 ...
                                         addOnWidth('get')+50 ...
                                         aFigurePosition(3)-20 ...
                                         15 ...
                                         ] ...
                            );
                    end
                else     
                    if isVsplash('get') == true
                         set(uiAlphaSlider, ...
                            'Position', [aFigurePosition(3)/2+10 ...
                                         addOnWidth('get')+50 ...
                                         aFigurePosition(3)/2-20 ...
                                         15 ...
                                         ] ...
                            );                       
                    else
                        set(uiAlphaSlider, ...
                            'Position', [aFigurePosition(3)/2.5+10 ...
                                         addOnWidth('get')+50 ...
                                         aFigurePosition(3)/2.5-20 ...
                                         15 ...
                                         ] ...
                            );
                    end
                end
            end
        end

        ptrFusionColorbar = uiFusionColorbarPtr('get');
        if ~isempty(ptrFusionColorbar) 

            aAxePosition = ptrFusionColorbar.Parent.Position;
            if size(dicomBuffer('get'), 3) == 1
                set(ptrFusionColorbar, ...
                    'Position', [aAxePosition(3)-49 ...
                                 27 ...
                                 40 ...
                                 ((aAxePosition(4))/2)-41  ...
                                 ] ...
                   );
            else
                if isVsplash('get') == true && ...
                  ~strcmpi(vSplahView('get'), 'all')
                    if viewSegPanel('get') 
                        
                        set(ptrFusionColorbar, ...
                            'Position', [aAxePosition(3)-(uiSegMainPanel.Position(3)/2)-49 ...
                                         29 ...
                                         40 ...
                                         ((aAxePosition(4))/2)-35  ...
                                         ] ...
                           );
                    elseif viewKernelPanel('get') == true 
                        
                        set(ptrFusionColorbar, ...
                            'Position', [aAxePosition(3)-(uiKernelMainPanel.Position(3)/2)-49 ...
                                         29 ...
                                         40 ...
                                         ((aAxePosition(4))/2)-35  ...
                                         ] ...
                           );
                    elseif viewRoiPanel('get') == true 
                        
                        set(ptrFusionColorbar, ...
                            'Position', [aAxePosition(3)-(uiRoiMainPanel.Position(3)/2)-49 ...
                                         29 ...
                                         40 ...
                                         ((aAxePosition(4))/2)-35  ...
                                         ] ...
                           );                       
                    else
                        set(ptrFusionColorbar, ...
                            'Position', [aAxePosition(3)-49 ...
                                         29 ...
                                         40 ...
                                         ((aAxePosition(4))/2)-35  ...
                                         ] ...
                           );
                    end
                else
                    set(ptrFusionColorbar, ...
                        'Position', [aAxePosition(3)-49 ...
                                     29 ...
                                     40 ...
                                     ((aAxePosition(4))/2)-35  ...
                                     ] ...
                        );
                end
            end                   
        end

        uiFusionSliderWindow = uiFusionSliderWindowPtr('get');
        if ~isempty(uiFusionSliderWindow) 

            aFigurePosition = uiFusionSliderWindow.Parent.Position;                                                                 
            if size(dicomBuffer('get'), 3) == 1
                set(uiFusionSliderWindow, ...
                    'Position', [aFigurePosition(3)-50 ...
                                 55 ...
                                 12 ...
                                 (aFigurePosition(4)/2)-75  ...
                                 ] ...
                    );
            else
                if isVsplash('get') == true
                    set(uiFusionSliderWindow, ...
                        'Position', [aFigurePosition(3)-50 ...
                                     70 ...
                                     12 ...
                                     (aFigurePosition(4)/2)-75  ...
                                     ] ...
                        );                    
                else
                    aAxePosition = uiTraWindow.Position;                                 
                    set(uiFusionSliderWindow, ...
                        'Position', [aAxePosition(1)+aAxePosition(3)-50 ...
                                     70 ...
                                     12 ...
                                     (aFigurePosition(4)/2)-75  ...
                                     ] ...
                        );
                end
            end   
        end

        uiFusionSliderLevel = uiFusionSliderLevelPtr('get');
        if ~isempty(uiFusionSliderLevel) 
            aFigurePosition = uiFusionSliderLevel.Parent.Position;                                                                 
            if size(dicomBuffer('get'), 3) == 1
                set(uiFusionSliderLevel, ...
                    'Position', [aFigurePosition(3)-21 ...
                                 55 ...
                                 12 ...
                                 (aFigurePosition(4)/2)-75  ...
                                 ] ...
                    );
            else
                if isVsplash('get') == true
                    set(uiFusionSliderLevel, ...
                        'Position', [aFigurePosition(3)-21 ...
                                     70 ...
                                     12 ...
                                     (aFigurePosition(4)/2)-75  ...
                                     ] ...
                        );                    
                else                
                    aAxePosition = uiTraWindow.Position;                                                 
                    set(uiFusionSliderLevel, ...
                        'Position', [aAxePosition(1)+aAxePosition(3)-21 ...
                                     70 ...
                                     12 ...
                                     (aFigurePosition(4)/2)-75  ...
                                     ] ...
                        );
                end
            end
        end

        uiSliderWindow = uiSliderWindowPtr('get');
        if ~isempty(uiSliderWindow)
            aFigurePosition = uiSliderWindow.Parent.Position;                                                                
            if size(dicomBuffer('get'), 3) == 1
                set(uiSliderWindow, ...
                    'Position', [aFigurePosition(3)-50 ...
                                 (aFigurePosition(4)/2)-15 ...
                                 12 ...
                                 (aFigurePosition(4)/2)-30  ...
                                 ] ...
                    );                    
            else
                if isVsplash('get') == true
                    set(uiSliderWindow, ...
                        'Position', [aFigurePosition(3)-50 ...
                                     aFigurePosition(4)/2 ...
                                     12 ...
                                     (aFigurePosition(4)/2)-45  ...
                                     ] ...
                        );                      
                else                
                    aAxePosition = uiTraWindow.Position;                                                 
                    set(uiSliderWindow, ...
                        'Position', [aAxePosition(1)+aAxePosition(3)-50 ...
                                     aFigurePosition(4)/2 ...
                                     12 ...
                                     (aFigurePosition(4)/2)-45  ...
                                     ] ...
                        );                   
                end
            end     
        end 

        uiSliderLevel = uiSliderLevelPtr('get');
        if ~isempty(uiSliderLevel)

            aFigurePosition = uiSliderLevel.Parent.Position;                                                                
            if size(dicomBuffer('get'), 3) == 1
                set(uiSliderLevel, ...
                    'Position', [aFigurePosition(3)-21 ...
                                 (aFigurePosition(4)/2)-15 ...
                                 12 ...
                                 (aFigurePosition(4)/2)-30  ...
                                 ] ...
                    );
            else
                if isVsplash('get') == true
                    set(uiSliderLevel, ...
                        'Position', [aFigurePosition(3)-21 ...
                                     aFigurePosition(4)/2 ...
                                     12 ...
                                     (aFigurePosition(4)/2)-45  ...
                                     ] ...
                        );                    
                else                
                    aAxePosition = uiTraWindow.Position;                                                 
                    set(uiSliderLevel, ...
                        'Position', [aAxePosition(1)+aAxePosition(3)-21 ...
                                     aFigurePosition(4)/2 ...
                                     12 ...
                                     (aFigurePosition(4)/2)-45  ...
                                     ] ...
                        );
                end
            end     
        end

        ptrColorbar = uiColorbarPtr('get');
        if ~isempty(ptrColorbar)  

            aAxePosition = ptrColorbar.Parent.Position;
            if size(dicomBuffer('get'), 3) == 1
                set(ptrColorbar, ...
                    'Position', [aAxePosition(3)-49 ...
                                 (aAxePosition(4)/2)-9 ...
                                 40 ...
                                 (aAxePosition(4)/2)+5  ...
                                 ] ...
                    );                  
            else  
                if isVsplash('get') == true && ...
                  ~strcmpi(vSplahView('get'), 'all')
                    if viewSegPanel('get')
                        
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-(uiSegMainPanel.Position(3)/2)-49 ...
                                         (aAxePosition(4)/2) ...
                                         40 ...
                                         (aAxePosition(4)/2)-4  ...
                                         ] ...
                           );
                    elseif viewKernelPanel('get') == true 
                        
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-(uiKernelMainPanel.Position(3)/2)-49 ...
                                         (aAxePosition(4)/2) ...
                                         40 ...
                                         (aAxePosition(4)/2)-4  ...
                                         ] ...
                           );
                    elseif viewRoiPanel('get') == true 
                        
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-(uiRoiMainPanel.Position(3)/2)-49 ...
                                         (aAxePosition(4)/2) ...
                                         40 ...
                                         (aAxePosition(4)/2)-4  ...
                                         ] ...
                           );                       
                    else
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-49 ...
                                         (aAxePosition(4)/2) ...
                                         40 ...
                                         (aAxePosition(4)/2)-4  ...
                                         ] ...
                           );
                    end
                else                        
                    set(ptrColorbar, ...
                        'Position', [aAxePosition(3)-49 ...
                                     (aAxePosition(4)/2) ...
                                     40 ...
                                     (aAxePosition(4)/2)-4  ...
                                     ] ...
                        );
                end
            end
        end  
    else
        uiSliderWindow = uiSliderWindowPtr('get');
        if ~isempty(uiSliderWindow)
            aFigurePosition = uiSliderWindow.Parent.Position;                                                                
            if size(dicomBuffer('get'), 3) == 1
                set(uiSliderWindow, ...
                    'Position', [aFigurePosition(3)-50 ...
                                 35 ...
                                 12 ...
                                 aFigurePosition(4)-80  ...
                                 ] ...
                    );                    
            else
                if isVsplash('get') == true
                    set(uiSliderWindow, ...
                        'Position', [aFigurePosition(3)-50 ...
                                     50 ...
                                     12 ...
                                     aFigurePosition(4)-95  ...
                                     ] ...
                        );                     
                else                
                    aAxePosition = uiTraWindow.Position;                                 
                    set(uiSliderWindow, ...
                        'Position', [aAxePosition(1)+aAxePosition(3)-50 ...
                                     50 ...
                                     12 ...
                                     aFigurePosition(4)-95  ...
                                     ] ...
                        );                   
                end
            end     
        end

        uiSliderLevel = uiSliderLevelPtr('get');
        if ~isempty(uiSliderLevel)

            aFigurePosition = uiSliderLevel.Parent.Position;                                                                
            if size(dicomBuffer('get'), 3) == 1
                set(uiSliderLevel, ...
                    'Position', [aFigurePosition(3)-21 ...
                                 35 ...
                                 12 ...
                                 aFigurePosition(4)-80  ...
                                 ] ...
                    );
            else
                if isVsplash('get') == true
                  set(uiSliderLevel, ...
                        'Position', [aFigurePosition(3)-21 ...
                                     50 ...
                                     12 ...
                                     aFigurePosition(4)-95  ...
                                     ] ...
                       );                    
                else                
                    aAxePosition = uiTraWindow.Position;                 
                    set(uiSliderLevel, ...
                        'Position', [aAxePosition(1)+aAxePosition(3)-21 ...
                                     50 ...
                                     12 ...
                                     aFigurePosition(4)-95  ...
                                     ] ...
                       );
                end
            end     
        end

        ptrColorbar = uiColorbarPtr('get');
        if ~isempty(ptrColorbar)  

            aAxePosition = ptrColorbar.Parent.Position;
            if size(dicomBuffer('get'), 3) == 1
                set(ptrColorbar, ...
                    'Position', [aAxePosition(3)-49 ...
                                 7 ...
                                 40 ...
                                 aAxePosition(4)-11  ...
                                 ] ...
                    );                    
            else  
                if isVsplash('get') == true && ...
                  ~strcmpi(vSplahView('get'), 'all')
                    if viewSegPanel('get') 
                        
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-(uiSegMainPanel.Position(3)/2)-49 ...
                                         7 ...
                                         40 ...
                                         aAxePosition(4)-11  ...
                                         ] ...
                            );
                    elseif viewKernelPanel('get') == true 
                        
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-(uiKernelMainPanel.Position(3)/2)-49 ...
                                         7 ...
                                         40 ...
                                         aAxePosition(4)-11  ...
                                         ] ...
                            );
                    elseif viewRoiPanel('get') == true 
                        
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-(uiRoiMainPanel.Position(3)/2)-49 ...
                                         7 ...
                                         40 ...
                                         aAxePosition(4)-11  ...
                                         ] ...
                            );                        
                    else
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-49 ...
                                         7 ...
                                         40 ... 
                                         aAxePosition(4)-11  ...
                                         ] ...
                            );
                    end
                else                             
                    set(ptrColorbar, ...
                        'Position', [aAxePosition(3)-49 ...
                                     7 ...
                                     40 ...
                                     aAxePosition(4)-11  ...
                                     ] ...
                        );
                end
            end
        end                 
    end

end 
