function resizeFigure(~, ~) 
%function resizeFigure(~, ~)
%Resize Main Figure.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2020, Daniel Lafontaine, on behalf of the TriDFusion development team.
% 
% This file is part of The Triple Dimention Fusion (TriDFusion).
% 
% TriDFusion development has been led by:  Daniel Lafontaine
% 
% TriDFusion is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>. 

   uiSegMainPanel = uiSegMainPanelPtr('get');
   if ~isempty(uiSegMainPanel)
        set(uiSegMainPanel, ...
            'position', [0 ...
                         addOnWidth('get')+30 ...
                         300 ...
                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                         ] ...
           );

        uiSegPanelSlider = uiSegPanelSliderPtr('get');
        if ~isempty(uiSegPanelSlider)

            aMainSegPanelPosition = get(uiSegMainPanel, 'position');
            set(uiSegPanelSlider, ...
                'position', [280 ...
                             0 ...
                             20 ...
                             aMainSegPanelPosition(4) ...
                             ]...
               );                
        end              
    end            

    uiKernelMainPanel = uiKernelMainPanelPtr('get');
    if ~isempty(uiKernelMainPanel)
        set(uiKernelMainPanel, ...
            'position', [0 ...
                         addOnWidth('get')+30 ...
                         300 ...
                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                         ] ...
           );

        uiKernelPanelSlider = uiKernelPanelSliderPtr('get');
        if ~isempty(uiKernelPanelSlider)
            aMainKernelPanelPosition = get(uiKernelMainPanel, 'position');
            set(uiKernelPanelSlider, ...
                'position', [280 ...
                             0 ...
                             20 ...
                             aMainKernelPanelPosition(4) ...
                             ]...
               );                
        end 
    end

    uiCorWindow = uiCorWindowPtr('get');
    if ~isempty(uiCorWindow)
        if viewSegPanel('get')
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')
                set(uiCorWindow, ...
                    'position', [uiSegMainPanel.Position(3) ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiSegMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                   
            else
                set(uiCorWindow, ...
                    'position', [uiSegMainPanel.Position(3) ...
                                 addOnWidth('get')+30+15 ...
                                 (getMainWindowSize('xsize')/4)-(uiSegMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );  
            end
        elseif viewKernelPanel('get')
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')
                set(uiCorWindow, ...
                    'position', [uiKernelMainPanel.Position(3) ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                     
            else
                set(uiCorWindow, ...
                    'position', [uiKernelMainPanel.Position(3) ...
                                 addOnWidth('get')+30+15 ...
                                 (getMainWindowSize('xsize')/4)-(uiKernelMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );  
            end
        else
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')    
                set(uiCorWindow, ...
                    'position', [0 ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize') ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                   
            else
                set(uiCorWindow, ...
                    'position', [0 ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')/4 ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );
            end
        end

        txt1 = axesText('get', 'axes1');
        if ~isempty(txt1)
            set(txt1.Parent, ...
                'Position', [5 ...
                             uiCorWindow.Position(4)-15 ...
                             70 ...
                             30 ...
                             ]...
                );                                               
        end
    end   

    uiSagWindow = uiSagWindowPtr('get');
    if ~isempty(uiSagWindow)
        if viewSegPanel('get') 
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all') 
               set(uiSagWindow, ...
                    'position', [uiSegMainPanel.Position(3) ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiSegMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                     
            else                        
               set(uiSagWindow, ...
                    'position', [(uiSegMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                 addOnWidth('get')+30+15 ...
                                 (getMainWindowSize('xsize')/4)-(uiSegMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );  
            end
        elseif viewKernelPanel('get') 
           if isVsplash('get') == true && ...
              ~strcmpi(vSplahView('get'), 'all') 
               set(uiSagWindow, ...
                    'position', [uiKernelMainPanel.Position(3) ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                  
           else
               set(uiSagWindow, ...
                    'position', [(uiKernelMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                 addOnWidth('get')+30+15 ...
                                 (getMainWindowSize('xsize')/4)-(uiKernelMainPanel.Position(3)/2) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );
           end
        else
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all') 
                set(uiSagWindow, ...
                    'position', [0 ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize') ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );
            else
                set(uiSagWindow, ...
                    'position', [getMainWindowSize('xsize')/4 ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')/4 ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );
           end
        end

        txt2 = axesText('get', 'axes2');
        if ~isempty(txt2)
            set(txt2.Parent, ...
                'Position', [5 ...
                             uiSagWindow.Position(4)-15 ...
                             70 ...
                             30]...
                );                                               
        end
    end  

    uiTraWindow = uiTraWindowPtr('get');
    if ~isempty(uiTraWindow)

        if isVsplash('get') == true && ...
           ~strcmpi(vSplahView('get'), 'all')                 
            if viewSegPanel('get') 
                set(uiTraWindow, ...
                    'position', [uiSegMainPanel.Position(3)  ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiSegMainPanel.Position(3)/2)...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );  
            elseif viewKernelPanel('get') 
                set(uiTraWindow, ...
                    'position', [uiKernelMainPanel.Position(3)  ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2)...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );     
            else
                set(uiTraWindow, ...
                    'position', [0 ...
                                 addOnWidth('get')+30+15 ...
                                 getMainWindowSize('xsize') ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                 ]...
                   );                        
            end
        else
            set(uiTraWindow, ...
                'position', [(getMainWindowSize('xsize')/2) ...
                             addOnWidth('get')+30+15 ...
                             getMainWindowSize('xsize')/2 ...
                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                             ]...
               );
        end
        txt3 = axesText('get', 'axes3');
        if ~isempty(txt3)
            set(txt3.Parent, ...
                'Position', [25 ...
                             uiTraWindow.Position(4)-getTopWindowSize('ysize') ...
                             100 ...
                             200 ...
                             ]...
                );                                               
        end
    end  

    uiSliderCor = uiSliderCorPtr('get');
    if ~isempty(uiSliderCor)                               
        if viewSegPanel('get') 
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')     
                set(uiSliderCor, ...
                    'position', [uiSegMainPanel.Position(3)...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-(uiSegMainPanel.Position(3)/2) ...
                                 15 ...
                                 ] ...
                   );                   
            else
                set(uiSliderCor, ...
                    'position', [uiSegMainPanel.Position(3)...
                                 addOnWidth('get')+30 ...
                                 (getMainWindowSize('xsize')/4)-(uiSegMainPanel.Position(3)/2) ...
                                 15 ...
                                 ] ...
                   );
            end
       elseif viewKernelPanel('get') 
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')     
                set(uiSliderCor, ...
                    'position', [uiKernelMainPanel.Position(3)...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                 15 ...
                                 ] ...
                   );                   
            else                   
                set(uiSliderCor, ...
                    'position', [uiKernelMainPanel.Position(3)...
                                 addOnWidth('get')+30 ...
                                 (getMainWindowSize('xsize')/4)-(uiKernelMainPanel.Position(3)/2) ...
                                 15 ...
                                 ] ...
                   );    
            end
        else
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')   
                set(uiSliderCor, ...
                    'Position', [0 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize') ...
                                 15 ...
                                 ]...
                   );                    
            else
                set(uiSliderCor, ...
                    'Position', [0 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')/4 ...
                                 15 ...
                                 ]...
                   );                                            
            end
        end
    end    

    uiSliderSag = uiSliderSagPtr('get');
    if ~isempty(uiSliderSag)                 
        if viewSegPanel('get') 
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')  
                set(uiSliderSag, ...
                    'position', [uiSegMainPanel.Position(3) ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-(uiSegMainPanel.Position(3)/2) ...
                                 15 ...
                                 ] ...
                    );                    
            else
                set(uiSliderSag, ...
                    'position', [(uiSegMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                 addOnWidth('get')+30 ...
                                 (getMainWindowSize('xsize')/4)-(uiSegMainPanel.Position(3)/2) ...
                                 15 ...
                                 ] ...
                    ); 
            end
        elseif viewKernelPanel('get') 
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')  
               set(uiSliderSag, ...
                   'position', [uiKernelMainPanel.Position(3) ...
                                addOnWidth('get')+30 ...
                                getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                15 ...
                                ] ...
                   );                     
            else
               set(uiSliderSag, ...
                   'position', [(uiKernelMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                addOnWidth('get')+30 ...
                                (getMainWindowSize('xsize')/4)-(uiKernelMainPanel.Position(3)/2) ...
                                15 ...
                                ] ...
                   );  
            end
        else
            if isVsplash('get') == true && ...
               ~strcmpi(vSplahView('get'), 'all')  
                set(uiSliderSag, ...
                    'Position', [0 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize') ...
                                 15 ...
                                 ]...
                   );                      
            else
                set(uiSliderSag, ...
                    'Position', [(getMainWindowSize('xsize')/4) ...
                                  addOnWidth('get')+30 ...
                                  getMainWindowSize('xsize')/4 ...
                                  15 ...
                                  ]...
                    );               
            end
        end         
    end

    uiSliderTra = uiSliderTraPtr('get');
    if ~isempty(uiSliderTra)   
        if isVsplash('get') == true && ...
           ~strcmpi(vSplahView('get'), 'all')  
            if viewSegPanel('get') 
                set(uiSliderTra, ...
                    'Position', [uiSegMainPanel.Position(3) ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-(uiSegMainPanel.Position(3)/2) ...
                                 15 ...
                                 ]...
                    );                           
            elseif viewKernelPanel('get') 
                set(uiSliderTra, ...
                    'Position', [uiKernelMainPanel.Position(3) ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                 15 ...
                                 ]...
                    );                         
            else
                set(uiSliderTra, ...
                    'Position', [0 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize') ...
                                 15 ...
                                 ]...
                    );                          
            end

        else
            set(uiSliderTra, ...
                'Position', [(getMainWindowSize('xsize')/2) ...
                              addOnWidth('get')+30 ...
                              getMainWindowSize('xsize')/2 ...
                              15 ...
                              ]...
                );     
        end
    end

    uiTopWindow = uiTopWindowPtr('get');
    if ~isempty(uiTopWindow)

        set(uiTopWindow, ...
            'position', [0 ...
                        getMainWindowSize('ysize')-getTopWindowSize('ysize') ...
                        getMainWindowSize('xsize') ...
                        getTopWindowSize('ysize') ...
                        ]...
            );
    end  

    uiOneWindow = uiOneWindowPtr('get');
    if ~isempty(uiOneWindow)
        if switchTo3DMode('get')     == true || ...
           switchToIsoSurface('get') == true || ...
           switchToMIPMode('get')    == true

            ui3DGateWindow = ui3DGateWindowObject('get');

            if view3DPanel('get') == false
                set(uiOneWindow, ...
                    'position', [0 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize') ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                 ]...
                   );    

                if ~isempty(ui3DGateWindow)
                    for ww=1:numel(ui3DGateWindow)
                        set(ui3DGateWindow{ww}, ...
                            'position', [0 ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize') ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                         ]...
                           );  
                    end
               end
            else
                set(uiOneWindow, ...
                    'position', [680 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-680 ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                 ]...
                   );   

                if ~isempty(ui3DGateWindow)
                    for ww=1:numel(ui3DGateWindow)
                        set(ui3DGateWindow{ww}, ...
                            'position', [680 ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize')-680 ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                         ]...
                           );                                  
                    end
                end
            end
        else
            if viewSegPanel('get') == true 
                set(uiOneWindow, ...
                    'position', [uiSegMainPanel.Position(3) ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-uiSegMainPanel.Position(3) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                 ]...
                   );     
            elseif viewKernelPanel('get') == true 
                set(uiOneWindow, ...
                    'position', [uiKernelMainPanel.Position(3) ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize')-uiKernelMainPanel.Position(3) ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                 ]...
                   );                            
            else                    
                set(uiOneWindow, ...
                    'position', [0 ...
                                 addOnWidth('get')+30 ...
                                 getMainWindowSize('xsize') ...
                                 getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                 ]...
                   );
            end

            txt = axesText('get', 'axe');
            if ~isempty(txt)
                set(txt.Parent, ...
                    'Position', [5 ...
                                 uiOneWindow.Position(4)-getTopWindowSize('ysize') ...
                                 100 ...
                                 200 ...
                                 ]...
                    );                                               
            end
        end
    end  

    uiMain3DPanel = uiMain3DPanelPtr('get');
    if ~isempty(uiMain3DPanel)
        if switchTo3DMode('get')     == true || ...
           switchToIsoSurface('get') == true || ...
           switchToMIPMode('get')    == true            
            set(uiMain3DPanel, ...
                'position', [0 ...
                             addOnWidth('get')+30 ...
                             680 ...
                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                             ]...
               );                
        end

        ui3DPanelSlider = ui3DPanelSliderPtr('get');
        if ~isempty(ui3DPanelSlider)
            if switchTo3DMode('get')     == true || ...
               switchToIsoSurface('get') == true || ...
               switchToMIPMode('get')    == true     
                aMain3DPanelPosition = get(uiMain3DPanel, 'position');
                set(ui3DPanelSlider, ...
                    'position', [660 ...
                                 0 ...
                                 20 ...
                                 aMain3DPanelPosition(4) ...
                                 ]...
                   );                
            end
        end            
    end            
 
    uiProgressWindow = uiProgressWindowPtr('get');
    if ~isempty(uiProgressWindow)
        set(uiProgressWindow, ...
            'position', [0 ...
                         0 ...
                         getMainWindowSize('xsize') ...
                         30 ...
                         ]...
           );
    end 

    if isFusion('get') == true

        uiAlphaSlider = uiAlphaSliderPtr('get');
        if ~isempty(uiAlphaSlider) 

            aAxePosition = uiAlphaSlider.Parent.Position;                                                                 
            if size(dicomBuffer('get'), 3) == 1
                set(uiAlphaSlider, ...
                    'Position', [10 ...
                                 35 ...
                                 aAxePosition(3)-20 ...
                                 15 ...
                                 ] ...
                    );
            else
                if isVsplash('get') == true && ...
                   ~strcmpi(vSplahView('get'), 'all')
                    if viewSegPanel('get') 
                        
                        set(uiAlphaSlider, ...
                            'Position', [uiSegMainPanel.Position(3)+10 ...
                                         addOnWidth('get')+50 ...
                                         aAxePosition(3)-uiSegMainPanel.Position(3)-20 ...
                                         15 ...
                                         ] ...
                            );
                    elseif viewKernelPanel('get') == true 
                        
                        set(uiAlphaSlider, ...
                            'Position', [uiKernelMainPanel.Position(3)+10 ...
                                         addOnWidth('get')+50 ...
                                         aAxePosition(3)-uiKernelMainPanel.Position(3)-20 ...
                                         15 ...
                                         ] ...
                            );
                    else
                        set(uiAlphaSlider, ...
                            'Position', [10 ...
                                         addOnWidth('get')+50 ...
                                         aAxePosition(3)-20 ...
                                         15 ...
                                         ] ...
                            );
                    end
                else
                    set(uiAlphaSlider, ...
                        'Position', [aAxePosition(3)/2+10 ...
                                     addOnWidth('get')+50 ...
                                     aAxePosition(3)/2-20 ...
                                     15 ...
                                     ] ...
                        );
                end
            end
        end

        ptrFusionColorbar = uiFusionColorbarPtr('get');
        if ~isempty(ptrFusionColorbar) 

            aAxePosition = ptrFusionColorbar.Parent.Position;
            if size(dicomBuffer('get'), 3) == 1
                set(ptrFusionColorbar, ...
                    'Position', [aAxePosition(3)-49 ...
                                 27 ...
                                 40 ...
                                 ((aAxePosition(4))/2)-41-20 ...
                                 ] ...
                   );
            else
                if isVsplash('get') == true && ...
                  ~strcmpi(vSplahView('get'), 'all')
                    if viewSegPanel('get') 
                        
                        set(ptrFusionColorbar, ...
                            'Position', [aAxePosition(3)-(uiSegMainPanel.Position(3)/2)-49 ...
                                         29 ...
                                         40 ...
                                         ((aAxePosition(4))/2)-35-20 ...
                                         ] ...
                           );
                    elseif viewKernelPanel('get') == true 
                        
                        set(ptrFusionColorbar, ...
                            'Position', [aAxePosition(3)-(uiKernelMainPanel.Position(3)/2)-49 ...
                                         29 ...
                                         40 ...
                                         ((aAxePosition(4))/2)-35-20 ...
                                         ] ...
                           );
                    else
                        set(ptrFusionColorbar, ...
                            'Position', [aAxePosition(3)-49 ...
                                         29 ...
                                         40 ...
                                         ((aAxePosition(4))/2)-35-20 ...
                                         ] ...
                           );
                    end
                else
                    set(ptrFusionColorbar, ...
                        'Position', [aAxePosition(3)-49 ...
                                     29 ...
                                     40 ...
                                     ((aAxePosition(4))/2)-35-20 ...
                                     ] ...
                        );
                end
            end                   
        end

        uiFusionSliderWindow = uiFusionSliderWindowPtr('get');
        if ~isempty(uiFusionSliderWindow) 

            aAxePosition = uiFusionSliderWindow.Parent.Position;                                                                 
            if size(dicomBuffer('get'), 3) == 1
                set(uiFusionSliderWindow, ...
                    'Position', [aAxePosition(3)-50 ...
                                 55 ...
                                 12 ...
                                 (aAxePosition(4)/2)-75-20 ...
                                 ] ...
                    );
            else
                set(uiFusionSliderWindow, ...
                    'Position', [aAxePosition(3)-50 ...
                                 70 ...
                                 12 ...
                                 (aAxePosition(4)/2)-75-20 ...
                                 ] ...
                    );
            end   
        end

        uiFusionSliderLevel = uiFusionSliderLevelPtr('get');
        if ~isempty(uiFusionSliderLevel) 
            aAxePosition = uiFusionSliderLevel.Parent.Position;                                                                 
            if size(dicomBuffer('get'), 3) == 1
                set(uiFusionSliderLevel, ...
                    'Position', [aAxePosition(3)-21 ...
                                 55 ...
                                 12 ...
                                 (aAxePosition(4)/2)-75-20 ...
                                 ] ...
                    );
            else
                set(uiFusionSliderLevel, ...
                    'Position', [aAxePosition(3)-21 ...
                                 70 ...
                                 12 ...
                                 (aAxePosition(4)/2)-75-20 ...
                                 ] ...
                    );
            end
        end

        uiSliderWindow = uiSliderWindowPtr('get');
        if ~isempty(uiSliderWindow)
            aAxePosition = uiSliderWindow.Parent.Position;                                                                
            if size(dicomBuffer('get'), 3) == 1
                set(uiSliderWindow, ...
                    'Position', [aAxePosition(3)-50 ...
                                 (aAxePosition(4)/2)-15 ...
                                 12 ...
                                 (aAxePosition(4)/2)-30-20 ...
                                 ] ...
                    );                    
            else
                set(uiSliderWindow, ...
                    'Position', [aAxePosition(3)-50 ...
                                 aAxePosition(4)/2 ...
                                 12 ...
                                 (aAxePosition(4)/2)-45-20 ...
                                 ] ...
                    );                   
            end     
        end 

        uiSliderLevel = uiSliderLevelPtr('get');
        if ~isempty(uiSliderLevel)

            aAxePosition = uiSliderLevel.Parent.Position;                                                                
            if size(dicomBuffer('get'), 3) == 1
                set(uiSliderLevel, ...
                    'Position', [aAxePosition(3)-21 ...
                                 (aAxePosition(4)/2)-15 ...
                                 12 ...
                                 (aAxePosition(4)/2)-30-20 ...
                                 ] ...
                    );
            else
                set(uiSliderLevel, ...
                    'Position', [aAxePosition(3)-21 ...
                                 aAxePosition(4)/2 ...
                                 12 ...
                                 (aAxePosition(4)/2)-45-20 ...
                                 ] ...
                    );
            end     
        end

        ptrColorbar = uiColorbarPtr('get');
        if ~isempty(ptrColorbar)  

            aAxePosition = ptrColorbar.Parent.Position;
            if size(dicomBuffer('get'), 3) == 1
                set(ptrColorbar, ...
                    'Position', [aAxePosition(3)-49 ...
                                 (aAxePosition(4)/2)-9 ...
                                 40 ...
                                 (aAxePosition(4)/2)+5-20 ...
                                 ] ...
                    );                  
            else  
                if isVsplash('get') == true && ...
                  ~strcmpi(vSplahView('get'), 'all')
                    if viewSegPanel('get')
                        
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-(uiSegMainPanel.Position(3)/2)-49 ...
                                         (aAxePosition(4)/2) ...
                                         40 ...
                                         (aAxePosition(4)/2)-4-20 ...
                                         ] ...
                           );
                    elseif viewKernelPanel('get') == true 
                        
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-(uiKernelMainPanel.Position(3)/2)-49 ...
                                         (aAxePosition(4)/2) ...
                                         40 ...
                                         (aAxePosition(4)/2)-4-20 ...
                                         ] ...
                           );
                    else
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-49 ...
                                         (aAxePosition(4)/2) ...
                                         40 ...
                                         (aAxePosition(4)/2)-4-20 ...
                                         ] ...
                           );
                    end
                else                        
                    set(ptrColorbar, ...
                        'Position', [aAxePosition(3)-49 ...
                                     (aAxePosition(4)/2) ...
                                     40 ...
                                     (aAxePosition(4)/2)-4-20 ...
                                     ] ...
                        );
                end
            end
        end  
    else
        uiSliderWindow = uiSliderWindowPtr('get');
        if ~isempty(uiSliderWindow)
            aAxePosition = uiSliderWindow.Parent.Position;                                                                
            if size(dicomBuffer('get'), 3) == 1
                set(uiSliderWindow, ...
                    'Position', [aAxePosition(3)-50 ...
                                 35 ...
                                 12 ...
                                 aAxePosition(4)-80-20 ...
                                 ] ...
                    );                    
            else
                set(uiSliderWindow, ...
                    'Position', [aAxePosition(3)-50 ...
                                 50 ...
                                 12 ...
                                 aAxePosition(4)-95-20 ...
                                 ] ...
                    );                   
            end     
        end

        uiSliderLevel = uiSliderLevelPtr('get');
        if ~isempty(uiSliderLevel)

            aAxePosition = uiSliderLevel.Parent.Position;                                                                
            if size(dicomBuffer('get'), 3) == 1
                set(uiSliderLevel, ...
                    'Position', [aAxePosition(3)-21 ...
                                 35 ...
                                 12 ...
                                 aAxePosition(4)-80-20 ...
                                 ] ...
                    );
            else
                set(uiSliderLevel, ...
                    'Position', [aAxePosition(3)-21 ...
                                 50 ...
                                 12 ...
                                 aAxePosition(4)-95-20 ...
                                 ] ...
                   );
            end     
        end

        ptrColorbar = uiColorbarPtr('get');
        if ~isempty(ptrColorbar)  

            aAxePosition = ptrColorbar.Parent.Position;
            if size(dicomBuffer('get'), 3) == 1
                set(ptrColorbar, ...
                    'Position', [aAxePosition(3)-49 ...
                                 7 ...
                                 40 ...
                                 aAxePosition(4)-11-20 ...
                                 ] ...
                    );                    
            else  
                if isVsplash('get') == true && ...
                  ~strcmpi(vSplahView('get'), 'all')
                    if viewSegPanel('get') 
                        
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-(uiSegMainPanel.Position(3)/2)-49 ...
                                         7 ...
                                         40 ...
                                         aAxePosition(4)-11-20 ...
                                         ] ...
                            );
                    elseif viewKernelPanel('get') == true 
                        
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-(uiKernelMainPanel.Position(3)/2)-49 ...
                                         7 ...
                                         40 ...
                                         aAxePosition(4)-11-20 ...
                                         ] ...
                            );
                    else
                        set(ptrColorbar, ...
                            'Position', [aAxePosition(3)-49 ...
                                         7 ...
                                         40 ... 
                                         aAxePosition(4)-11-20 ...
                                         ] ...
                            );
                    end
                else                             
                    set(ptrColorbar, ...
                        'Position', [aAxePosition(3)-49 ...
                                     7 ...
                                     40 ...
                                     aAxePosition(4)-11-20 ...
                                     ] ...
                        );
                end
            end
        end                 
    end

end 
