function setAxesLimitsFromSource(sourceAxes, targetAxes)
%function setAxesLimitsFromSource(sourceAxes, targetAxes)
%Set axe Limit and camera view from a source axe.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2024, Daniel Lafontaine, on behalf of the TriDFusion development team.
% 
% This file is part of The Triple Dimention Fusion (TriDFusion).
% 
% TriDFusion development has been led by:  Daniel Lafontaine
% 
% TriDFusion is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>. 

    set(targetAxes, 'XLim'                  , get(sourceAxes, 'XLim'), ...
                    'YLim'                  , get(sourceAxes, 'YLim'), ...
                    'XLimMode'              , get(sourceAxes, 'XLimMode'), ...
                    'YLimMode'              , get(sourceAxes, 'YLimMode'), ...
                    'ZLim'                  , get(sourceAxes, 'ZLim'), ...
                    'ZLimMode'              , get(sourceAxes, 'ZLimMode'), ...
                    'CameraPosition'        , get(sourceAxes, 'CameraPosition'), ...
                    'CameraPositionMode'    , get(sourceAxes, 'CameraPositionMode'), ...
                    'CameraTarget'          , get(sourceAxes, 'CameraTarget'), ...
                    'CameraTargetMode'      , get(sourceAxes, 'CameraTargetMode'), ...
                    'CameraUpVector'        , get(sourceAxes, 'CameraUpVector'), ...
                    'CameraUpVectorMode'    , get(sourceAxes, 'CameraUpVectorMode'), ...
                    'CameraViewAngle'       , get(sourceAxes, 'CameraViewAngle'), ...
                    'CameraViewAngleMode'   , get(sourceAxes, 'CameraViewAngleMode'), ...
                    'View'                  , get(sourceAxes, 'View'), ...
                    'DataAspectRatio'       , get(sourceAxes, 'DataAspectRatio'), ...
                    'DataAspectRatioMode'   , get(sourceAxes, 'DataAspectRatioMode'), ...
                    'PlotBoxAspectRatio'    , get(sourceAxes, 'PlotBoxAspectRatio'), ...
                    'PlotBoxAspectRatioMode', get(sourceAxes, 'PlotBoxAspectRatioMode'));
 
end