function aMask = getBrownFatTotalSegmentorAnnotationMask(sSegmentationFolderName, aMask)
%function aMask = getBrownFatTotalSegmentorAnnotationMask(sSegmentationFolderName, aMask)
%Create an annoted mask, from a machine learning segmentation.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2023, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    asSegmentList = {
%         'rib_left_1.nii.gz',...
%         'rib_left_2.nii.gz',...
%         'rib_left_3.nii.gz',...
%         'rib_left_4.nii.gz',...
%         'rib_left_5.nii.gz',...
%         'rib_left_6.nii.gz',...
%         'rib_left_7.nii.gz',...
%         'rib_left_8.nii.gz',...
%         'rib_left_9.nii.gz',...
%         'rib_left_10.nii.gz',...
%         'rib_left_11.nii.gz',...
%         'rib_left_12.nii.gz',...
%         'rib_right_1.nii.gz',...
%         'rib_right_2.nii.gz',...
%         'rib_right_3.nii.gz',...
%         'rib_right_4.nii.gz',...
%         'rib_right_5.nii.gz',...
%         'rib_right_6.nii.gz',...
%         'rib_right_7.nii.gz',...
%         'rib_right_8.nii.gz',...
%         'rib_right_9.nii.gz',...
%         'rib_right_10.nii.gz',...
%         'rib_right_11.nii.gz',...
%         'rib_right_12.nii.gz',...              
    'vertebrae_C1.nii.gz',...
    'vertebrae_C2.nii.gz',...
    'vertebrae_C3.nii.gz',...
    'vertebrae_C4.nii.gz',...
    'vertebrae_C5.nii.gz',...
    'vertebrae_C6.nii.gz',...
    'vertebrae_C7.nii.gz',...    
    'vertebrae_T1.nii.gz',...
    'vertebrae_T2.nii.gz',...
    'vertebrae_T3.nii.gz',...
    'vertebrae_T4.nii.gz',...
    'vertebrae_T5.nii.gz',...
    'vertebrae_T6.nii.gz',...
    'vertebrae_T7.nii.gz',...
    'vertebrae_T8.nii.gz',...
    'vertebrae_T9.nii.gz',...   
    'vertebrae_T10.nii.gz',...
    'vertebrae_T11.nii.gz',...
    'vertebrae_T12.nii.gz',...        
    'clavicula_right.nii.gz', ...
    'clavicula_left.nii.gz', ...
    'kidney_right.nii.gz', ...
    'kidney_left.nii.gz', ...  
    'scapula_right.nii.gz',...
    'scapula_left.nii.gz', ...
    'scapula.nii.gz', ...
    'sternum.nii.gz'};
 
    dNbElements = numel(asSegmentList);

    for bb=1:dNbElements

        if mod(bb,5)==1 || bb == 1 || bb == dNbElements
            
            progressBar( bb/dNbElements-0.0001, sprintf('Computing association item %d/%d, please wait.', bb, dNbElements) );
        end

        sNiiFileName = sprintf('%s%s', sSegmentationFolderName, asSegmentList{bb});  

        if exist(sNiiFileName, 'file')

            nii = nii_tool('load', sNiiFileName);
            aObjectMask = imrotate3(nii.img, 90, [0 0 1], 'nearest');

            if contains(asSegmentList{bb}, 'vertebrae_C') 
                dMaskValue =1;

            elseif contains(asSegmentList{bb}, 'vertebrae_T') 
                dMaskValue =2;               

            elseif contains(asSegmentList{bb}, 'clavicula')
                dMaskValue =3;

            elseif contains(asSegmentList{bb}, 'kidney')
                dMaskValue =4;

            elseif contains(asSegmentList{bb}, 'scapula')
                dMaskValue =5;

            elseif contains(asSegmentList{bb}, 'sternum')
                dMaskValue =6;     

%                 elseif contains(asSegmentList{bb}, 'rib')
%                     dMaskValue =7;                     
            else
                dMaskValue =0;                     
           end
                
            aMask(aObjectMask~=0)=dMaskValue;
        end
    end

    aMask=aMask(:,:,end:-1:1);

    progressBar( 1, 'Ready' );

end