function setMachineLearningPSMAGa68PETFullAICallback(hObject, ~)
%function setMachineLearningPSMAGa68PETFullAICallback()
%Run PSMA Ga68 PET Full AI Tumor Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2024, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    [sPredictScript] = validateNnUNetv2Installation();
    
    dlgPSMAGa68PETFullAISegmentation  = [];
  
    if ~isempty(sPredictScript) ... % External Segmentor is installed

        if exist('hObject', 'var')

            DLG_PSMA_Ga68_SPECT_PERCENT_X = 380;
            DLG_PSMA_Ga68_SPECT_PERCENT_Y = 215;

            if viewerUIFigure('get') == true
        
                dlgPSMAGa68PETFullAISegmentation = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_PSMA_Ga68_SPECT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_PSMA_Ga68_SPECT_PERCENT_Y/2) ...
                                        DLG_PSMA_Ga68_SPECT_PERCENT_X ...
                                        DLG_PSMA_Ga68_SPECT_PERCENT_Y ...
                                        ],...
                           'Resize', 'off', ...
                           'Color', viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name' , 'PSMA Ga68 Machine Learning Full AI PET Segmentation'...
                           );
            else       
                dlgPSMAGa68PETFullAISegmentation = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_PSMA_Ga68_SPECT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_PSMA_Ga68_SPECT_PERCENT_Y/2) ...
                                        DLG_PSMA_Ga68_SPECT_PERCENT_X ...
                                        DLG_PSMA_Ga68_SPECT_PERCENT_Y ...
                                        ],...
                           'MenuBar', 'none',...
                           'Resize', 'off', ...    
                           'NumberTitle','off',...
                           'MenuBar', 'none',...
                           'Color', viewerBackgroundColor('get'), ...
                           'Name', 'PSMA Ga68 Machine Learning Full AI PET Segmentation',...
                           'Toolbar','none'...               
                           );    
            end

            % Trainer with Dice and CE Loss
        
                uicontrol(dlgPSMAGa68PETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Trainer with Dice and CE Loss, no smoothing',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkPSMAGa68PETFullAICELossCallback, ...
                          'position', [40 165 250 20]...
                          );
        
            chkPSMAGa68PETFullAICELoss = ...
                uicontrol(dlgPSMAGa68PETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningPSMAGa68CELoss('get'),...
                          'position', [20 165 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkPSMAGa68PETFullAICELossCallback...
                          );

            % Classify Segmentation
        
                uicontrol(dlgPSMAGa68PETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Classify the Segmentation',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkPSMAGa68PETFullAIClassifySegmentationCallback, ...
                          'position', [40 140 250 20]...
                          );
        
            chkPSMAGa68PETFullAIClassifySegmentation = ...
                uicontrol(dlgPSMAGa68PETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningPSMAGa68ClassifySegmentation('get'),...
                          'position', [20 140 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkPSMAGa68PETFullAIClassifySegmentationCallback...
                          );

            % Smooth mask

                uicontrol(dlgPSMAGa68PETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Smooth Mask',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'ButtonDownFcn'  , @chkPSMAGa68PETFullAISmoothMaskCallback, ...
                          'position', [40 115 150 20]...
                          );

            chkPSMAGa68PETFullAISmoothMask = ...
                uicontrol(dlgPSMAGa68PETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningPSMAGa68SmoothMask('get'),...
                          'position', [20 115 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'Callback', @chkPSMAGa68PETFullAISmoothMaskCallback...
                          );
             % Pixel Edge
        
                uicontrol(dlgPSMAGa68PETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Pixel Edge',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkPSMAGa68PETFullAIPixelEdgeCallback, ...
                          'position', [40 90 150 20]...
                          );
        
            chkPSMAGa68PETFullAIPixelEdge = ...
                uicontrol(dlgPSMAGa68PETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , pixelEdge('get'),...
                          'position', [20 90 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkPSMAGa68PETFullAIPixelEdgeCallback...
                          );

            % Smallest Contour (ml)
        
                uicontrol(dlgPSMAGa68PETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'Smallest Contour (ml)',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 65 250 20]...
                          );
        
            edtPSMAGa68PETFullAISmallestVoiValue = ...
                uicontrol(dlgPSMAGa68PETFullAISegmentation, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 65 75 20], ...
                          'String'  , num2str(machineLearningPSMAGa68SmallestVoiValue('get')), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtPSMAGa68PETFullAISmallestVoiValueCallback ...
                          );  
        
             % Cancel or Proceed
        
             uicontrol(dlgPSMAGa68PETFullAISegmentation,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelPSMAGa68PETFullAISegmentationCallback...
                       );
        
             uicontrol(dlgPSMAGa68PETFullAISegmentation,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedPSMAGa68PETFullAISegmentationCallback...
                      );               
        else

            % Options

            tPSMAGa68PETFullAI.options.CELossTrainer        = machineLearningPSMAGa68CELoss('get');
            tPSMAGa68PETFullAI.options.classifySegmentation = machineLearningPSMAGa68ClassifySegmentation('get');
            tPSMAGa68PETFullAI.options.smoothMask           = machineLearningPSMAGa68SmoothMask('get');
            tPSMAGa68PETFullAI.options.smallestVoiValue     = machineLearningPSMAGa68SmallestVoiValue('get');
            tPSMAGa68PETFullAI.options.pixelEdge            = pixelEdge('get');
    
            setMachineLearningPSMAGa68PETFullAI(sPredictScript, tPSMAGa68PETFullAI); 
        end
    end

    function chkPSMAGa68PETFullAICELossCallback(hObject, ~)

        bObjectValue = get(chkPSMAGa68PETFullAICELoss, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkPSMAGa68PETFullAICELoss, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkPSMAGa68PETFullAICELoss, 'Value');

        machineLearningPSMAGa68CELoss('set', bObjectValue);
    end

    function chkPSMAGa68PETFullAIClassifySegmentationCallback(hObject, ~)

        bObjectValue = get(chkPSMAGa68PETFullAIClassifySegmentation, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkPSMAGa68PETFullAIClassifySegmentation, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkPSMAGa68PETFullAIClassifySegmentation, 'Value');

        machineLearningPSMAGa68ClassifySegmentation('set', bObjectValue);
    end

    function chkPSMAGa68PETFullAISmoothMaskCallback(hObject, ~)

        bObjectValue = get(chkPSMAGa68PETFullAISmoothMask, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkPSMAGa68PETFullAISmoothMask, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkPSMAGa68PETFullAISmoothMask, 'Value');

        machineLearningPSMAGa68SmoothMask('set', bObjectValue);
    end

    function edtPSMAGa68PETFullAISmallestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtPSMAGa68PETFullAISmallestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtPSMAGa68PETFullAISmallestVoiValue, 'String', num2str(dObjectValue));
        end

        machineLearningPSMAGa68SmallestVoiValue('set', dObjectValue);

    end

    function chkPSMAGa68PETFullAIPixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkPSMAGa68PETFullAIPixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkPSMAGa68PETFullAIPixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkPSMAGa68PETFullAIPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox

        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end

    function cancelPSMAGa68PETFullAISegmentationCallback(~, ~)   

        delete(dlgPSMAGa68PETFullAISegmentation);
    end
    
    function proceedPSMAGa68PETFullAISegmentationCallback(~, ~)

        % Options

        tPSMAGa68PETFullAI.options.CELossTrainer        =            get(chkPSMAGa68PETFullAICELoss, 'Value');
        tPSMAGa68PETFullAI.options.classifySegmentation =            get(chkPSMAGa68PETFullAIClassifySegmentation, 'Value');
        tPSMAGa68PETFullAI.options.smoothMask           =            get(chkPSMAGa68PETFullAISmoothMask, 'Value');
        tPSMAGa68PETFullAI.options.smallestVoiValue     = str2double(get(edtPSMAGa68PETFullAISmallestVoiValue , 'String'));
        tPSMAGa68PETFullAI.options.pixelEdge            =            get(chkPSMAGa68PETFullAIPixelEdge, 'Value');

        delete(dlgPSMAGa68PETFullAISegmentation);

        setMachineLearningPSMAGa68PETFullAI(sPredictScript, tPSMAGa68PETFullAI); 
    end

end