function setMachineLearningFDGBrownFatPETFullAICallback(hObject, ~)
%function setMachineLearningFDGBrownFatPETFullAICallback(hObject)
%Run FDG SUV Brown Fat PET Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2023, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    [sPredictScript] = validateNnUNetv2Installation();
    
    dlgFDGBrownFatPETFullAISegmentation  = [];
  
    if ~isempty(sPredictScript) ... % External Segmentor is installed

        if exist('hObject', 'var')

            DLG_FDG_BROWN_FAT_PERCENT_X = 380;
            DLG_FDG_BROWN_FAT_PERCENT_Y = 265;


            if viewerUIFigure('get') == true
        
                dlgFDGBrownFatPETFullAISegmentation = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_FDG_BROWN_FAT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_FDG_BROWN_FAT_PERCENT_Y/2) ...
                                        DLG_FDG_BROWN_FAT_PERCENT_X ...
                                        DLG_FDG_BROWN_FAT_PERCENT_Y ...
                                        ],...
                           'Resize', 'off', ...
                           'Color', viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name' , 'FDG Machine Learning Full AI Brown Fat Segmentation'...
                           );
            else       
                dlgFDGBrownFatPETFullAISegmentation = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_FDG_BROWN_FAT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_FDG_BROWN_FAT_PERCENT_Y/2) ...
                                        DLG_FDG_BROWN_FAT_PERCENT_X ...
                                        DLG_FDG_BROWN_FAT_PERCENT_Y ...
                                        ],...
                           'MenuBar', 'none',...
                           'Resize', 'off', ...    
                           'NumberTitle','off',...
                           'MenuBar', 'none',...
                           'Color', viewerBackgroundColor('get'), ...
                           'Name', 'FDG Machine Learning Full AI Brown Fat Segmentation',...
                           'Toolbar','none'...               
                           );    
            end

            setObjectIcon(dlgFDGBrownFatPETFullAISegmentation);

            % Trainer with Dice and CE Loss
        
                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Trainer with Dice and CE Loss, no smoothing',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkFDGBrownFatPETFullAICELossCallback, ...
                          'position', [40 215 250 20]...
                          );
        
            chkFDGBrownFatPETFullAICELoss = ...
                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningFDGBrownFatCELoss('get'),...
                          'position', [20 215 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkFDGBrownFatPETFullAICELossCallback...
                          );

            % Classify Segmentation
        
                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Classify the Segmentation',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkFDGBrownFatPETFullAIClassifySegmentationCallback, ...
                          'position', [40 190 250 20]...
                          );
        
            chkFDGBrownFatPETFullAIClassifySegmentation = ...
                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningFDGBrownFatClassifySegmentation('get'),...
                          'position', [20 190 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkFDGBrownFatPETFullAIClassifySegmentationCallback...
                          );

            % SUV scaled
        
                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'SUV-Scaled',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkFDGBrownFatPETFullAISUVScaledCallback, ...
                          'position', [40 165 250 20]...
                          );
        
            chkFDGBrownFatPETFullAISUVScaled = ...
                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningFDGBrownFatSUVScaled('get'),...
                          'position', [20 165 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkFDGBrownFatPETFullAISUVScaledCallback...
                          );

             % SUV normalization

            if machineLearningFDGBrownFatSUVScaled('get') == true
                sSUVNormalizationTxtEnable = 'Inactive';
                sSUVNormalizationChkEnable = 'on';
            else
                sSUVNormalizationTxtEnable = 'on';
                sSUVNormalizationChkEnable = 'off';               
            end        

            txtFDGBrownFatPETFullAISUVNormalization = ...            
                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , sSUVNormalizationTxtEnable,...
                          'string'  , 'SUV-Normalization',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkFDGBrownFatPETFullAISUVNormalizationCallback, ...
                          'position', [60 140 250 20]...
                          );
        
            chkFDGBrownFatPETFullAISUVNormalization = ...
                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , sSUVNormalizationChkEnable,...
                          'value'   , machineLearningFDGBrownFatSUVNormalization('get'),...
                          'position', [40 140 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkFDGBrownFatPETFullAISUVNormalizationCallback...
                          );
            % Smooth mask

                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Smooth Mask',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'ButtonDownFcn'  , @chkFDGBrownFatPETFullAISmoothMaskCallback, ...
                          'position', [40 115 150 20]...
                          );

            chkFDGBrownFatPETFullAISmoothMask = ...
                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningFDGBrownFatSmoothMask('get'),...
                          'position', [20 115 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'Callback', @chkFDGBrownFatPETFullAISmoothMaskCallback...
                          );
             % Pixel Edge
        
                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Pixel Edge',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkFDGBrownFatPETFullAIPixelEdgeCallback, ...
                          'position', [40 90 150 20]...
                          );
        
            chkFDGBrownFatPETFullAIPixelEdge = ...
                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , pixelEdge('get'),...
                          'position', [20 90 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkFDGBrownFatPETFullAIPixelEdgeCallback...
                          );

            % Smallest Contour (ml)
        
                uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'Smallest Contour (ml)',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 65 250 20]...
                          );
        
            edtFDGBrownFatPETFullAISmallestVoiValue = ...
                uicontrol(dlgFDGBrownFatPETFullAISegmentation, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 65 75 20], ...
                          'String'  , num2str(machineLearningFDGBrownFatSmallestVoiValue('get')), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtFDGBrownFatPETFullAISmallestVoiValueCallback ...
                          );  
        
             % Cancel or Proceed
        
             uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelFDGBrownFatPETFullAISegmentationCallback...
                       );
        
             uicontrol(dlgFDGBrownFatPETFullAISegmentation,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedFDGBrownFatPETFullAISegmentationCallback...
                      );               
        else

            % Options

            tBrownFatPETFullAI.options.CELossTrainer        = machineLearningFDGBrownFatCELoss('get');
            tBrownFatPETFullAI.options.classifySegmentation = machineLearningFDGBrownFatClassifySegmentation('get');
            tBrownFatPETFullAI.options.smoothMask           = machineLearningFDGBrownFatSmoothMask('get');
            tBrownFatPETFullAI.options.smallestVoiValue     = machineLearningFDGBrownFatSmallestVoiValue('get');
            tBrownFatPETFullAI.options.pixelEdge            = pixelEdge('get');
            tBrownFatPETFullAI.options.SUVNormalization     = machineLearningFDGBrownFatSUVNormalization('get');
            tBrownFatPETFullAI.options.SUVScaled            = machineLearningFDGBrownFatSUVScaled('get');
    
            setMachineLearningFDGBrownFatPETFullAI(sPredictScript, tBrownFatPETFullAI); 
        end
    end

    function chkFDGBrownFatPETFullAICELossCallback(hObject, ~)

        bObjectValue = get(chkFDGBrownFatPETFullAICELoss, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFDGBrownFatPETFullAICELoss, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFDGBrownFatPETFullAICELoss, 'Value');

        machineLearningFDGBrownFatCELoss('set', bObjectValue);
    end

    function chkFDGBrownFatPETFullAIClassifySegmentationCallback(hObject, ~)

        bObjectValue = get(chkFDGBrownFatPETFullAIClassifySegmentation, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFDGBrownFatPETFullAIClassifySegmentation, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFDGBrownFatPETFullAIClassifySegmentation, 'Value');

        machineLearningFDGBrownFatClassifySegmentation('set', bObjectValue);
    end

    function chkFDGBrownFatPETFullAISmoothMaskCallback(hObject, ~)

        bObjectValue = get(chkFDGBrownFatPETFullAISmoothMask, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFDGBrownFatPETFullAISmoothMask, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFDGBrownFatPETFullAISmoothMask, 'Value');

        machineLearningFDGBrownFatSmoothMask('set', bObjectValue);
    end

    function chkFDGBrownFatPETFullAISUVScaledCallback(hObject, ~)

        bObjectValue = get(chkFDGBrownFatPETFullAISUVScaled, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDGBrownFatPETFullAISUVScaled, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDGBrownFatPETFullAISUVScaled, 'Value');

        machineLearningFDGBrownFatSUVScaled('set', bObjectValue);

        % SUV normalization

        if machineLearningFDGBrownFatSUVScaled('get') == true
            sSUVNormalizationTxtEnable = 'Inactive';
            sSUVNormalizationChkEnable = 'on';
        else
            sSUVNormalizationTxtEnable = 'on';
            sSUVNormalizationChkEnable = 'off';               
        end        

        set(txtFDGBrownFatPETFullAISUVNormalization, 'Enable', sSUVNormalizationTxtEnable);
        set(chkFDGBrownFatPETFullAISUVNormalization, 'Enable', sSUVNormalizationChkEnable);        
        
    end

    function chkFDGBrownFatPETFullAISUVNormalizationCallback(hObject, ~)

        bObjectValue = get(chkFDGBrownFatPETFullAISUVNormalization, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDGBrownFatPETFullAISUVNormalization, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDGBrownFatPETFullAISUVNormalization, 'Value');

        machineLearningFDGBrownFatSUVNormalization('set', bObjectValue);
        
    end

    function edtFDGBrownFatPETFullAISmallestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtFDGBrownFatPETFullAISmallestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtFDGBrownFatPETFullAISmallestVoiValue, 'String', num2str(dObjectValue));
        end

        machineLearningFDGBrownFatSmallestVoiValue('set', dObjectValue);

    end

    function chkFDGBrownFatPETFullAIPixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkFDGBrownFatPETFullAIPixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDGBrownFatPETFullAIPixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDGBrownFatPETFullAIPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox

        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end

    function cancelFDGBrownFatPETFullAISegmentationCallback(~, ~)   

        delete(dlgFDGBrownFatPETFullAISegmentation);
    end
    
    function proceedFDGBrownFatPETFullAISegmentationCallback(~, ~)

        % Options

        tBrownFatPETFullAI.options.CELossTrainer        =            get(chkFDGBrownFatPETFullAICELoss, 'Value');
        tBrownFatPETFullAI.options.classifySegmentation =            get(chkFDGBrownFatPETFullAIClassifySegmentation, 'Value');
        tBrownFatPETFullAI.options.smoothMask           =            get(chkFDGBrownFatPETFullAISmoothMask, 'Value');
        tBrownFatPETFullAI.options.smallestVoiValue     = str2double(get(edtFDGBrownFatPETFullAISmallestVoiValue , 'String'));
        tBrownFatPETFullAI.options.pixelEdge            =            get(chkFDGBrownFatPETFullAIPixelEdge       , 'value' );
        tBrownFatPETFullAI.options.SUVNormalization     =            get(chkFDGBrownFatPETFullAISUVNormalization, 'value' );
        tBrownFatPETFullAI.options.SUVScaled            =            get(chkFDGBrownFatPETFullAISUVScaled, 'value' );

        delete(dlgFDGBrownFatPETFullAISegmentation);

        setMachineLearningFDGBrownFatPETFullAI(sPredictScript, tBrownFatPETFullAI); 
    end
end