function setMachineLearningBreastCancerPETCTFullAICallback(hObject, ~)
%function setMachineLearningBreastCancerPETCTFullAICallback()
%Run Metastatic Breast Cancer PT/CT Full AI Tumor Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2024, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    [sPredictScript] = validateNnUNetv2Installation();
    
    dlgBreastCancerPETCTFullAISegmentation  = [];
  
    if ~isempty(sPredictScript) ... % External Segmentor is installed

        if exist('hObject', 'var')

            DLG_BREAST_CANCER_PETCT_PERCENT_X = 380;
            DLG_BREAST_CANCER_PETCT_PERCENT_Y = 215;

            if viewerUIFigure('get') == true
        
                dlgBreastCancerPETCTFullAISegmentation = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_BREAST_CANCER_PETCT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_BREAST_CANCER_PETCT_PERCENT_Y/2) ...
                                        DLG_BREAST_CANCER_PETCT_PERCENT_X ...
                                        DLG_BREAST_CANCER_PETCT_PERCENT_Y ...
                                        ],...
                           'Resize', 'off', ...
                           'Color', viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name' , 'Metastatic Breast Cancer Machine Learning Full AI PET CT Segmentation'...
                           );
            else       
                dlgBreastCancerPETCTFullAISegmentation = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_BREAST_CANCER_PETCT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_BREAST_CANCER_PETCT_PERCENT_Y/2) ...
                                        DLG_BREAST_CANCER_PETCT_PERCENT_X ...
                                        DLG_BREAST_CANCER_PETCT_PERCENT_Y ...
                                        ],...
                           'MenuBar', 'none',...
                           'Resize', 'off', ...    
                           'NumberTitle','off',...
                           'MenuBar', 'none',...
                           'Color', viewerBackgroundColor('get'), ...
                           'Name', 'Metastatic Breast Cancer Machine Learning Full AI PET CT Segmentation',...
                           'Toolbar','none'...               
                           );    
            end

            % Trainer with Dice and CE Loss
        
                uicontrol(dlgBreastCancerPETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Trainer with Dice and CE Loss, no smoothing',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkBreastCancerPETCTFullAICELossCallback, ...
                          'position', [40 165 250 20]...
                          );
        
            chkBreastCancerPETCTFullAICELoss = ...
                uicontrol(dlgBreastCancerPETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningBreastCancerCELoss('get'),...
                          'position', [20 165 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkBreastCancerPETCTFullAICELossCallback...
                          );

            % Classify Segmentation
        
                uicontrol(dlgBreastCancerPETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Classify the Segmentation',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkBreastCancerPETCTFullAIClassifySegmentationCallback, ...
                          'position', [40 140 250 20]...
                          );
        
            chkBreastCancerPETCTFullAIClassifySegmentation = ...
                uicontrol(dlgBreastCancerPETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningBreastCancerClassifySegmentation('get'),...
                          'position', [20 140 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkBreastCancerPETCTFullAIClassifySegmentationCallback...
                          );

            % Smooth mask

                uicontrol(dlgBreastCancerPETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Smooth Mask',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'ButtonDownFcn'  , @chkBreastCancerPETCTFullAISmoothMaskCallback, ...
                          'position', [40 115 150 20]...
                          );

            chkBreastCancerPETCTFullAISmoothMask = ...
                uicontrol(dlgBreastCancerPETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningBreastCancerSmoothMask('get'),...
                          'position', [20 115 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'Callback', @chkBreastCancerPETCTFullAISmoothMaskCallback...
                          );
             % Pixel Edge
        
                uicontrol(dlgBreastCancerPETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Pixel Edge',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkBreastCancerPETCTFullAIPixelEdgeCallback, ...
                          'position', [40 90 150 20]...
                          );
        
            chkBreastCancerPETCTFullAIPixelEdge = ...
                uicontrol(dlgBreastCancerPETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , pixelEdge('get'),...
                          'position', [20 90 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkBreastCancerPETCTFullAIPixelEdgeCallback...
                          );

            % Smallest Contour (ml)
        
                uicontrol(dlgBreastCancerPETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'Smallest Contour (ml)',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 65 250 20]...
                          );
        
            edtBreastCancerPETCTFullAISmallestVoiValue = ...
                uicontrol(dlgBreastCancerPETCTFullAISegmentation, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 65 75 20], ...
                          'String'  , num2str(machineLearningBreastCancerSmallestVoiValue('get')), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtBreastCancerPETCTFullAISmallestVoiValueCallback ...
                          );  
        
             % Cancel or Proceed
        
             uicontrol(dlgBreastCancerPETCTFullAISegmentation,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelBreastCancerPETCTFullAISegmentationCallback...
                       );
        
             uicontrol(dlgBreastCancerPETCTFullAISegmentation,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedBreastCancerPETCTFullAISegmentationCallback...
                      );               
        else

            % Options

            tBreastCancerPETCTFullAI.options.CELossTrainer        = machineLearningBreastCancerCELoss('get');
            tBreastCancerPETCTFullAI.options.classifySegmentation = machineLearningBreastCancerClassifySegmentation('get');
            tBreastCancerPETCTFullAI.options.smoothMask           = machineLearningBreastCancerSmoothMask('get');
            tBreastCancerPETCTFullAI.options.smallestVoiValue     = machineLearningBreastCancerSmallestVoiValue('get');
            tBreastCancerPETCTFullAI.options.pixelEdge            = pixelEdge('get');
    
            setMachineLearningBreastCancerPETCTFullAI(sPredictScript, tBreastCancerPETCTFullAI); 
        end
    end

    function chkBreastCancerPETCTFullAICELossCallback(hObject, ~)

        bObjectValue = get(chkBreastCancerPETCTFullAICELoss, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkBreastCancerPETCTFullAICELoss, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkBreastCancerPETCTFullAICELoss, 'Value');

        machineLearningBreastCancerCELoss('set', bObjectValue);
    end

    function chkBreastCancerPETCTFullAIClassifySegmentationCallback(hObject, ~)

        bObjectValue = get(chkBreastCancerPETCTFullAIClassifySegmentation, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkBreastCancerPETCTFullAIClassifySegmentation, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkBreastCancerPETCTFullAIClassifySegmentation, 'Value');

        machineLearningBreastCancerClassifySegmentation('set', bObjectValue);
    end

    function chkBreastCancerPETCTFullAISmoothMaskCallback(hObject, ~)

        bObjectValue = get(chkBreastCancerPETCTFullAISmoothMask, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkBreastCancerPETCTFullAISmoothMask, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkBreastCancerPETCTFullAISmoothMask, 'Value');

        machineLearningBreastCancerSmoothMask('set', bObjectValue);
    end

    function edtBreastCancerPETCTFullAISmallestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtBreastCancerPETCTFullAISmallestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtBreastCancerPETCTFullAISmallestVoiValue, 'String', num2str(dObjectValue));
        end

        machineLearningBreastCancerSmallestVoiValue('set', dObjectValue);

    end

    function chkBreastCancerPETCTFullAIPixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkBreastCancerPETCTFullAIPixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBreastCancerPETCTFullAIPixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBreastCancerPETCTFullAIPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox

        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end

    function cancelBreastCancerPETCTFullAISegmentationCallback(~, ~)   

        delete(dlgBreastCancerPETCTFullAISegmentation);
    end
    
    function proceedBreastCancerPETCTFullAISegmentationCallback(~, ~)

        % Options

        tBreastCancerPETCTFullAI.options.CELossTrainer        =            get(chkBreastCancerPETCTFullAICELoss, 'Value');
        tBreastCancerPETCTFullAI.options.classifySegmentation =            get(chkBreastCancerPETCTFullAIClassifySegmentation, 'Value');
        tBreastCancerPETCTFullAI.options.smoothMask           =            get(chkBreastCancerPETCTFullAISmoothMask, 'Value');
        tBreastCancerPETCTFullAI.options.smallestVoiValue     = str2double(get(edtBreastCancerPETCTFullAISmallestVoiValue , 'String'));

        delete(dlgBreastCancerPETCTFullAISegmentation);

        setMachineLearningBreastCancerPETCTFullAI(sPredictScript, tBreastCancerPETCTFullAI); 
    end

end