function setMantleCellLymphomaSegmentationCallack(hObject, ~)
%function setMantleCellLymphomaSegmentationCallack(hObject)
%Run Mantle Cell Lymphoma Tumor Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2024, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    [sSegmentatorScript, ~] = validateSegmentatorInstallation();

    dlgMachineLearningMantleCellLymphoma  = [];
  
    if ~isempty(sSegmentatorScript) % External Segmentor is installed

        if exist('hObject', 'var')

            DLG_MantleCellLymphoma_PERCENT_X = 380;
            DLG_MantleCellLymphoma_PERCENT_Y = 540;

             if viewerUIFigure('get') == true
        
                dlgMachineLearningMantleCellLymphoma = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_MantleCellLymphoma_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_MantleCellLymphoma_PERCENT_Y/2) ...
                                        DLG_MantleCellLymphoma_PERCENT_X ...
                                        DLG_MantleCellLymphoma_PERCENT_Y ...
                                        ],...
                           'Resize', 'off', ...
                           'Color', viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name' , 'Mantle Cell Lymphoma Segmentation'...
                           );
            else          
                dlgMachineLearningMantleCellLymphoma = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_MantleCellLymphoma_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_MantleCellLymphoma_PERCENT_Y/2) ...
                                        DLG_MantleCellLymphoma_PERCENT_X ...
                                        DLG_MantleCellLymphoma_PERCENT_Y ...
                                        ],...
                           'MenuBar', 'none',...
                           'Resize', 'off', ...    
                           'NumberTitle','off',...
                           'MenuBar', 'none',...
                           'Color', viewerBackgroundColor('get'), ...
                           'Name', 'Mantle Cell Lymphoma Segmentation',...
                           'Toolbar','none'...               
                           );    
             end

            setObjectIcon(dlgMachineLearningMantleCellLymphoma);

            % Exclude organs from AI analysis
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'FontWeight','bold'  ,...
                      'string'  , 'Exclude organs from AI analysis',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 490 300 20]...
                      );
        % Skeleton
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Skeleton',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkMantleCellLymphomaSkeletonCallback, ...
                      'position', [60 465 150 20]...
                      );
    
        chkMantleCellLymphomaSkeleton = ...
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeMantleCellLymphomaSkeleton('get'),...
                      'position', [40 465 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkMantleCellLymphomaSkeletonCallback...
                      );

        % Cardiovascular
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Cardiovascular',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkMantleCellLymphomaCardiovascularCallback, ...
                      'position', [60 440 150 20]...
                      );
    
        chkMantleCellLymphomaCardiovascular = ...
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeMantleCellLymphomaCardiovascular('get'),...
                      'position', [40 440 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkMantleCellLymphomaCardiovascularCallback...
                      );

        % Brain
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Brain',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkMantleCellLymphomaBrainCallback, ...
                      'position', [60 415 150 20]...
                      );
    
        chkMantleCellLymphomaBrain = ...
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeMantleCellLymphomaBrain('get'),...
                      'position', [40 415 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkMantleCellLymphomaBrainCallback...
                      );

         % Spinal Cord
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Spinal Cord',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkMantleCellLymphomaSpinalCordCallback, ...
                      'position', [60 390 150 20]...
                      );
    
        chkMantleCellLymphomaSpinalCord = ...
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeMantleCellLymphomaSpinalCord('get'),...
                      'position', [40 390 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkMantleCellLymphomaSpinalCordCallback...
                      );

         % Adrenal Gland Left
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Adrenal Gland Left',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkMantleCellLymphomaAdrenalGlandLeftCallback, ...
                      'position', [60 365 150 20]...
                      );
    
        chkMantleCellLymphomaAdrenalGlandLeft = ...
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeMantleCellLymphomaAdrenalGlandLeft('get'),...
                      'position', [40 365 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkMantleCellLymphomaAdrenalGlandLeftCallback...
                      );

         % Adrenal Gland Right
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Adrenal Gland Right',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkMantleCellLymphomaAdrenalGlandRightCallback, ...
                      'position', [60 340 150 20]...
                      );
    
        chkMantleCellLymphomaAdrenalGlandRight = ...
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeMantleCellLymphomaAdrenalGlandRight('get'),...
                      'position', [40 340 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkMantleCellLymphomaAdrenalGlandRightCallback...
                      );
        % Spleen
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Spleen',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkMantleCellLymphomaSpleenCallback, ...
                      'position', [60 315 150 20]...
                      );
    
        chkMantleCellLymphomaSpleen = ...
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeMantleCellLymphomaSpleen('get'),...
                      'position', [40 315 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkMantleCellLymphomaSpleenCallback...
                      );

         % Gallbladder
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Gallbladder',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkMantleCellLymphomaGallbladderCallback, ...
                      'position', [60 290 150 20]...
                      );
    
        chkMantleCellLymphomaGallbladder = ...
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeMantleCellLymphomaGallbladder('get'),...
                      'position', [40 290 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkMantleCellLymphomaGallbladderCallback...
                      );

        % Kidney left
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Kidney left',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkMantleCellLymphomaKidneyLeftCallback, ...
                      'position', [60 265 150 20]...
                      );
    
        chkMantleCellLymphomaKidneyLeft = ...
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeMantleCellLymphomaKidneyLeft('get'),...
                      'position', [40 265 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkMantleCellLymphomaKidneyLeftCallback...
                      );
    
        % Kidney right
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Kidney right',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkMantleCellLymphomaKidneyRightCallback, ...
                      'position', [60 240 150 20]...
                      );
    
        chkMantleCellLymphomaKidneyRight = ...
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeMantleCellLymphomaKidneyRight('get'),...
                      'position', [40 240 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkMantleCellLymphomaKidneyRightCallback...
                      );
        
        % Prostate
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Prostate',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkMantleCellLymphomaProstateCallback, ...
                      'position', [60 215 150 20]...
                      );
    
        chkMantleCellLymphomaProstate = ...
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeMantleCellLymphomaProstate('get'),...
                      'position', [40 215 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkMantleCellLymphomaProstateCallback...
                      );
    
        % Gastrointestal Tract
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Gastrointestal Tract',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkMantleCellLymphomaGastrointestalTractCallback, ...
                      'position', [60 190 150 20]...
                      );
    
        chkMantleCellLymphomaGastrointestalTract = ...
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeMantleCellLymphomaGastrointestalTract('get'),...
                      'position', [40 190 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkMantleCellLymphomaGastrointestalTractCallback...
                      );
        % Options
    
            uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'style'     , 'text',...
                      'FontWeight','bold'  ,...
                      'string'    , 'Options',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 140 300 20]...
                      );    
    
             % Pixel Edge
        
                uicontrol(dlgMachineLearningMantleCellLymphoma,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Pixel Edge',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkMantleCellLymphomaPixelEdgeCallback, ...
                          'position', [40 115 150 20]...
                          );
        
            chkMantleCellLymphomaPixelEdge = ...
                uicontrol(dlgMachineLearningMantleCellLymphoma,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , pixelEdge('get'),...
                          'position', [20 115 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkMantleCellLymphomaPixelEdgeCallback...
                          );

            % Percent of liver max
        
                uicontrol(dlgMachineLearningMantleCellLymphoma,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'Percent of liver max',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 90 250 20]...
                          );
        
            edtMantleCellLymphomaPercentOfLiverMax = ...
                uicontrol(dlgMachineLearningMantleCellLymphoma, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 90 75 20], ...
                          'String'  , num2str(mantleCellLymphomaPercentOfLiverMax('get')), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtMantleCellLymphomaPercentOfLiverMaxCallback ...
                          );  

            % Smallest Contour (ml)
        
                uicontrol(dlgMachineLearningMantleCellLymphoma,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'Smallest Contour (ml)',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 65 250 20]...
                          );
        
            edtMantleCellLymphomaSmalestVoiValue = ...
                uicontrol(dlgMachineLearningMantleCellLymphoma, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 65 75 20], ...
                          'String'  , num2str(mantleCellLymphomaSmalestVoiValue('get')), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtMantleCellLymphomaSmalestVoiValueCallback ...
                          );  
        
             % Cancel or Proceed
        
             uicontrol(dlgMachineLearningMantleCellLymphoma,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelMachineLearningMantleCellLymphomaCallback...
                       );
        
             uicontrol(dlgMachineLearningMantleCellLymphoma,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedMachineLearningMantleCellLymphomaCallback...
                      );  
        else
            % Exclude List

            tMantleCellLymphoma.exclude.skeleton.all            = excludeMantleCellLymphomaSkeleton('get');
            tMantleCellLymphoma.exclude.cardiovascular.all      = excludeMantleCellLymphomaCardiovascular('get');
            tMantleCellLymphoma.exclude.organ.brain             = excludeMantleCellLymphomaBrain('get');
            tMantleCellLymphoma.exclude.organ.spinalCord        = excludeMantleCellLymphomaSpinalCord('get');
            tMantleCellLymphoma.exclude.organ.adrenalGlandLeft  = excludeMantleCellLymphomaAdrenalGlandLeft('get');
            tMantleCellLymphoma.exclude.organ.adrenalGlandRight = excludeMantleCellLymphomaAdrenalGlandRight('get');
            tMantleCellLymphoma.exclude.organ.spleen            = excludeMantleCellLymphomaSpleen('get');
            tMantleCellLymphoma.exclude.organ.gallbladder       = excludeMantleCellLymphomaGallbladder('get');
            tMantleCellLymphoma.exclude.organ.kidneyLeft        = excludeMantleCellLymphomaKidneyLeft('get');
            tMantleCellLymphoma.exclude.organ.kidneyRight       = excludeMantleCellLymphomaKidneyRight('get');
            tMantleCellLymphoma.exclude.organ.prostate          = excludeMantleCellLymphomaProstate('get');
            tMantleCellLymphoma.exclude.gastrointestalTract.all = excludeMantleCellLymphomaGastrointestalTract('get');
     
            % Options
    
            tMantleCellLymphoma.options.percentOfLiverMax = mantleCellLymphomaPercentOfLiverMax('get');
            tMantleCellLymphoma.options.smalestVoiValue   = mantleCellLymphomaSmalestVoiValue('get');
            tMantleCellLymphoma.options.pixelEdge         = pixelEdge('get');
        
            setMantleCellLymphomaSegmentation(sSegmentatorScript, tMantleCellLymphoma);        
        end
    end

    % Exclude organs from AI analysis


    % Skeleton

    function chkMantleCellLymphomaSkeletonCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaSkeleton, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaSkeleton, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaSkeleton, 'Value');

        excludeMantleCellLymphomaSkeleton('set', bObjectValue);

    end

    % Cardiovascular

    function chkMantleCellLymphomaCardiovascularCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaCardiovascular, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaCardiovascular, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaCardiovascular, 'Value');

        excludeMantleCellLymphomaCardiovascular('set', bObjectValue);

    end

    % Brain

    function chkMantleCellLymphomaBrainCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaBrain, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaBrain, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaBrain, 'Value');

        excludeMantleCellLymphomaBrain('set', bObjectValue);

    end

    % Spinal Cord

    function chkMantleCellLymphomaSpinalCordCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaSpinalCord, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaSpinalCord, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaSpinalCord, 'Value');

        excludeMantleCellLymphomaSpinalCord('set', bObjectValue);

    end

    % Gallbladder

    function chkMantleCellLymphomaGallbladderCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaGallbladder, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaGallbladder, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaGallbladder, 'Value');

        excludeMantleCellLymphomaGallbladder('set', bObjectValue);

    end

    % Kidney Left

    function chkMantleCellLymphomaKidneyLeftCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaKidneyLeft, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaKidneyLeft, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaKidneyLeft, 'Value');

        excludeMantleCellLymphomaKidneyLeft('set', bObjectValue);

    end

    % Kidney Right

    function chkMantleCellLymphomaKidneyRightCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaKidneyRight, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaKidneyRight, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaKidneyRight, 'Value');

        excludeMantleCellLymphomaKidneyRight('set', bObjectValue);

    end

    % Adrenal Gland Left

    function chkMantleCellLymphomaAdrenalGlandLeftCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaAdrenalGlandLeft, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaAdrenalGlandLeft, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaAdrenalGlandLeft, 'Value');

        excludeMantleCellLymphomaAdrenalGlandLeft('set', bObjectValue);

    end

    % Adrenal Gland Right

    function chkMantleCellLymphomaAdrenalGlandRightCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaAdrenalGlandRight, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaAdrenalGlandRight, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaAdrenalGlandRight, 'Value');

        excludeMantleCellLymphomaAdrenalGlandRight('set', bObjectValue);

    end

    % Spleen

    function chkMantleCellLymphomaSpleenCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaSpleen, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaSpleen, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaSpleen, 'Value');

        excludeMantleCellLymphomaSpleen('set', bObjectValue);

    end

    % Prostate

    function chkMantleCellLymphomaProstateCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaProstate, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaProstate, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaProstate, 'Value');

        excludeMantleCellLymphomaProstate('set', bObjectValue);

    end

    % GastrointestalTract

    function chkMantleCellLymphomaGastrointestalTractCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaGastrointestalTract, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaGastrointestalTract, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaGastrointestalTract, 'Value');

        excludeMantleCellLymphomaGastrointestalTract('set', bObjectValue);

    end

    function edtMantleCellLymphomaPercentOfLiverMaxCallback(~, ~)

        dObjectValue = str2double(get(edtMantleCellLymphomaPercentOfLiverMax, 'String'));

        if dObjectValue < 0

            dObjectValue = 1;

            set(edtMantleCellLymphomaPercentOfLiverMax, 'String', num2str(dObjectValue));
        end

        mantleCellLymphomaPercentOfLiverMax('set', dObjectValue);

    end

    function edtMantleCellLymphomaSmalestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtMantleCellLymphomaSmalestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtMantleCellLymphomaSmalestVoiValue, 'String', num2str(dObjectValue));
        end

        mantleCellLymphomaSmalestVoiValue('set', dObjectValue);

    end

    function chkMantleCellLymphomaPixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkMantleCellLymphomaPixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkMantleCellLymphomaPixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkMantleCellLymphomaPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox

        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end


    function cancelMachineLearningMantleCellLymphomaCallback(~, ~)   

        delete(dlgMachineLearningMantleCellLymphoma);
    end
    
    function proceedMachineLearningMantleCellLymphomaCallback(~, ~)

        % Exclude List

        tMantleCellLymphoma.exclude.skeleton.all            = get(chkMantleCellLymphomaSkeleton           , 'value');
        tMantleCellLymphoma.exclude.cardiovascular.all      = get(chkMantleCellLymphomaCardiovascular     , 'value');
        tMantleCellLymphoma.exclude.organ.brain             = get(chkMantleCellLymphomaBrain              , 'value');
        tMantleCellLymphoma.exclude.organ.spinalCord        = get(chkMantleCellLymphomaSpinalCord         , 'value');
        tMantleCellLymphoma.exclude.organ.adrenalGlandLeft  = get(chkMantleCellLymphomaAdrenalGlandLeft   , 'value');
        tMantleCellLymphoma.exclude.organ.adrenalGlandRight = get(chkMantleCellLymphomaAdrenalGlandRight  , 'value');
        tMantleCellLymphoma.exclude.organ.spleen            = get(chkMantleCellLymphomaSpleen             , 'value');
        tMantleCellLymphoma.exclude.organ.gallbladder       = get(chkMantleCellLymphomaGallbladder        , 'value');
        tMantleCellLymphoma.exclude.organ.kidneyLeft        = get(chkMantleCellLymphomaKidneyLeft         , 'value');
        tMantleCellLymphoma.exclude.organ.kidneyRight       = get(chkMantleCellLymphomaKidneyRight        , 'value');
        tMantleCellLymphoma.exclude.organ.prostate          = get(chkMantleCellLymphomaProstate           , 'value');
        tMantleCellLymphoma.exclude.gastrointestalTract.all = get(chkMantleCellLymphomaGastrointestalTract, 'value');

        % Options

        tMantleCellLymphoma.options.percentOfLiverMax = str2double(get(edtMantleCellLymphomaPercentOfLiverMax, 'String'));
        tMantleCellLymphoma.options.smalestVoiValue   = str2double(get(edtMantleCellLymphomaSmalestVoiValue  , 'String'));
        tMantleCellLymphoma.options.pixelEdge         = get(chkMantleCellLymphomaPixelEdge                   , 'value');

        delete(dlgMachineLearningMantleCellLymphoma);

        setMantleCellLymphomaSegmentation(sSegmentatorScript, tMantleCellLymphoma); 
    end

end