function setMachineLearningFullAIGa68DOTATATECallback(hObject, ~)
%function setMachineLearningFullAIGa68DOTATATECallback()
%Run machine learning full AI Ga68 DOTATATE Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2023, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    [sSegmentatorScript, ~] = validateSegmentatorInstallation();

    sOnnxPath = validateOnnxInstallation();

    if ~isempty(sSegmentatorScript) && ... % External Segmentor is installed
       ~isempty(sOnnxPath)

        if exist('hObject', 'var')

            DLG_Ga68DOTATATE_X = 380;
            DLG_Ga68DOTATATE_Y = 715;

            if viewerUIFigure('get') == true

                dlgFullAIGa68DOTATATE = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_Ga68DOTATATE_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_Ga68DOTATATE_Y/2) ...
                                        DLG_Ga68DOTATATE_X ...
                                        DLG_Ga68DOTATATE_Y ...
                                        ],...
                           'Resize', 'off', ...
                           'Color', viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name' , 'Full AI Ga68 DOTATATE Segmentation'...
                           );
            else
                dlgFullAIGa68DOTATATE = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_Ga68DOTATATE_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_Ga68DOTATATE_Y/2) ...
                                        DLG_Ga68DOTATATE_X ...
                                        DLG_Ga68DOTATATE_Y ...
                                        ],...
                           'MenuBar', 'none',...
                           'Resize', 'off', ...
                           'NumberTitle','off',...
                           'MenuBar', 'none',...
                           'Color', viewerBackgroundColor('get'), ...
                           'Name', 'Full AI Ga68 DOTATATE Segmentation',...
                           'Toolbar','none'...
                           );
            end

            axeFullAIGa68DOTATATE = ...
                axes(dlgFullAIGa68DOTATATE, ...
                     'Units'   , 'pixels', ...
                     'Position', [0 0 DLG_Ga68DOTATATE_X DLG_Ga68DOTATATE_Y], ...
                     'Color'   , viewerBackgroundColor('get'),...
                     'XColor'  , viewerForegroundColor('get'),...
                     'YColor'  , viewerForegroundColor('get'),...
                     'ZColor'  , viewerForegroundColor('get'),...
                     'Visible' , 'off'...
                     );
            axeFullAIGa68DOTATATE.Interactions = [zoomInteraction regionZoomInteraction rulerPanInteraction];
            axeFullAIGa68DOTATATE.Toolbar.Visible = 'off';
            disableDefaultInteractivity(axeFullAIGa68DOTATATE);

            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Trained Model',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'position', [20 665 150 20]...
                      );

        uiFullAIGa68DOTATATETrainedModel = ...
             uicontrol(dlgFullAIGa68DOTATATE, ...
                      'Style'   , 'popup', ...
                      'Position', [210 665 150 25], ...
                      'String'  , {'Model 1', 'Model 2'}, ...
                      'Value'   , Ga68DOTATATEFullAITrainedModel('get'),...
                      'Enable'  , 'on', ...
                      'Callback', @uiFullAIGa68DOTATATETrainedModelCallback, ...
                      'BackgroundColor', viewerBackgroundColor ('get'), ...
                      'ForegroundColor', viewerForegroundColor('get') ...
                      );
        % Options

            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'FontWeight','bold'  ,...
                      'string'  , 'Options',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'position', [20 615 300 20]...
                      );

        % Smallest Contour (ml)

            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Smallest Contour (ml)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'position', [20 590 250 20]...
                      );

        edtFullAIGa68DOTATATESmalestVoiValue = ...
            uicontrol(dlgFullAIGa68DOTATATE, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 590 75 20], ...
                      'String'  , num2str(Ga68DOTATATEFullAISmalestVoiValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtFullAIGa68DOTATATESmalestVoiValueCallback ...
                      );
        % Pixel Edge

            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Pixel Edge',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEPixelEdgeCallback, ...
                      'position', [40 565 150 20]...
                      );

        chkFullAIGa68DOTATATEPixelEdge = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , pixelEdge('get'),...
                      'position', [20 565 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEPixelEdgeCallback...
                      );
        % Smooth mask

            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Smooth Mask',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATESmoothMaskCallback, ...
                      'position', [40 540 150 20]...
                      );

        chkFullAIGa68DOTATATESmoothMask = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , Ga68DOTATATEFullAISmoothMask('get'),...
                      'position', [20 540 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATESmoothMaskCallback...
                      );

        % Lesion Classification

            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Lesion Classification',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATELesionClassificationCallback, ...
                      'position', [40 515 150 20]...
                      );

        chkFullAIGa68DOTATATELesionClassification = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , Ga68DOTATATEFullAILesionClassification('get'),...
                      'position', [20 515 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATELesionClassificationCallback...
                      );

        % Enhanced Bone Mask Lesion

        if Ga68DOTATATEFullAILesionClassification('get') == true
            sClassificationTxtEnable = 'Inactive';
            sClassificationChkEnable = 'on';
        else
            sClassificationTxtEnable = 'on';
            sClassificationChkEnable = 'off';
        end

        txtFullAIGa68DOTATATEEnhancedBoneMaskLesion = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Enhanced Bone Mask Lesion',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEEnhancedBoneMaskLesionCallback, ...
                      'position', [60 490 150 20]...
                      );

        chkFullAIGa68DOTATATEEnhancedBoneMaskLesion = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , Ga68DOTATATEFullAIEnhancedBoneMaskLesion('get'),...
                      'position', [40 490 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEEnhancedBoneMaskLesionCallback...
                      );

        % Other Organs

            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'FontWeight','bold'  ,...
                      'string'  , 'Exclude organ list',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'position', [40 465 300 20]...
                      );

        % Brain

        txtFullAIGa68DOTATATEBrain = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Brain',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEBrainCallback, ...
                      'position', [80 440 150 20]...
                      );

        chkFullAIGa68DOTATATEBrain = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATEBrain('get'),...
                      'position', [60 440 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEBrainCallback...
                      );

        % Trachea

        txtFullAIGa68DOTATATETrachea = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Trachea',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATETracheaCallback, ...
                      'position', [80 415 150 20]...
                      );

        chkFullAIGa68DOTATATETrachea = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATETrachea('get'),...
                      'position', [60 415 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATETracheaCallback...
                      );

        % Adrenal gland left

        txtFullAIGa68DOTATATEAdrenalGlandLeft = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Adrenal gland left',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEAdrenalGlandLeftCallback, ...
                      'position', [80 390 150 20]...
                      );

        chkFullAIGa68DOTATATEAdrenalGlandLeft = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATEAdrenalGlandLeft('get'),...
                      'position', [60 390 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEAdrenalGlandLeftCallback...
                      );

        % Adrenal gland right

        txtFullAIGa68DOTATATEAdrenalGlandRight = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Adrenal gland right',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEAdrenalGlandRightCallback, ...
                      'position', [80 365 150 20]...
                      );

        chkFullAIGa68DOTATATEAdrenalGlandRight = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATEAdrenalGlandRight('get'),...
                      'position', [60 365 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEAdrenalGlandRightCallback...
                      );

        % Spleen

        txtFullAIGa68DOTATATESpleen = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Spleen',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATESpleenCallback, ...
                      'position', [80 340 150 20]...
                      );

        chkFullAIGa68DOTATATESpleen = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATESpleen('get'),...
                      'position', [60 340 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATESpleenCallback...
                      );

        % Gallbladder

        txtFullAIGa68DOTATATEGallbladder = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Gallbladder',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEGallbladderCallback, ...
                      'position', [80 315 150 20]...
                      );

        chkFullAIGa68DOTATATEGallbladder = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATEGallbladder('get'),...
                      'position', [60 315 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEGallbladderCallback...
                      );

        % Pancreas

        txtFullAIGa68DOTATATEPancreas = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Pancreas',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEPancreasCallback, ...
                      'position', [80 290 150 20]...
                      );

        chkFullAIGa68DOTATATEPancreas = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATEPancreas('get'),...
                      'position', [60 290 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEPancreasCallback...
                      );

        % Kidney left

        txtFullAIGa68DOTATATEKidneyLeft = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Kidney left',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEKidneyLeftCallback, ...
                      'position', [80 265 150 20]...
                      );

        chkFullAIGa68DOTATATEKidneyLeft = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATEKidneyLeft('get'),...
                      'position', [60 265 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEKidneyLeftCallback...
                      );

        % Kidney right

        txtFullAIGa68DOTATATEKidneyRight = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Kidney right',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEKidneyRightCallback, ...
                      'position', [80 240 150 20]...
                      );

        chkFullAIGa68DOTATATEKidneyRight = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATEKidneyRight('get'),...
                      'position', [60 240 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEKidneyRightCallback...
                      );

        % Gastrointestinal Tract Name

            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'FontWeight','bold'  ,...
                      'string'  , 'Exclude gastrointestinal tract list',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'position', [40 215 300 20]...
                      );
        % Esophagus

        txtFullAIGa68DOTATATEEsophagus = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Esophagus',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEEsophagusCallback, ...
                      'position', [80 190 150 20]...
                      );

        chkFullAIGa68DOTATATEEsophagus = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATEEsophagus('get'),...
                      'position', [60 190 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEEsophagusCallback...
                      );

        % Stomach

        txtFullAIGa68DOTATATEStomach = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Stomach',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEStomachCallback, ...
                      'position', [80 165 150 20]...
                      );

        chkFullAIGa68DOTATATEStomach = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATEStomach('get'),...
                      'position', [60 165 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEStomachCallback...
                      );

        % Duodenum

        txtFullAIGa68DOTATATEDuodenum = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Duodenum',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEDuodenumCallback, ...
                      'position', [80 140 150 20]...
                      );

        chkFullAIGa68DOTATATEDuodenum = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATEDuodenum('get'),...
                      'position', [60 140 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEDuodenumCallback...
                      );

        % Small bowel

        txtFullAIGa68DOTATATESmallBowel = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Small bowel',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATESmallBowelCallback, ...
                      'position', [80 115 150 20]...
                      );

        chkFullAIGa68DOTATATESmallBowel = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATESmallBowel('get'),...
                      'position', [60 115 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATESmallBowelCallback...
                      );

        % Colon

        txtFullAIGa68DOTATATEColon = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Colon',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEColonCallback, ...
                      'position', [80 90 150 20]...
                      );

        chkFullAIGa68DOTATATEColon = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATEColon('get'),...
                      'position', [60 90 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEColonCallback...
                      );

        % Urinary bladder

        txtFullAIGa68DOTATATEUrinaryBladder = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , sClassificationTxtEnable,...
                      'string'  , 'Urinary bladder',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'ButtonDownFcn'  , @chkFullAIGa68DOTATATEUrinaryBladderCallback, ...
                      'position', [80 65 150 20]...
                      );

        chkFullAIGa68DOTATATEUrinaryBladder = ...
            uicontrol(dlgFullAIGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , sClassificationChkEnable,...
                      'value'   , excludeGa68DOTATATEUrinaryBladder('get'),...
                      'position', [60 65 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @chkFullAIGa68DOTATATEUrinaryBladderCallback...
                      );

        % Cancel or Proceed

             uicontrol(dlgFullAIGa68DOTATATE,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...
                       'Callback', @cancelFullAiGa68DOTATATECallback...
                       );

             uicontrol(dlgFullAIGa68DOTATATE,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'Callback', @proceedFullAiGa68DOTATATECallback...
                      );
        else

            dTrainedModel = get(uiFullAIGa68DOTATATETrainedModel, 'Value');

            tGa68DOTATATE.classification.enable                 = Ga68DOTATATEFullAITrainedModel('get');
            tGa68DOTATATE.classification.enhancedBoneMaskLesion = Ga68DOTATATEFullAIEnhancedBoneMaskLesion('get');

            % Other Organs

            tGa68DOTATATE.exclude.organ.brain             = excludeGa68DOTATATEBrain('get');
            tGa68DOTATATE.exclude.organ.trachea           = excludeGa68DOTATATETrachea('get');
            tGa68DOTATATE.exclude.organ.adrenalGlandLeft  = excludeGa68DOTATATEAdrenalGlandLeft('get');
            tGa68DOTATATE.exclude.organ.adrenalGlandRight = excludeGa68DOTATATEAdrenalGlandRight('get');
            tGa68DOTATATE.exclude.organ.spleen            = excludeGa68DOTATATESpleen('get');
            tGa68DOTATATE.exclude.organ.gallbladder       = excludeGa68DOTATATEGallbladder('get');
            tGa68DOTATATE.exclude.organ.pancreas          = excludeGa68DOTATATEPancreas('get');
            tGa68DOTATATE.exclude.organ.kidneyLeft        = excludeGa68DOTATATEKidneyLeft('get');
            tGa68DOTATATE.exclude.organ.kidneyRight       = gexcludeGa68DOTATATEKidneyRight('get');

            % Gastrointestinal Tract Name

            tGa68DOTATATE.exclude.gastrointestinal.urinaryBladder = excludeGa68DOTATATEUrinaryBladder('get');
            tGa68DOTATATE.exclude.gastrointestinal.esophagus      = excludeGa68DOTATATEEsophagus('get');
            tGa68DOTATATE.exclude.gastrointestinal.stomach        = excludeGa68DOTATATEStomach('get');
            tGa68DOTATATE.exclude.gastrointestinal.duodenum       = excludeGa68DOTATATEDuodenum('get');
            tGa68DOTATATE.exclude.gastrointestinal.smallBowel     = excludeGa68DOTATATESmallBowel('get');
            tGa68DOTATATE.exclude.gastrointestinal.colon          = excludeGa68DOTATATEColon('get');

            tGa68DOTATATE.options.smalestVoiValue = Ga68DOTATATEFullAISmalestVoiValue('get');
            tGa68DOTATATE.options.pixelEdge       = pixelEdge('get');
            tGa68DOTATATE.options.smoothMask      = Ga68DOTATATEFullAISmoothMask('get');

            setMachineLearningFullAIGa68DOTATATE(sSegmentatorScript, sOnnxPath, dTrainedModel, tGa68DOTATATE);
        end
    end

    function uiFullAIGa68DOTATATETrainedModelCallback(hObject, ~)

        Ga68DOTATATEFullAITrainedModel('set', get(hObject, 'Value'));
    end

    function edtFullAIGa68DOTATATESmalestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtFullAIGa68DOTATATESmalestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtFullAIGa68DOTATATESmalestVoiValue, 'String', num2str(dObjectValue));
        end

        Ga68DOTATATEFullAISmalestVoiValue('set', dObjectValue);

    end

    function chkFullAIGa68DOTATATELesionClassificationCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATELesionClassification, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATELesionClassification, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATELesionClassification, 'Value');

        Ga68DOTATATEFullAILesionClassification('set', bObjectValue);

        if bObjectValue == true

            set(txtFullAIGa68DOTATATEEnhancedBoneMaskLesion, 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEEnhancedBoneMaskLesion, 'Enable', 'On');

            set(txtFullAIGa68DOTATATEBrain            , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEBrain            , 'Enable', 'On');
            set(txtFullAIGa68DOTATATETrachea          , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATETrachea          , 'Enable', 'On');
            set(txtFullAIGa68DOTATATEAdrenalGlandLeft , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEAdrenalGlandLeft , 'Enable', 'On');
            set(txtFullAIGa68DOTATATEAdrenalGlandRight, 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEAdrenalGlandRight, 'Enable', 'On');
            set(txtFullAIGa68DOTATATESpleen           , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATESpleen           , 'Enable', 'On');
            set(txtFullAIGa68DOTATATEGallbladder      , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEGallbladder      , 'Enable', 'On');
            set(txtFullAIGa68DOTATATEPancreas         , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEPancreas         , 'Enable', 'On');
            set(txtFullAIGa68DOTATATEKidneyLeft       , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEKidneyLeft       , 'Enable', 'On');
            set(txtFullAIGa68DOTATATEKidneyRight      , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEKidneyRight      , 'Enable', 'On');
            set(txtFullAIGa68DOTATATEEsophagus        , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEEsophagus        , 'Enable', 'On');
            set(txtFullAIGa68DOTATATEStomach          , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEStomach          , 'Enable', 'On');
            set(txtFullAIGa68DOTATATEDuodenum         , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEDuodenum         , 'Enable', 'On');
            set(txtFullAIGa68DOTATATESmallBowel       , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATESmallBowel       , 'Enable', 'On');
            set(txtFullAIGa68DOTATATEColon            , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEColon            , 'Enable', 'On');
            set(txtFullAIGa68DOTATATEUrinaryBladder   , 'Enable', 'Inactive');
            set(chkFullAIGa68DOTATATEUrinaryBladder   , 'Enable', 'On');
        else
            set(txtFullAIGa68DOTATATEEnhancedBoneMaskLesion, 'Enable', 'On');
            set(chkFullAIGa68DOTATATEEnhancedBoneMaskLesion, 'Enable', 'Off');

            set(txtFullAIGa68DOTATATEBrain            , 'Enable', 'On');
            set(chkFullAIGa68DOTATATEBrain            , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATETrachea          , 'Enable', 'On');
            set(chkFullAIGa68DOTATATETrachea          , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATEAdrenalGlandLeft , 'Enable', 'On');
            set(chkFullAIGa68DOTATATEAdrenalGlandLeft , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATEAdrenalGlandRight, 'Enable', 'On');
            set(chkFullAIGa68DOTATATEAdrenalGlandRight, 'Enable', 'Off');
            set(txtFullAIGa68DOTATATESpleen           , 'Enable', 'On');
            set(chkFullAIGa68DOTATATESpleen           , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATEGallbladder      , 'Enable', 'On');
            set(chkFullAIGa68DOTATATEGallbladder      , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATEPancreas         , 'Enable', 'On');
            set(chkFullAIGa68DOTATATEPancreas         , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATEKidneyLeft       , 'Enable', 'On');
            set(chkFullAIGa68DOTATATEKidneyLeft       , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATEKidneyRight      , 'Enable', 'On');
            set(chkFullAIGa68DOTATATEKidneyRight      , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATEEsophagus        , 'Enable', 'On');
            set(chkFullAIGa68DOTATATEEsophagus        , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATEStomach          , 'Enable', 'On');
            set(chkFullAIGa68DOTATATEStomach          , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATEDuodenum         , 'Enable', 'On');
            set(chkFullAIGa68DOTATATEDuodenum         , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATESmallBowel       , 'Enable', 'On');
            set(chkFullAIGa68DOTATATESmallBowel       , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATEColon            , 'Enable', 'On');
            set(chkFullAIGa68DOTATATEColon            , 'Enable', 'Off');
            set(txtFullAIGa68DOTATATEUrinaryBladder   , 'Enable', 'On');
            set(chkFullAIGa68DOTATATEUrinaryBladder   , 'Enable', 'Off');
        end
    end
    % Other Organs

    % Brain

    function chkFullAIGa68DOTATATEBrainCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEBrain, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEBrain, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEBrain, 'Value');

        excludeGa68DOTATATEBrain('set', bObjectValue);

    end

    % Trachea

    function chkFullAIGa68DOTATATETracheaCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATETrachea, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATETrachea, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATETrachea, 'Value');

        excludeGa68DOTATATETrachea('set', bObjectValue);

    end

    % Adrenal Gland Left

    function chkFullAIGa68DOTATATEAdrenalGlandLeftCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEAdrenalGlandLeft, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEAdrenalGlandLeft, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEAdrenalGlandLeft, 'Value');

        excludeGa68DOTATATEAdrenalGlandLeft('set', bObjectValue);

    end

    % Adrenal Gland Right

    function chkFullAIGa68DOTATATEAdrenalGlandRightCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEAdrenalGlandRight, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEAdrenalGlandRight, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEAdrenalGlandRight, 'Value');

        excludeGa68DOTATATEAdrenalGlandRight('set', bObjectValue);

    end

    % Spleen

    function chkFullAIGa68DOTATATESpleenCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATESpleen, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATESpleen, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATESpleen, 'Value');

        excludeGa68DOTATATESpleen('set', bObjectValue);

    end

    % Gallbladder

    function chkFullAIGa68DOTATATEGallbladderCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEGallbladder, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEGallbladder, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEGallbladder, 'Value');

        excludeGa68DOTATATEGallbladder('set', bObjectValue);

    end

    % Pancreas

    function chkFullAIGa68DOTATATEPancreasCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEPancreas, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEPancreas, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEPancreas, 'Value');

        excludeGa68DOTATATEPancreas('set', bObjectValue);

    end

    % Kidney Left

    function chkFullAIGa68DOTATATEKidneyLeftCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEKidneyLeft, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEKidneyLeft, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEKidneyLeft, 'Value');

        excludeGa68DOTATATEKidneyLeft('set', bObjectValue);

    end

    % Kidney Right

    function chkFullAIGa68DOTATATEKidneyRightCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEKidneyRight, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEKidneyRight, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEKidneyRight, 'Value');

        excludeGa68DOTATATEKidneyRight('set', bObjectValue);

    end

    % Gastrointestinal Tract Name

    % Esophagus

    function chkFullAIGa68DOTATATEEsophagusCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEEsophagus, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEEsophagus, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEEsophagus, 'Value');

        excludeGa68DOTATATEEsophagus('set', bObjectValue);

    end

    % Stomach

    function chkFullAIGa68DOTATATEStomachCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEStomach, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEStomach, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEStomach, 'Value');

        excludeGa68DOTATATEStomach('set', bObjectValue);

    end

    % Duodenum

    function chkFullAIGa68DOTATATEDuodenumCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEDuodenum, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEDuodenum, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEDuodenum, 'Value');

        excludeGa68DOTATATEDuodenum('set', bObjectValue);

    end

    % Small Bowel

    function chkFullAIGa68DOTATATESmallBowelCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATESmallBowel, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATESmallBowel, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATESmallBowel, 'Value');

        excludeGa68DOTATATESmallBowel('set', bObjectValue);

    end

    % Colon

    function chkFullAIGa68DOTATATEColonCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEColon, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEColon, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEColon, 'Value');

        excludeGa68DOTATATEColon('set', bObjectValue);

    end

    % Urinary Bladder

    function chkFullAIGa68DOTATATEUrinaryBladderCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEUrinaryBladder, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEUrinaryBladder, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEUrinaryBladder, 'Value');

        excludeGa68DOTATATEUrinaryBladder('set', bObjectValue);

    end

    function chkFullAIGa68DOTATATEEnhancedBoneMaskLesionCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEEnhancedBoneMaskLesion, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEEnhancedBoneMaskLesion, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEEnhancedBoneMaskLesion, 'Value');

        Ga68DOTATATEFullAIEnhancedBoneMaskLesion('set', bObjectValue);

    end

    function chkFullAIGa68DOTATATESmoothMaskCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATESmoothMask, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATESmoothMask, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATESmoothMask, 'Value');

        Ga68DOTATATEFullAISmoothMask('set', bObjectValue);
    end

    function chkFullAIGa68DOTATATEPixelEdgeCallback(hObject, ~)

        bObjectValue = get(chkFullAIGa68DOTATATEPixelEdge, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFullAIGa68DOTATATEPixelEdge, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFullAIGa68DOTATATEPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);

        % Set contour panel checkbox

        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end

    function cancelFullAiGa68DOTATATECallback(~, ~)

        delete(dlgFullAIGa68DOTATATE);

    end

    function proceedFullAiGa68DOTATATECallback(~, ~)

        dTrainedModel = get(uiFullAIGa68DOTATATETrainedModel, 'Value');

        tGa68DOTATATE.classification.enable                 = get(chkFullAIGa68DOTATATELesionClassification, 'value');
        tGa68DOTATATE.classification.enhancedBoneMaskLesion = get(chkFullAIGa68DOTATATEEnhancedBoneMaskLesion, 'Value');

        % Other Organs

        tGa68DOTATATE.exclude.organ.brain             = get(chkFullAIGa68DOTATATEBrain            , 'value');
        tGa68DOTATATE.exclude.organ.trachea           = get(chkFullAIGa68DOTATATETrachea          , 'value');
        tGa68DOTATATE.exclude.organ.adrenalGlandLeft  = get(chkFullAIGa68DOTATATEAdrenalGlandLeft , 'value');
        tGa68DOTATATE.exclude.organ.adrenalGlandRight = get(chkFullAIGa68DOTATATEAdrenalGlandRight, 'value');
        tGa68DOTATATE.exclude.organ.spleen            = get(chkFullAIGa68DOTATATESpleen           , 'value');
        tGa68DOTATATE.exclude.organ.gallbladder       = get(chkFullAIGa68DOTATATEGallbladder      , 'value');
        tGa68DOTATATE.exclude.organ.pancreas          = get(chkFullAIGa68DOTATATEPancreas         , 'value');
        tGa68DOTATATE.exclude.organ.kidneyLeft        = get(chkFullAIGa68DOTATATEKidneyLeft       , 'value');
        tGa68DOTATATE.exclude.organ.kidneyRight       = get(chkFullAIGa68DOTATATEKidneyRight      , 'value');

        % Gastrointestinal Tract Name

        tGa68DOTATATE.exclude.gastrointestinal.urinaryBladder = get(chkFullAIGa68DOTATATEUrinaryBladder, 'value');
        tGa68DOTATATE.exclude.gastrointestinal.esophagus      = get(chkFullAIGa68DOTATATEEsophagus     , 'value');
        tGa68DOTATATE.exclude.gastrointestinal.stomach        = get(chkFullAIGa68DOTATATEStomach       , 'value');
        tGa68DOTATATE.exclude.gastrointestinal.duodenum       = get(chkFullAIGa68DOTATATEDuodenum      , 'value');
        tGa68DOTATATE.exclude.gastrointestinal.smallBowel     = get(chkFullAIGa68DOTATATESmallBowel    , 'value');
        tGa68DOTATATE.exclude.gastrointestinal.colon          = get(chkFullAIGa68DOTATATEColon         , 'value');

        tGa68DOTATATE.options.smalestVoiValue = str2double(get(edtFullAIGa68DOTATATESmalestVoiValue, 'String'));
        tGa68DOTATATE.options.pixelEdge       = get(chkFullAIGa68DOTATATEPixelEdge, 'value');
        tGa68DOTATATE.options.smoothMask      = get(chkFullAIGa68DOTATATESmoothMask, 'value');

        delete(dlgFullAIGa68DOTATATE);

        setMachineLearningFullAIGa68DOTATATE(sSegmentatorScript, sOnnxPath, dTrainedModel, tGa68DOTATATE);

    end

end
