function setMachineLearningFDGBrownFatSUVCallback(hObject, ~)
%function setMachineLearningFDGBrownFatSUVCallback(hObject)
%Run FDG SUV Brown Fat Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2023, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    [sSegmentatorScript, sSegmentatorCombineMasks] = validateSegmentatorInstallation();
    

    dlgFDGBrownFatSUVSegmentation  = [];
  
    if ~isempty(sSegmentatorScript) ... % External Segmentor is installed

        if exist('hObject', 'var')
       
            DLG_FDG_BROWN_FAT_PERCENT_X = 380;
            DLG_FDG_BROWN_FAT_PERCENT_Y = 670;

            if viewerUIFigure('get') == true
        
                dlgFDGBrownFatSUVSegmentation = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_FDG_BROWN_FAT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_FDG_BROWN_FAT_PERCENT_Y/2) ...
                                        DLG_FDG_BROWN_FAT_PERCENT_X ...
                                        DLG_FDG_BROWN_FAT_PERCENT_Y ...
                                        ],...
                           'Resize', 'off', ...
                           'Color', viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name' , 'FDG SUV Machine Learning Brown Fat Segmentation'...
                           );
            else       
                dlgFDGBrownFatSUVSegmentation = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_FDG_BROWN_FAT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_FDG_BROWN_FAT_PERCENT_Y/2) ...
                                        DLG_FDG_BROWN_FAT_PERCENT_X ...
                                        DLG_FDG_BROWN_FAT_PERCENT_Y ...
                                        ],...
                           'MenuBar', 'none',...
                           'Resize', 'off', ...    
                           'NumberTitle','off',...
                           'MenuBar', 'none',...
                           'Color', viewerBackgroundColor('get'), ...
                           'Name', 'FDG SUV Machine Learning Brown Fat Segmentation',...
                           'Toolbar','none'...               
                           );    
            end

         % Exclude organs from AI analysis
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'FontWeight','bold'  ,...
                      'string'  , 'Exclude organs from AI analysis',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 630 300 20]...
                      );
    
        % Brain
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Brain',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVBrainCallback, ...
                      'position', [60 610 150 20]...
                      );
    
        chkBrownFatSUVBrain = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVBrain('get'),...
                      'position', [40 610 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVBrainCallback...
                      );
    
        % Heart
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Heart',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVHeartCallback, ...
                      'position', [60 590 150 20]...
                      );
    
        chkBrownFatSUVHeart = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVHeart('get'),...
                      'position', [40 590 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVHeartCallback...
                      );
    
        % Lungs
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Lungs',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVLungsCallback, ...
                      'position', [60 570 150 20]...
                      );
    
        chkBrownFatSUVLungs = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVLungs('get'),...
                      'position', [40 570 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVLungsCallback...
                      );
    
        % Trachea
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Trachea',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVTracheaCallback, ...
                      'position', [60 550 150 20]...
                      );
    
        chkBrownFatSUVTrachea = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVHeart('get'),...
                      'position', [40 550 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVTracheaCallback...
                      );
    
        % Kidney left
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Kidney left',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVKidneyLeftCallback, ...
                      'position', [60 530 150 20]...
                      );
    
        chkBrownFatSUVKidneyLeft = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVKidneyLeft('get'),...
                      'position', [40 530 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVKidneyLeftCallback...
                      );
    
        % Kidney right
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Kidney right',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVKidneyRightCallback, ...
                      'position', [60 510 150 20]...
                      );
    
        chkBrownFatSUVKidneyRight = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVKidneyRight('get'),...
                      'position', [40 510 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVKidneyRightCallback...
                      );
        
        % Liver
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Liver',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVLiverCallback, ...
                      'position', [60 490 150 20]...
                      );
    
        chkBrownFatSUVLiver = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVLiver('get'),...
                      'position', [40 490 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVLiverCallback...
                      );
    
        % Adrenal Gland Left
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Adrenal gland left',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVAdrenalGlandLeftCallback, ...
                      'position', [60 470 150 20]...
                      );
    
        chkBrownFatSUVAdrenalGlandLeft = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVPancreas('get'),...
                      'position', [40 470 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVAdrenalGlandLeftCallback...
                      );
    
        % Adrenal Gland Right
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Adrenal gland right',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVAdrenalGlandRightCallback, ...
                      'position', [60 450 150 20]...
                      );
    
        chkBrownFatSUVAdrenalGlandRight = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVPancreas('get'),...
                      'position', [40 450 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVAdrenalGlandRightCallback...
                      );
    
        % Spleen
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Spleen',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVSpleenCallback, ...
                      'position', [60 430 150 20]...
                      );
    
        chkBrownFatSUVSpleen = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVPancreas('get'),...
                      'position', [40 430 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVSpleenCallback...
                      );
    
        % Gallbladder
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Gallbladder',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVGallbladderCallback, ...
                      'position', [60 410 150 20]...
                      );
    
        chkBrownFatSUVGallbladder = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVPancreas('get'),...
                      'position', [40 410 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVGallbladderCallback...
                      );
    
        % Pancreas
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Pancreas',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVPancreasCallback, ...
                      'position', [60 390 150 20]...
                      );
    
        chkBrownFatSUVPancreas = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVPancreas('get'),...
                      'position', [40 390 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVPancreasCallback...
                      );

         % Esophagus
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Esophagus',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVEsophagusCallback, ...
                      'position', [60 350 150 20]...
                      );
    
        chkBrownFatSUVEsophagus = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVEsophagus('get'),...
                      'position', [40 350 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVSkeletonCallback...
                      ); 
         % Stomach
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Stomach',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVStomachCallback, ...
                      'position', [60 330 150 20]...
                      );
    
        chkBrownFatSUVStomach = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVStomach('get'),...
                      'position', [40 330 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVSkeletonCallback...
                      ); 
         % Duodenum
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Duodenum',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVDuodenumCallback, ...
                      'position', [60 310 150 20]...
                      );
    
        chkBrownFatSUVDuodenum = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVDuodenum('get'),...
                      'position', [40 310 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVSkeletonCallback...
                      );

         % SmallBowel
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Small Bowel',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVSmallBowelCallback, ...
                      'position', [60 290 150 20]...
                      );
    
        chkBrownFatSUVSmallBowel = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVSmallBowel('get'),...
                      'position', [40 290 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVSkeletonCallback...
                      );
         % Colon
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Colon',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVColonCallback, ...
                      'position', [60 270 150 20]...
                      );

        chkBrownFatSUVColon = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVColon('get'),...
                      'position', [40 270 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVSkeletonCallback...
                      );

        % Skeleton
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Skeleton',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkBrownFatSUVSkeletonCallback, ...
                      'position', [60 230 150 20]...
                      );
    
        chkBrownFatSUVSkeleton = ...
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeBrownFatSUVSkeleton('get'),...
                      'position', [40 230 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkBrownFatSUVSkeletonCallback...
                      );

        % Options
    
            uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'style'     , 'text',...
                      'FontWeight','bold'  ,...
                      'string'    , 'Options',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 190 300 20]...
                      );

            % SUV Type

            asSUVType = FDGBrownFatSUVType('get'); 
            
            if strcmpi(asSUVType, 'BW') % Body Weight
                dSUVoffset = 1;
            elseif strcmpi(asSUVType, 'FDG') % Brads FDG specific SUV
                dSUVoffset = 2;
            elseif strcmpi(asSUVType, 'BSA') % body surface area
                dSUVoffset = 3;            
            elseif strcmpi(asSUVType, 'LBM') % lean body mass 
                dSUVoffset = 4;
            elseif strcmpi(asSUVType, 'LBMJANMA') % lean body mass by Janmahasatian method
                dSUVoffset = 5;
            else
                dSUVoffset = 1;
            end

                 uicontrol(dlgFDGBrownFatSUVSegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'SUV Type',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 165 185 20]...
                          );
        
            edtFDGBrownFatSUVType = ...
                uicontrol(dlgFDGBrownFatSUVSegmentation, ...
                          'Enable'  , 'on', ...
                          'Style'   , 'popup', ...
                          'Position', [205 165 155 25], ...
                          'String'  , {'BW', 'FDG', 'BSA', 'LBM', 'LBMJANMA'}, ...
                          'Value'   , dSUVoffset, ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtFDGBrownFatSUVTypeCallback ...
                          ); 

            % CT HU threshold
    
            [dHUMinValue, dHUMaxValue] = FDGBrownFatHUThresholdValue('get');
    
                uicontrol(dlgFDGBrownFatSUVSegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'CT HU Threshold',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 140 185 20]...
                          );
        
            edtFDGBrownFatHUThresholdOfMaxValue = ...
                uicontrol(dlgFDGBrownFatSUVSegmentation, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 140 75 20], ...
                          'String'  , num2str(dHUMaxValue), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtFDGBrownFatHUThresholdValueCallback ...
                          ); 
    
            edtFDGBrownFatHUThresholdOfMinValue = ...
                uicontrol(dlgFDGBrownFatSUVSegmentation, ...
                          'Style'   , 'Edit', ...
                          'Position', [205 140 75 20], ...
                          'String'  , num2str(dHUMinValue), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtFDGBrownFatHUThresholdValueCallback ...
                          ); 
    
            % SUV threshold
        
                uicontrol(dlgFDGBrownFatSUVSegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'PT SUV Threshold',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 115 250 20]...
                          );
        
            edtFDGBrownFatSUVThresholdOfMaxValue = ...
                uicontrol(dlgFDGBrownFatSUVSegmentation, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 115 75 20], ...
                          'String'  , num2str(FDGBrownFatSUVThresholdValue('get')), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtFDGBrownFatSUVThresholdOfMaxValueCallback ...
                          );     
        
             % Pixel Edge
        
                uicontrol(dlgFDGBrownFatSUVSegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Pixel Edge',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkFDGBrownFatSUVPixelEdgeCallback, ...
                          'position', [40 90 150 20]...
                          );
        
            chkFDGBrownFatSUVPixelEdge = ...
                uicontrol(dlgFDGBrownFatSUVSegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , pixelEdge('get'),...
                          'position', [20 90 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkFDGBrownFatSUVPixelEdgeCallback...
                          );
        
            % Smallest Contour (ml)
        
                uicontrol(dlgFDGBrownFatSUVSegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'Smallest Contour (ml)',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 65 250 20]...
                          );
        
            edtFDGBrownFatSUVSmalestVoiValue = ...
                uicontrol(dlgFDGBrownFatSUVSegmentation, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 65 75 20], ...
                          'String'  , num2str(FDGBrownFatSmalestVoiValue('get')), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtFDGBrownFatSUVSmalestVoiValueCallback ...
                          );  
        
             % Cancel or Proceed
        
             uicontrol(dlgFDGBrownFatSUVSegmentation,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelFDGBrownFatSUVSegmentationCallback...
                       );
        
             uicontrol(dlgFDGBrownFatSUVSegmentation,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedFDGBrownFatSUVSegmentationCallback...
                      );               
        else
            % Set SUV type

            viewerSUVtype('set', FDGBrownFatSUVType('get'));         
        
            setQuantification( get(uiSeriesPtr('get'), 'Value') );

            % Exclude List
    
            tBrownFatSUV.exclude.organ.brain             = excludeBrownFatSUVBrain('get');
            tBrownFatSUV.exclude.organ.heart             = excludeBrownFatSUVHeart('get');
            tBrownFatSUV.exclude.organ.lungs             = excludeBrownFatSUVLungs('get');
            tBrownFatSUV.exclude.organ.kidneyLeft        = excludeBrownFatSUVKidneyLeft('get');
            tBrownFatSUV.exclude.organ.kidneyRight       = excludeBrownFatSUVKidneyRight('get');
            tBrownFatSUV.exclude.organ.liver             = excludeBrownFatSUVLiver('get');
            tBrownFatSUV.exclude.organ.trachea           = excludeGa68DOTATATETrachea('get');
            tBrownFatSUV.exclude.organ.adrenalGlandLeft  = excludeBrownFatSUVAdrenalGlandLeft('get');
            tBrownFatSUV.exclude.organ.adrenalGlandRight = excludeBrownFatSUVAdrenalGlandRight('get');
            tBrownFatSUV.exclude.organ.spleen            = excludeBrownFatSUVSpleen('get');
            tBrownFatSUV.exclude.organ.gallbladder       = excludeBrownFatSUVGallbladder('get');
            tBrownFatSUV.exclude.organ.pancreas          = excludeBrownFatSUVPancreas('get');
    
            tBrownFatSUV.exclude.organ.esophagus         = excludeBrownFatSUVEsophagus('get');
            tBrownFatSUV.exclude.organ.stomach           = excludeBrownFatSUVStomach('get');
            tBrownFatSUV.exclude.organ.duodenum          = excludeBrownFatSUVDuodenum('get');
            tBrownFatSUV.exclude.organ.smallBowel        = excludeBrownFatSUVSmallBowel('get');
            tBrownFatSUV.exclude.organ.colon             = excludeBrownFatSUVColon('get');

            tBrownFatSUV.exclude.organ.skeleton          = excludeBrownFatSUVSkeleton('get');

            % Options
            
            [dHUMinValue, dHUMaxValue] = FDGBrownFatHUThresholdValue('get');

            tBrownFatSUV.options.smalestVoiValue       = FDGBrownFatSmalestVoiValue('get');
            tBrownFatSUV.options.pixelEdge             = pixelEdge('get');
            tBrownFatSUV.options.HUThreshold.min       = dHUMinValue;
            tBrownFatSUV.options.HUThreshold.max       = dHUMaxValue;
            tBrownFatSUV.options.SUVThreshold          = FDGBrownFatSUVThresholdValue('get');
        
            setMachineLearningFDGBrownFatSUV(sSegmentatorScript, sSegmentatorCombineMasks, tBrownFatSUV);    

        end
    end

    % Exclude organs from AI analysis

    % Brain

    function chkBrownFatSUVBrainCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVBrain, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVBrain, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVBrain, 'Value');

        excludeBrownFatSUVBrain('set', bObjectValue);

    end

    % Heart

    function chkBrownFatSUVHeartCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVHeart, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVHeart, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVHeart, 'Value');

        excludeBrownFatSUVHeart('set', bObjectValue);

    end

    % Lungs

    function chkBrownFatSUVLungsCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVLungs, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVLungs, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVLungs, 'Value');

        excludeBrownFatSUVLungs('set', bObjectValue);

    end

    % Trachea

    function chkBrownFatSUVTracheaCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVTrachea, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVTrachea, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVTrachea, 'Value');

        excludeBrownFatSUVTrachea('set', bObjectValue);

    end

    % Kidney Left

    function chkBrownFatSUVKidneyLeftCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVKidneyLeft, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVKidneyLeft, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVKidneyLeft, 'Value');

        excludeBrownFatSUVKidneyLeft('set', bObjectValue);

    end

    % Kidney Right

    function chkBrownFatSUVKidneyRightCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVKidneyRight, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVKidneyRight, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVKidneyRight, 'Value');

        excludeBrownFatSUVKidneyRight('set', bObjectValue);

    end

    % Liver

    function chkBrownFatSUVLiverCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVLiver, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVLiver, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVLiver, 'Value');

        excludeBrownFatSUVLiver('set', bObjectValue);

    end

    % Adrenal Gland Left

    function chkBrownFatSUVAdrenalGlandLeftCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVAdrenalGlandLeft, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVAdrenalGlandLeft, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVAdrenalGlandLeft, 'Value');

        excludeBrownFatSUVAdrenalGlandLeft('set', bObjectValue);

    end

    % Adrenal Gland Right

    function chkBrownFatSUVAdrenalGlandRightCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVAdrenalGlandRight, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVAdrenalGlandRight, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVAdrenalGlandRight, 'Value');

        excludeBrownFatSUVAdrenalGlandRight('set', bObjectValue);

    end

    % Spleen

    function chkBrownFatSUVSpleenCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVSpleen, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVSpleen, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVSpleen, 'Value');

        excludeBrownFatSUVSpleen('set', bObjectValue);

    end

    % Gallbladder

    function chkBrownFatSUVGallbladderCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVGallbladder, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVGallbladder, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVGallbladder, 'Value');

        excludeBrownFatSUVGallbladder('set', bObjectValue);

    end

    % Pancreas

    function chkBrownFatSUVPancreasCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVPancreas, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVPancreas, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVPancreas, 'Value');

        excludeBrownFatSUVPancreas('set', bObjectValue);

    end

    % Esophagus

    function chkBrownFatSUVEsophagusCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVEsophagus, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVEsophagus, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVEsophagus, 'Value');

        excludeBrownFatSUVEsophagus('set', bObjectValue);

    end

    % Stomach

    function chkBrownFatSUVStomachCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVStomach, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVStomach, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVStomach, 'Value');

        excludeBrownFatSUVStomach('set', bObjectValue);

    end

    % Duodenum

    function chkBrownFatSUVDuodenumCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVDuodenum, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVDuodenum, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVDuodenum, 'Value');

        excludeBrownFatSUVDuodenum('set', bObjectValue);

    end

    % SmallBowel

    function chkBrownFatSUVSmallBowelCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVSmallBowel, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVSmallBowel, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVSmallBowel, 'Value');

        excludeBrownFatSUVSmallBowel('set', bObjectValue);

    end

    % Colon

    function chkBrownFatSUVColonCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVColon, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVColon, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVColon, 'Value');

        excludeBrownFatSUVColon('set', bObjectValue);

    end
           
    % Skeleton

    function chkBrownFatSUVSkeletonCallback(hObject, ~)  
                
        bObjectValue = get(chkBrownFatSUVSkeleton, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBrownFatSUVSkeleton, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBrownFatSUVSkeleton, 'Value');

        excludeBrownFatSUVSkeleton('set', bObjectValue);

    end

    function edtFDGBrownFatSUVSmalestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtFDGBrownFatSUVSmalestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtFDGBrownFatSUVSmalestVoiValue, 'String', num2str(dObjectValue));
        end

        FDGSmalestVoiValue('set', dObjectValue);

    end

    function chkFDGBrownFatSUVPixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkFDGBrownFatSUVPixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDGBrownFatSUVPixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDGBrownFatSUVPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox

        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end

    function edtFDGBrownFatHUThresholdValueCallback(~, ~)     

        dBrownFatCTHUMinThreshold = str2double(get(edtFDGBrownFatHUThresholdOfMinValue, 'String'));
        dBrownFatCTHUMaxThreshold = str2double(get(edtFDGBrownFatHUThresholdOfMaxValue, 'String'));

        if dBrownFatCTHUMinThreshold >= dBrownFatCTHUMaxThreshold

            dBrownFatCTHUMinThreshold = dBrownFatCTHUMaxThreshold-1;

            set(edtFDGBrownFatHUThresholdOfMinValue, 'String', num2str(dBrownFatCTHUMinThreshold));
        end

        if dBrownFatCTHUMaxThreshold <= dBrownFatCTHUMinThreshold

            dBrownFatCTHUMaxThreshold = dBrownFatCTHUMinThreshold+1;

             set(edtFDGBrownFatHUThresholdOfMaxValue, 'String', num2str(dBrownFatCTHUMaxThreshold));
           
        end

        FDGBrownFatHUThresholdValue('set', dBrownFatCTHUMinThreshold, dBrownFatCTHUMaxThreshold); % HU
    end

    function edtFDGBrownFatSUVThresholdOfMaxValueCallback(~, ~)     

        dBrownFatThreshold = str2double(get(edtFDGBrownFatSUVThresholdOfMaxValue, 'String'));

        if dBrownFatThreshold <= 0

            dBrownFatThreshold = 2.5;

            set(edtFDGBrownFatSUVThresholdOfMaxValue, 'String', num2str(dBrownFatThreshold));
         
        end

        FDGBrownFatSUVThresholdValue('set', dBrownFatThreshold);

    end

    function edtFDGBrownFatSUVTypeCallback(~, ~)

        asSUVType = get(edtFDGBrownFatSUVType, 'String');
        dSUVType  = get(edtFDGBrownFatSUVType, 'Value');

        FDGBrownFatSUVType('set', asSUVType{dSUVType});
        
    end

    function cancelFDGBrownFatSUVSegmentationCallback(~, ~)   

        delete(dlgFDGBrownFatSUVSegmentation);
    end
    
    function proceedFDGBrownFatSUVSegmentationCallback(~, ~)

        % Set SUV type

        viewerSUVtype('set', FDGBrownFatSUVType('get'));         
    
        setQuantification( get(uiSeriesPtr('get'), 'Value') );

        % Exclude List

        tBrownFatSUV.exclude.organ.brain             = get(chkBrownFatSUVBrain            , 'value');
        tBrownFatSUV.exclude.organ.heart             = get(chkBrownFatSUVHeart            , 'value');
        tBrownFatSUV.exclude.organ.lungs             = get(chkBrownFatSUVLungs            , 'value');
        tBrownFatSUV.exclude.organ.kidneyLeft        = get(chkBrownFatSUVKidneyLeft       , 'value');
        tBrownFatSUV.exclude.organ.kidneyRight       = get(chkBrownFatSUVKidneyRight      , 'value');
        tBrownFatSUV.exclude.organ.liver             = get(chkBrownFatSUVLiver            , 'value');
        tBrownFatSUV.exclude.organ.trachea           = get(chkBrownFatSUVTrachea          , 'value');
        tBrownFatSUV.exclude.organ.adrenalGlandLeft  = get(chkBrownFatSUVAdrenalGlandLeft , 'value');
        tBrownFatSUV.exclude.organ.adrenalGlandRight = get(chkBrownFatSUVAdrenalGlandRight, 'value');
        tBrownFatSUV.exclude.organ.spleen            = get(chkBrownFatSUVSpleen           , 'value');
        tBrownFatSUV.exclude.organ.gallbladder       = get(chkBrownFatSUVGallbladder      , 'value');
        tBrownFatSUV.exclude.organ.pancreas          = get(chkBrownFatSUVPancreas         , 'value');

        tBrownFatSUV.exclude.organ.esophagus         = get(chkBrownFatSUVEsophagus        , 'value');
        tBrownFatSUV.exclude.organ.stomach           = get(chkBrownFatSUVStomach          , 'value');
        tBrownFatSUV.exclude.organ.duodenum          = get(chkBrownFatSUVDuodenum         , 'value');
        tBrownFatSUV.exclude.organ.smallBowel        = get(chkBrownFatSUVSmallBowel       , 'value');
        tBrownFatSUV.exclude.organ.colon             = get(chkBrownFatSUVColon            , 'value');
        
        tBrownFatSUV.exclude.organ.skeleton          = get(chkBrownFatSUVSkeleton         , 'value');

        % Options

        tBrownFatSUV.options.smalestVoiValue       = str2double(get(edtFDGBrownFatSUVSmalestVoiValue    , 'String'));
        tBrownFatSUV.options.pixelEdge             =            get(chkFDGBrownFatSUVPixelEdge          , 'value' );
        tBrownFatSUV.options.HUThreshold.min       = str2double(get(edtFDGBrownFatHUThresholdOfMinValue , 'String'));
        tBrownFatSUV.options.HUThreshold.max       = str2double(get(edtFDGBrownFatHUThresholdOfMaxValue , 'String'));
        tBrownFatSUV.options.SUVThreshold          = str2double(get(edtFDGBrownFatSUVThresholdOfMaxValue, 'String'));

        delete(dlgFDGBrownFatSUVSegmentation);

        setMachineLearningFDGBrownFatSUV(sSegmentatorScript, sSegmentatorCombineMasks, tBrownFatSUV); 
    end
    
end