function setMachineLearningFDGBrownFatPETCTFullAICallback(hObject, ~)
%function setMachineLearningFDGBrownFatPETCTFullAICallback(hObject)
%Run FDG SUV Brown Fat PET\CT Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2023, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    [sPredictScript] = validateNnUNetv2Installation();
    
    dlgFDGBrownFatPETCTFullAISegmentation  = [];
  
    if ~isempty(sPredictScript) ... % External Segmentor is installed

        if exist('hObject', 'var')

            DLG_FDG_BROWN_FAT_PERCENT_X = 380;
            DLG_FDG_BROWN_FAT_PERCENT_Y = 265;

            if viewerUIFigure('get') == true
        
                dlgFDGBrownFatPETCTFullAISegmentation = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_FDG_BROWN_FAT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_FDG_BROWN_FAT_PERCENT_Y/2) ...
                                        DLG_FDG_BROWN_FAT_PERCENT_X ...
                                        DLG_FDG_BROWN_FAT_PERCENT_Y ...
                                        ],...
                           'Resize', 'off', ...
                           'Color', viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name' , 'FDG Machine Learning Full AI Brown Fat Segmentation'...
                           );
            else       
                dlgFDGBrownFatPETCTFullAISegmentation = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_FDG_BROWN_FAT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_FDG_BROWN_FAT_PERCENT_Y/2) ...
                                        DLG_FDG_BROWN_FAT_PERCENT_X ...
                                        DLG_FDG_BROWN_FAT_PERCENT_Y ...
                                        ],...
                           'MenuBar', 'none',...
                           'Resize', 'off', ...    
                           'NumberTitle','off',...
                           'MenuBar', 'none',...
                           'Color', viewerBackgroundColor('get'), ...
                           'Name', 'FDG Machine Learning Full AI Brown Fat Segmentation',...
                           'Toolbar','none'...               
                           );    
            end

            % Trainer with Dice and CE Loss
        
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Trainer with Dice and CE Loss, no smoothing',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkFDGBrownFatPETCTFullAICELossCallback, ...
                          'position', [40 215 250 20]...
                          );
        
            chkFDGBrownFatPETCTFullAICELoss = ...
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningFDGBrownFatCELoss('get'),...
                          'position', [20 215 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkFDGBrownFatPETCTFullAICELossCallback...
                          );

            % Classify the Segmentation
        
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Classify the Segmentation',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkFDGBrownFatPETCTFullAIClassifySegmentationCallback, ...
                          'position', [40 190 250 20]...
                          );
        
            chkFDGBrownFatPETCTFullAIClassifySegmentation = ...
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningFDGBrownFatClassifySegmentation('get'),...
                          'position', [20 190 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkFDGBrownFatPETCTFullAIClassifySegmentationCallback...
                          );

             % SUV scaled
        
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'SUV-Scaled',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkFDGBrownFatPETCTFullAISUVScaledCallback, ...
                          'position', [40 165 250 20]...
                          );
        
            chkFDGBrownFatPETCTFullAISUVScaled = ...
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningFDGBrownFatSUVScaled('get'),...
                          'position', [20 165 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkFDGBrownFatPETCTFullAISUVScaledCallback...
                          );

            % SUV normalization

            if machineLearningFDGBrownFatSUVScaled('get') == true
                sSUVNormalizationTxtEnable = 'Inactive';
                sSUVNormalizationChkEnable = 'on';
            else
                sSUVNormalizationTxtEnable = 'on';
                sSUVNormalizationChkEnable = 'off';               
            end

            txtFDGBrownFatPETCTFullAISUVNormalization = ...
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , sSUVNormalizationTxtEnable,...
                          'string'  , 'SUV-Normalization',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkFDGBrownFatPETCTFullAISUVNormalizationCallback, ...
                          'position', [60 140 250 20]...
                          );
        
            chkFDGBrownFatPETCTFullAISUVNormalization = ...
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , sSUVNormalizationChkEnable,...
                          'value'   , machineLearningFDGBrownFatSUVNormalization('get'),...
                          'position', [40 140 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkFDGBrownFatPETCTFullAISUVNormalizationCallback...
                          );

            % Smooth mask

                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Smooth Mask',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'ButtonDownFcn'  , @chkFDGBrownFatPETCTFullAISmoothMaskCallback, ...
                          'position', [40 115 150 20]...
                          );

            chkFDGBrownFatPETCTFullAISmoothMask = ...
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningFDGBrownFatSmoothMask('get'),...
                          'position', [20 115 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'Callback', @chkFDGBrownFatPETCTFullAISmoothMaskCallback...
                          );            
             % Pixel Edge
        
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Pixel Edge',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkFDGBrownFatPETCTFullAIPixelEdgeCallback, ...
                          'position', [40 90 150 20]...
                          );
        
            chkFDGBrownFatPETCTFullAIPixelEdge = ...
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , pixelEdge('get'),...
                          'position', [20 90 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkFDGBrownFatPETCTFullAIPixelEdgeCallback...
                          );

            % Smallest Contour (ml)
        
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'Smallest Contour (ml)',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 65 250 20]...
                          );
        
            edtFDGBrownFatPETCTFullAISmallestVoiValue = ...
                uicontrol(dlgFDGBrownFatPETCTFullAISegmentation, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 65 75 20], ...
                          'String'  , num2str(machineLearningFDGBrownFatSmallestVoiValue('get')), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtFDGBrownFatPETCTFullAISmallestVoiValueCallback ...
                          );  
        
             % Cancel or Proceed
        
             uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelFDGBrownFatPETCTFullAISegmentationCallback...
                       );
        
             uicontrol(dlgFDGBrownFatPETCTFullAISegmentation,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedFDGBrownFatPETCTFullAISegmentationCallback...
                      );               
        else

            % Options
            
            tBrownFatPETCTFullAI.options.CELossTrainer        = machineLearningFDGBrownFatCELoss('get');
            tBrownFatPETCTFullAI.options.classifySegmentation = machineLearningFDGBrownFatClassifySegmentation('get');
            tBrownFatPETCTFullAI.options.smoothMask           = machineLearningFDGBrownFatSmoothMask('get');
            tBrownFatPETCTFullAI.options.smallestVoiValue     = machineLearningFDGBrownFatSmallestVoiValue('get');
            tBrownFatPETCTFullAI.options.pixelEdge            = pixelEdge('get');
            tBrownFatPETCTFullAI.options.SUVNormalization     = machineLearningFDGBrownFatSUVNormalization('get');
            tBrownFatPETCTFullAI.options.SUVScaled            = machineLearningFDGBrownFatSUVScaled('get');
  
            setMachineLearningFDGBrownFatPETCTFullAI(sPredictScript, tBrownFatPETCTFullAI); 
        end
    end

    function chkFDGBrownFatPETCTFullAICELossCallback(hObject, ~)

        bObjectValue = get(chkFDGBrownFatPETCTFullAICELoss, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFDGBrownFatPETCTFullAICELoss, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFDGBrownFatPETCTFullAICELoss, 'Value');

        machineLearningFDGBrownFatCELoss('set', bObjectValue);
    end

    function chkFDGBrownFatPETCTFullAIClassifySegmentationCallback(hObject, ~)

        bObjectValue = get(chkFDGBrownFatPETCTFullAIClassifySegmentation, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFDGBrownFatPETCTFullAIClassifySegmentation, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFDGBrownFatPETCTFullAIClassifySegmentation, 'Value');

        machineLearningFDGBrownFatClassifySegmentation('set', bObjectValue);
    end

    function chkFDGBrownFatPETCTFullAISmoothMaskCallback(hObject, ~)

        bObjectValue = get(chkFDGBrownFatPETCTFullAISmoothMask, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkFDGBrownFatPETCTFullAISmoothMask, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkFDGBrownFatPETCTFullAISmoothMask, 'Value');

        machineLearningFDGBrownFatSmoothMask('set', bObjectValue);
    end

    function chkFDGBrownFatPETCTFullAISUVScaledCallback(hObject, ~)

        bObjectValue = get(chkFDGBrownFatPETCTFullAISUVScaled, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDGBrownFatPETCTFullAISUVScaled, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDGBrownFatPETCTFullAISUVScaled, 'Value');

        machineLearningFDGBrownFatSUVScaled('set', bObjectValue);

        % SUV normalization

        if machineLearningFDGBrownFatSUVScaled('get') == true
            sSUVNormalizationTxtEnable = 'Inactive';
            sSUVNormalizationChkEnable = 'on';
        else
            sSUVNormalizationTxtEnable = 'on';
            sSUVNormalizationChkEnable = 'off';               
        end        

        set(txtFDGBrownFatPETCTFullAISUVNormalization, 'Enable', sSUVNormalizationTxtEnable);
        set(chkFDGBrownFatPETCTFullAISUVNormalization, 'Enable', sSUVNormalizationChkEnable);
    
    end

    function chkFDGBrownFatPETCTFullAISUVNormalizationCallback(hObject, ~)

        bObjectValue = get(chkFDGBrownFatPETCTFullAISUVNormalization, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDGBrownFatPETCTFullAISUVNormalization, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDGBrownFatPETCTFullAISUVNormalization, 'Value');

        machineLearningFDGBrownFatSUVNormalization('set', bObjectValue);
        
    end

    function edtFDGBrownFatPETCTFullAISmallestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtFDGBrownFatPETCTFullAISmallestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtFDGBrownFatPETCTFullAISmallestVoiValue, 'String', num2str(dObjectValue));
        end

        machineLearningFDGBrownFatSmallestVoiValue('set', dObjectValue);

    end

    function chkFDGBrownFatPETCTFullAIPixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkFDGBrownFatPETCTFullAIPixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDGBrownFatPETCTFullAIPixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDGBrownFatPETCTFullAIPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox

        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end

    function cancelFDGBrownFatPETCTFullAISegmentationCallback(~, ~)   

        delete(dlgFDGBrownFatPETCTFullAISegmentation);
    end
    
    function proceedFDGBrownFatPETCTFullAISegmentationCallback(~, ~)


        % Options

        tBrownFatPETCTFullAI.options.CELossTrainer        =            get(chkFDGBrownFatPETCTFullAICELoss, 'Value');
        tBrownFatPETCTFullAI.options.classifySegmentation =            get(chkFDGBrownFatPETCTFullAIClassifySegmentation, 'Value');
        tBrownFatPETCTFullAI.options.smoothMask           =            get(chkFDGBrownFatPETCTFullAISmoothMask, 'Value');
        tBrownFatPETCTFullAI.options.smallestVoiValue     = str2double(get(edtFDGBrownFatPETCTFullAISmallestVoiValue, 'String'));
        tBrownFatPETCTFullAI.options.pixelEdge            =            get(chkFDGBrownFatPETCTFullAIPixelEdge       , 'value' );
        tBrownFatPETCTFullAI.options.SUVNormalization     =            get(chkFDGBrownFatPETCTFullAISUVNormalization, 'value' );
        tBrownFatPETCTFullAI.options.SUVScaled            =            get(chkFDGBrownFatPETCTFullAISUVScaled, 'value' );

        delete(dlgFDGBrownFatPETCTFullAISegmentation);

        setMachineLearningFDGBrownFatPETCTFullAI(sPredictScript, tBrownFatPETCTFullAI); 
    end
end