function setMachineLearningPSMALu177SPECTFullAICallback(hObject, ~)
%function setMachineLearningPSMALu177SPECTFullAICallback()
%Run PSMA Lu177 SPECT Full AI Tumor Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2024, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    [sPredictScript] = validateNnUNetv2Installation();
    
    dlgPSMALu177SPECTFullAISegmentation  = [];
  
    if ~isempty(sPredictScript) ... % External Segmentor is installed

        if exist('hObject', 'var')

            DLG_PSMA_LU177_SPECT_PERCENT_X = 380;
            DLG_PSMA_LU177_SPECT_PERCENT_Y = 215;

            if viewerUIFigure('get') == true
        
                dlgPSMALu177SPECTFullAISegmentation = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_PSMA_LU177_SPECT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_PSMA_LU177_SPECT_PERCENT_Y/2) ...
                                        DLG_PSMA_LU177_SPECT_PERCENT_X ...
                                        DLG_PSMA_LU177_SPECT_PERCENT_Y ...
                                        ],...
                           'Resize', 'off', ...
                           'Color', viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name' , 'PSMA Lu177 Machine Learning Full AI SPECT Segmentation'...
                           );
            else       
                dlgPSMALu177SPECTFullAISegmentation = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_PSMA_LU177_SPECT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_PSMA_LU177_SPECT_PERCENT_Y/2) ...
                                        DLG_PSMA_LU177_SPECT_PERCENT_X ...
                                        DLG_PSMA_LU177_SPECT_PERCENT_Y ...
                                        ],...
                           'MenuBar', 'none',...
                           'Resize', 'off', ...    
                           'NumberTitle','off',...
                           'MenuBar', 'none',...
                           'Color', viewerBackgroundColor('get'), ...
                           'Name', 'PSMA Lu177 Machine Learning Full AI SPECT Segmentation',...
                           'Toolbar','none'...               
                           );    
            end

            % Trainer with Dice and CE Loss
        
                uicontrol(dlgPSMALu177SPECTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Trainer with Dice and CE Loss, no smoothing',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkPSMALu177SPECTFullAICELossCallback, ...
                          'position', [40 165 250 20]...
                          );
        
            chkPSMALu177SPECTFullAICELoss = ...
                uicontrol(dlgPSMALu177SPECTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningPSMALu177CELoss('get'),...
                          'position', [20 165 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkPSMALu177SPECTFullAICELossCallback...
                          );

            % Classify Segmentation
        
                uicontrol(dlgPSMALu177SPECTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Classify the Segmentation',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkPSMALu177SPECTFullAIClassifySegmentationCallback, ...
                          'position', [40 140 250 20]...
                          );
        
            chkPSMALu177SPECTFullAIClassifySegmentation = ...
                uicontrol(dlgPSMALu177SPECTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningPSMALu177ClassifySegmentation('get'),...
                          'position', [20 140 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkPSMALu177SPECTFullAIClassifySegmentationCallback...
                          );

            % Smooth mask

                uicontrol(dlgPSMALu177SPECTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Smooth Mask',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'ButtonDownFcn'  , @chkPSMALu177SPECTFullAISmoothMaskCallback, ...
                          'position', [40 115 150 20]...
                          );

            chkPSMALu177SPECTFullAISmoothMask = ...
                uicontrol(dlgPSMALu177SPECTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningPSMALu177SmoothMask('get'),...
                          'position', [20 115 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'Callback', @chkPSMALu177SPECTFullAISmoothMaskCallback...
                          );
             % Pixel Edge
        
                uicontrol(dlgPSMALu177SPECTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Pixel Edge',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkPSMALu177SPECTFullAIPixelEdgeCallback, ...
                          'position', [40 90 150 20]...
                          );
        
            chkPSMALu177SPECTFullAIPixelEdge = ...
                uicontrol(dlgPSMALu177SPECTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , pixelEdge('get'),...
                          'position', [20 90 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkPSMALu177SPECTFullAIPixelEdgeCallback...
                          );

            % Smallest Contour (ml)
        
                uicontrol(dlgPSMALu177SPECTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'Smallest Contour (ml)',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 65 250 20]...
                          );
        
            edtPSMALu177SPECTFullAISmallestVoiValue = ...
                uicontrol(dlgPSMALu177SPECTFullAISegmentation, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 65 75 20], ...
                          'String'  , num2str(machineLearningPSMALu177SmallestVoiValue('get')), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtPSMALu177SPECTFullAISmallestVoiValueCallback ...
                          );  
        
             % Cancel or Proceed
        
             uicontrol(dlgPSMALu177SPECTFullAISegmentation,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelPSMALu177SPECTFullAISegmentationCallback...
                       );
        
             uicontrol(dlgPSMALu177SPECTFullAISegmentation,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedPSMALu177SPECTFullAISegmentationCallback...
                      );               
        else

            % Options

            tPSMALu177SPECTFullAI.options.CELossTrainer        = machineLearningPSMALu177CELoss('get');
            tPSMALu177SPECTFullAI.options.classifySegmentation = machineLearningPSMALu177ClassifySegmentation('get');
            tPSMALu177SPECTFullAI.options.smoothMask           = machineLearningPSMALu177SmoothMask('get');
            tPSMALu177SPECTFullAI.options.smallestVoiValue     = machineLearningPSMALu177SmallestVoiValue('get');
            tPSMALu177SPECTFullAI.options.pixelEdge            = pixelEdge('get');
    
            setMachineLearningPSMALu177SPECTFullAI(sPredictScript, tPSMALu177SPECTFullAI); 
        end
    end

    function chkPSMALu177SPECTFullAICELossCallback(hObject, ~)

        bObjectValue = get(chkPSMALu177SPECTFullAICELoss, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkPSMALu177SPECTFullAICELoss, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkPSMALu177SPECTFullAICELoss, 'Value');

        machineLearningPSMALu177CELoss('set', bObjectValue);
    end

    function chkPSMALu177SPECTFullAIClassifySegmentationCallback(hObject, ~)

        bObjectValue = get(chkPSMALu177SPECTFullAIClassifySegmentation, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkPSMALu177SPECTFullAIClassifySegmentation, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkPSMALu177SPECTFullAIClassifySegmentation, 'Value');

        machineLearningPSMALu177ClassifySegmentation('set', bObjectValue);
    end

    function chkPSMALu177SPECTFullAISmoothMaskCallback(hObject, ~)

        bObjectValue = get(chkPSMALu177SPECTFullAISmoothMask, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkPSMALu177SPECTFullAISmoothMask, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkPSMALu177SPECTFullAISmoothMask, 'Value');

        machineLearningPSMALu177SmoothMask('set', bObjectValue);
    end

    function edtPSMALu177SPECTFullAISmallestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtPSMALu177SPECTFullAISmallestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtPSMALu177SPECTFullAISmallestVoiValue, 'String', num2str(dObjectValue));
        end

        machineLearningPSMALu177SmallestVoiValue('set', dObjectValue);

    end

    function chkPSMALu177SPECTFullAIPixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkPSMALu177SPECTFullAIPixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkPSMALu177SPECTFullAIPixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkPSMALu177SPECTFullAIPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox

        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end

    function cancelPSMALu177SPECTFullAISegmentationCallback(~, ~)   

        delete(dlgPSMALu177SPECTFullAISegmentation);
    end
    
    function proceedPSMALu177SPECTFullAISegmentationCallback(~, ~)

        % Options

        tPSMALu177SPECTFullAI.options.CELossTrainer        =            get(chkPSMALu177SPECTFullAICELoss, 'Value');
        tPSMALu177SPECTFullAI.options.classifySegmentation =            get(chkPSMALu177SPECTFullAIClassifySegmentation, 'Value');
        tPSMALu177SPECTFullAI.options.smoothMask           =            get(chkPSMALu177SPECTFullAISmoothMask, 'Value');
        tPSMALu177SPECTFullAI.options.smallestVoiValue     = str2double(get(edtPSMALu177SPECTFullAISmallestVoiValue , 'String'));
        tPSMALu177SPECTFullAI.options.pixelEdge            =            get(chkPSMALu177SPECTFullAIPixelEdge, 'Value');

        delete(dlgPSMALu177SPECTFullAISegmentation);

        setMachineLearningPSMALu177SPECTFullAI(sPredictScript, tPSMALu177SPECTFullAI); 
    end

end