function setMachineLearningBreastCancerPETFullAICallback(hObject, ~)
%function setMachineLearningBreastCancerPETFullAICallback()
%Run Metastatic Breast Cancer PET Full AI Tumor Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2024, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    [sPredictScript] = validateNnUNetv2Installation();
    
    dlgBreastCancerPETFullAISegmentation  = [];
  
    if ~isempty(sPredictScript) ... % External Segmentor is installed

        if exist('hObject', 'var')

            DLG_BREAST_CANCER_SPECT_PERCENT_X = 380;
            DLG_BREAST_CANCER_SPECT_PERCENT_Y = 215;

            if viewerUIFigure('get') == true
        
                dlgBreastCancerPETFullAISegmentation = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_BREAST_CANCER_SPECT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_BREAST_CANCER_SPECT_PERCENT_Y/2) ...
                                        DLG_BREAST_CANCER_SPECT_PERCENT_X ...
                                        DLG_BREAST_CANCER_SPECT_PERCENT_Y ...
                                        ],...
                           'Resize', 'off', ...
                           'Color', viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name' , 'Metastatic Breast Cancer Machine Learning Full AI PET Segmentation'...
                           );
            else       
                dlgBreastCancerPETFullAISegmentation = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_BREAST_CANCER_SPECT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_BREAST_CANCER_SPECT_PERCENT_Y/2) ...
                                        DLG_BREAST_CANCER_SPECT_PERCENT_X ...
                                        DLG_BREAST_CANCER_SPECT_PERCENT_Y ...
                                        ],...
                           'MenuBar', 'none',...
                           'Resize', 'off', ...    
                           'NumberTitle','off',...
                           'MenuBar', 'none',...
                           'Color', viewerBackgroundColor('get'), ...
                           'Name', 'Metastatic Breast Cancer Machine Learning Full AI PET Segmentation',...
                           'Toolbar','none'...               
                           );    
            end

            % Trainer with Dice and CE Loss
        
                uicontrol(dlgBreastCancerPETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Trainer with Dice and CE Loss, no smoothing',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkBreastCancerPETFullAICELossCallback, ...
                          'position', [40 165 250 20]...
                          );
        
            chkBreastCancerPETFullAICELoss = ...
                uicontrol(dlgBreastCancerPETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningBreastCancerCELoss('get'),...
                          'position', [20 165 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkBreastCancerPETFullAICELossCallback...
                          );

            % Classify Segmentation
        
                uicontrol(dlgBreastCancerPETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Classify the Segmentation',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkBreastCancerPETFullAIClassifySegmentationCallback, ...
                          'position', [40 140 250 20]...
                          );
        
            chkBreastCancerPETFullAIClassifySegmentation = ...
                uicontrol(dlgBreastCancerPETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningBreastCancerClassifySegmentation('get'),...
                          'position', [20 140 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkBreastCancerPETFullAIClassifySegmentationCallback...
                          );

            % Smooth mask

                uicontrol(dlgBreastCancerPETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Smooth Mask',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'ButtonDownFcn'  , @chkBreastCancerPETFullAISmoothMaskCallback, ...
                          'position', [40 115 150 20]...
                          );

            chkBreastCancerPETFullAISmoothMask = ...
                uicontrol(dlgBreastCancerPETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningBreastCancerSmoothMask('get'),...
                          'position', [20 115 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'Callback', @chkBreastCancerPETFullAISmoothMaskCallback...
                          );
             % Pixel Edge
        
                uicontrol(dlgBreastCancerPETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Pixel Edge',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkBreastCancerPETFullAIPixelEdgeCallback, ...
                          'position', [40 90 150 20]...
                          );
        
            chkBreastCancerPETFullAIPixelEdge = ...
                uicontrol(dlgBreastCancerPETFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , pixelEdge('get'),...
                          'position', [20 90 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkBreastCancerPETFullAIPixelEdgeCallback...
                          );

            % Smallest Contour (ml)
        
                uicontrol(dlgBreastCancerPETFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'Smallest Contour (ml)',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 65 250 20]...
                          );
        
            edtBreastCancerPETFullAISmallestVoiValue = ...
                uicontrol(dlgBreastCancerPETFullAISegmentation, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 65 75 20], ...
                          'String'  , num2str(machineLearningBreastCancerSmallestVoiValue('get')), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtBreastCancerPETFullAISmallestVoiValueCallback ...
                          );  
        
             % Cancel or Proceed
        
             uicontrol(dlgBreastCancerPETFullAISegmentation,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelBreastCancerPETFullAISegmentationCallback...
                       );
        
             uicontrol(dlgBreastCancerPETFullAISegmentation,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedBreastCancerPETFullAISegmentationCallback...
                      );               
        else

            % Options

            tBreastCancerPETFullAI.options.CELossTrainer        = machineLearningBreastCancerCELoss('get');
            tBreastCancerPETFullAI.options.classifySegmentation = machineLearningBreastCancerClassifySegmentation('get');
            tBreastCancerPETFullAI.options.smoothMask           = machineLearningBreastCancerSmoothMask('get');
            tBreastCancerPETFullAI.options.smallestVoiValue     = machineLearningBreastCancerSmallestVoiValue('get');
            tBreastCancerPETFullAI.options.pixelEdge            = pixelEdge('get');
    
            setMachineLearningBreastCancerPETFullAI(sPredictScript, tBreastCancerPETFullAI); 
        end
    end

    function chkBreastCancerPETFullAICELossCallback(hObject, ~)

        bObjectValue = get(chkBreastCancerPETFullAICELoss, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkBreastCancerPETFullAICELoss, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkBreastCancerPETFullAICELoss, 'Value');

        machineLearningBreastCancerCELoss('set', bObjectValue);
    end

    function chkBreastCancerPETFullAIClassifySegmentationCallback(hObject, ~)

        bObjectValue = get(chkBreastCancerPETFullAIClassifySegmentation, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkBreastCancerPETFullAIClassifySegmentation, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkBreastCancerPETFullAIClassifySegmentation, 'Value');

        machineLearningBreastCancerClassifySegmentation('set', bObjectValue);
    end

    function chkBreastCancerPETFullAISmoothMaskCallback(hObject, ~)

        bObjectValue = get(chkBreastCancerPETFullAISmoothMask, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkBreastCancerPETFullAISmoothMask, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkBreastCancerPETFullAISmoothMask, 'Value');

        machineLearningBreastCancerSmoothMask('set', bObjectValue);
    end

    function edtBreastCancerPETFullAISmallestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtBreastCancerPETFullAISmallestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtBreastCancerPETFullAISmallestVoiValue, 'String', num2str(dObjectValue));
        end

        machineLearningBreastCancerSmallestVoiValue('set', dObjectValue);

    end

    function chkBreastCancerPETFullAIPixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkBreastCancerPETFullAIPixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkBreastCancerPETFullAIPixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkBreastCancerPETFullAIPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox

        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end

    function cancelBreastCancerPETFullAISegmentationCallback(~, ~)   

        delete(dlgBreastCancerPETFullAISegmentation);
    end
    
    function proceedBreastCancerPETFullAISegmentationCallback(~, ~)

        % Options

        tBreastCancerPETFullAI.options.CELossTrainer        =            get(chkBreastCancerPETFullAICELoss, 'Value');
        tBreastCancerPETFullAI.options.classifySegmentation =            get(chkBreastCancerPETFullAIClassifySegmentation, 'Value');
        tBreastCancerPETFullAI.options.smoothMask           =            get(chkBreastCancerPETFullAISmoothMask, 'Value');
        tBreastCancerPETFullAI.options.smallestVoiValue     = str2double(get(edtBreastCancerPETFullAISmallestVoiValue , 'String'));
        tBreastCancerPETFullAI.options.pixelEdge            =            get(chkBreastCancerPETFullAIPixelEdge, 'Value');

        delete(dlgBreastCancerPETFullAISegmentation);

        setMachineLearningBreastCancerPETFullAI(sPredictScript, tBreastCancerPETFullAI); 
    end

end