function setMachineLearningFDHTCallback(hObject, ~)
%function setMachineLearningFDHTCallback(hObject)
%Run FDHT SUV Tumor Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2023, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    [sSegmentatorScript, ~] = validateSegmentatorInstallation();

    dlgMachineLearningFDHT  = [];
  
    if ~isempty(sSegmentatorScript) % External Segmentor is installed

        if exist('hObject', 'var')

            DLG_FDHT_PERCENT_X = 380;
            DLG_FDHT_PERCENT_Y = 355;

            if viewerUIFigure('get') == true
        
                dlgMachineLearningFDHT = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_FDHT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_FDHT_PERCENT_Y/2) ...
                                        DLG_FDHT_PERCENT_X ...
                                        DLG_FDHT_PERCENT_Y ...
                                        ],...
                           'Resize', 'off', ...
                           'Color', viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name' , 'FDHT Machine Learning SUV Segmentation'...
                           );
            else          
                dlgMachineLearningFDHT = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_FDHT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_FDHT_PERCENT_Y/2) ...
                                        DLG_FDHT_PERCENT_X ...
                                        DLG_FDHT_PERCENT_Y ...
                                        ],...
                           'MenuBar', 'none',...
                           'Resize', 'off', ...    
                           'NumberTitle','off',...
                           'MenuBar', 'none',...
                           'Color', viewerBackgroundColor('get'), ...
                           'Name', 'FDHT Machine Learning SUV Segmentation',...
                           'Toolbar','none'...               
                           );    
            end

            setObjectIcon(dlgMachineLearningFDHT);

            % Exclude organs from AI analysis
    
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'text',...
                      'FontWeight','bold'  ,...
                      'string'  , 'Exclude organs from AI analysis',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 315 300 20]...
                      );
    
        % Brain
    
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Brain',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkFDHTBrainCallback, ...
                      'position', [60 290 150 20]...
                      );
    
        chkFDHTBrain = ...
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeFDHTBrain('get'),...
                      'position', [40 290 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkFDHTBrainCallback...
                      );
    
        % Spleen
    
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Spleen',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkFDHTSpleenCallback, ...
                      'position', [60 265 150 20]...
                      );
    
        chkFDHTSpleen = ...
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeFDHTSpleen('get'),...
                      'position', [40 265 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkFDHTSpleenCallback...
                      );
    
        % Kidney left
    
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Kidney left',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkFDHTKidneyLeftCallback, ...
                      'position', [60 240 150 20]...
                      );
    
        chkFDHTKidneyLeft = ...
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeFDHTKidneyLeft('get'),...
                      'position', [40 240 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkFDHTKidneyLeftCallback...
                      );
    
        % Kidney right
    
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Kidney right',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkFDHTKidneyRightCallback, ...
                      'position', [60 215 150 20]...
                      );
    
        chkFDHTKidneyRight = ...
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeFDHTKidneyRight('get'),...
                      'position', [40 215 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkFDHTKidneyRightCallback...
                      );
        
        % Small bowel
    
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Small bowel',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkFDHTSmallBowelCallback, ...
                      'position', [60 190 150 20]...
                      );
    
        chkFDHTSmallBowel = ...
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeFDHTSmallBowel('get'),...
                      'position', [40 190 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkFDHTSmallBowelCallback...
                      );
    
        % Urinary bladder
    
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Urinary bladder',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkFDHTUrinaryBladderCallback, ...
                      'position', [60 165 150 20]...
                      );
    
        chkFDHTUrinaryBladder = ...
            uicontrol(dlgMachineLearningFDHT,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeFDHTUrinaryBladder('get'),...
                      'position', [40 165 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkFDHTUrinaryBladderCallback...
                      );
    
        % Options
    
            uicontrol(dlgMachineLearningFDHT,...
                      'style'     , 'text',...
                      'FontWeight','bold'  ,...
                      'string'    , 'Options',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 115 300 20]...
                      );    
    
             % Pixel Edge
        
                uicontrol(dlgMachineLearningFDHT,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Pixel Edge',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkFDHTPixelEdgeCallback, ...
                          'position', [40 90 150 20]...
                          );
        
            chkFDHTPixelEdge = ...
                uicontrol(dlgMachineLearningFDHT,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , pixelEdge('get'),...
                          'position', [20 90 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkFDHTPixelEdgeCallback...
                          );
        
            % Smallest Contour (ml)
        
                uicontrol(dlgMachineLearningFDHT,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'Smallest Contour (ml)',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 65 250 20]...
                          );
        
            edtFDHTSmalestVoiValue = ...
                uicontrol(dlgMachineLearningFDHT, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 65 75 20], ...
                          'String'  , num2str(FDHTSmalestVoiValue('get')), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtFDHTSmalestVoiValueCallback ...
                          );  
        
             % Cancel or Proceed
        
             uicontrol(dlgMachineLearningFDHT,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelMachineLearningFDHTCallback...
                       );
        
             uicontrol(dlgMachineLearningFDHT,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedMachineLearningFDHTCallback...
                      );   
        else

            % Exclude List
    
            % Other Organs
    
            tFDHT.exclude.organ.brain       = excludeFDHTBrain('get');
            tFDHT.exclude.organ.kidneyLeft  = excludeFDHTKidneyLeft('get');
            tFDHT.exclude.organ.kidneyRight = excludeFDHTKidneyRight('get');
            tFDHT.exclude.organ.spleen      = excludeFDHTSpleen('get');
    
            % Gastrointestinal Tract Name
    
            tFDHT.exclude.gastrointestinal.smallBowel     = excludeFDHTSmallBowel('get');
            tFDHT.exclude.gastrointestinal.urinaryBladder = excludeFDHTUrinaryBladder('get');
    
            % Options
    
            tFDHT.options.smalestVoiValue = FDHTSmalestVoiValue('get');
            tFDHT.options.pixelEdge       = pixelEdge('get');
    
            setMachineLearningFDHT(sSegmentatorScript, tFDHT);     
        end
    end

    % Exclude organs from AI analysis

    % Brain

    function chkFDHTBrainCallback(hObject, ~)  
                
        bObjectValue = get(chkFDHTBrain, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDHTBrain, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDHTBrain, 'Value');

        excludeFDHTBrain('set', bObjectValue);

    end

    % Kidney Left

    function chkFDHTKidneyLeftCallback(hObject, ~)  
                
        bObjectValue = get(chkFDHTKidneyLeft, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDHTKidneyLeft, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDHTKidneyLeft, 'Value');

        excludeFDHTKidneyLeft('set', bObjectValue);

    end

    % Kidney Right

    function chkFDHTKidneyRightCallback(hObject, ~)  
                
        bObjectValue = get(chkFDHTKidneyRight, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDHTKidneyRight, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDHTKidneyRight, 'Value');

        excludeFDHTKidneyRight('set', bObjectValue);

    end

    % Small Bowel

    function chkFDHTSmallBowelCallback(hObject, ~)  
                
        bObjectValue = get(chkFDHTSmallBowel, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDHTSmallBowel, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDHTSmallBowel, 'Value');

        excludeFDHTSmallBowel('set', bObjectValue);

    end


    % Spleen

    function chkFDHTSpleenCallback(hObject, ~)  
                
        bObjectValue = get(chkFDHTSpleen, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDHTSpleen, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDHTSpleen, 'Value');

        excludeFDHTSpleen('set', bObjectValue);

    end

    function edtFDHTSmalestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtFDHTSmalestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtFDHTSmalestVoiValue, 'String', num2str(dObjectValue));
        end

        FDHTSmalestVoiValue('set', dObjectValue);

    end

    function chkFDHTPixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkFDHTPixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkFDHTPixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkFDHTPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox

        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end


    function cancelMachineLearningFDHTCallback(~, ~)   

        delete(dlgMachineLearningFDHT);
    end
    
    function proceedMachineLearningFDHTCallback(~, ~)

        % Exclude List

        % Other Organs

        tFDHT.exclude.organ.brain       = get(chkFDHTBrain      , 'value');
        tFDHT.exclude.organ.kidneyLeft  = get(chkFDHTKidneyLeft , 'value');
        tFDHT.exclude.organ.kidneyRight = get(chkFDHTKidneyRight, 'value');
        tFDHT.exclude.organ.spleen      = get(chkFDHTSpleen, 'value');

        % Gastrointestinal Tract Name

        tFDHT.exclude.gastrointestinal.smallBowel     = get(chkFDHTSmallBowel    , 'value');
        tFDHT.exclude.gastrointestinal.urinaryBladder = get(chkFDHTUrinaryBladder, 'value');

        % Options

        tFDHT.options.smalestVoiValue = str2double(get(edtFDHTSmalestVoiValue    , 'String'));
        tFDHT.options.pixelEdge       = get(chkFDHTPixelEdge                     , 'value');

        delete(dlgMachineLearningFDHT);

        setMachineLearningFDHT(sSegmentatorScript, tFDHT); 
    end
    
end