function setMachineLearningPSMAGa68PETCTFullAICallback(hObject, ~)
%function setMachineLearningPSMAGa68PETCTFullAICallback()
%Run PSMA Ga68 PT/CT Full AI Tumor Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2024, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    [sPredictScript] = validateNnUNetv2Installation();
    
    dlgPSMAGa68PETCTFullAISegmentation  = [];
  
    if ~isempty(sPredictScript) ... % External Segmentor is installed

        if exist('hObject', 'var')

            DLG_PSMA_Ga68_PETCT_PERCENT_X = 380;
            DLG_PSMA_Ga68_PETCT_PERCENT_Y = 215;

            if viewerUIFigure('get') == true
        
                dlgPSMAGa68PETCTFullAISegmentation = ...
                    uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_PSMA_Ga68_PETCT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_PSMA_Ga68_PETCT_PERCENT_Y/2) ...
                                        DLG_PSMA_Ga68_PETCT_PERCENT_X ...
                                        DLG_PSMA_Ga68_PETCT_PERCENT_Y ...
                                        ],...
                           'Resize', 'off', ...
                           'Color', viewerBackgroundColor('get'),...
                           'WindowStyle', 'modal', ...
                           'Name' , 'PSMA Ga68 Machine Learning Full AI PET CT Segmentation'...
                           );
            else       
                dlgPSMAGa68PETCTFullAISegmentation = ...
                    dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_PSMA_Ga68_PETCT_PERCENT_X/2) ...
                                        (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_PSMA_Ga68_PETCT_PERCENT_Y/2) ...
                                        DLG_PSMA_Ga68_PETCT_PERCENT_X ...
                                        DLG_PSMA_Ga68_PETCT_PERCENT_Y ...
                                        ],...
                           'MenuBar', 'none',...
                           'Resize', 'off', ...    
                           'NumberTitle','off',...
                           'MenuBar', 'none',...
                           'Color', viewerBackgroundColor('get'), ...
                           'Name', 'PSMA Ga68 Machine Learning Full AI PET CT Segmentation',...
                           'Toolbar','none'...               
                           );    
            end

            % Trainer with Dice and CE Loss
        
                uicontrol(dlgPSMAGa68PETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Trainer with Dice and CE Loss, no smoothing',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkPSMAGa68PETCTFullAICELossCallback, ...
                          'position', [40 165 250 20]...
                          );
        
            chkPSMAGa68PETCTFullAICELoss = ...
                uicontrol(dlgPSMAGa68PETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningPSMAGa68CELoss('get'),...
                          'position', [20 165 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkPSMAGa68PETCTFullAICELossCallback...
                          );

            % Classify Segmentation
        
                uicontrol(dlgPSMAGa68PETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Classify the Segmentation',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkPSMAGa68PETCTFullAIClassifySegmentationCallback, ...
                          'position', [40 140 250 20]...
                          );
        
            chkPSMAGa68PETCTFullAIClassifySegmentation = ...
                uicontrol(dlgPSMAGa68PETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningPSMAGa68ClassifySegmentation('get'),...
                          'position', [20 140 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkPSMAGa68PETCTFullAIClassifySegmentationCallback...
                          );

            % Smooth mask

                uicontrol(dlgPSMAGa68PETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Smooth Mask',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'ButtonDownFcn'  , @chkPSMAGa68PETCTFullAISmoothMaskCallback, ...
                          'position', [40 115 150 20]...
                          );

            chkPSMAGa68PETCTFullAISmoothMask = ...
                uicontrol(dlgPSMAGa68PETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , machineLearningPSMAGa68SmoothMask('get'),...
                          'position', [20 115 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'Callback', @chkPSMAGa68PETCTFullAISmoothMaskCallback...
                          );
             % Pixel Edge
        
                uicontrol(dlgPSMAGa68PETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'Inactive',...
                          'string'  , 'Pixel Edge',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'ButtonDownFcn'  , @chkPSMAGa68PETCTFullAIPixelEdgeCallback, ...
                          'position', [40 90 150 20]...
                          );
        
            chkPSMAGa68PETCTFullAIPixelEdge = ...
                uicontrol(dlgPSMAGa68PETCTFullAISegmentation,...
                          'style'   , 'checkbox',...
                          'enable'  , 'on',...
                          'value'   , pixelEdge('get'),...
                          'position', [20 90 20 20],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'Callback', @chkPSMAGa68PETCTFullAIPixelEdgeCallback...
                          );

            % Smallest Contour (ml)
        
                uicontrol(dlgPSMAGa68PETCTFullAISegmentation,...
                          'style'   , 'text',...
                          'Enable'  , 'On',...
                          'string'  , 'Smallest Contour (ml)',...
                          'horizontalalignment', 'left',...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...                   
                          'position', [20 65 250 20]...
                          );
        
            edtPSMAGa68PETCTFullAISmallestVoiValue = ...
                uicontrol(dlgPSMAGa68PETCTFullAISegmentation, ...
                          'Style'   , 'Edit', ...
                          'Position', [285 65 75 20], ...
                          'String'  , num2str(machineLearningPSMAGa68SmallestVoiValue('get')), ...
                          'Enable'  , 'on', ...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...
                          'CallBack', @edtPSMAGa68PETCTFullAISmallestVoiValueCallback ...
                          );  
        
             % Cancel or Proceed
        
             uicontrol(dlgPSMAGa68PETCTFullAISegmentation,...
                       'String','Cancel',...
                       'Position',[285 7 75 25],...
                       'BackgroundColor', viewerBackgroundColor('get'), ...
                       'ForegroundColor', viewerForegroundColor('get'), ...                
                       'Callback', @cancelPSMAGa68PETCTFullAISegmentationCallback...
                       );
        
             uicontrol(dlgPSMAGa68PETCTFullAISegmentation,...
                      'String','Proceed',...
                      'Position',[200 7 75 25],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...               
                      'Callback', @proceedPSMAGa68PETCTFullAISegmentationCallback...
                      );               
        else

            % Options

            tPSMAGa68PETCTFullAI.options.CELossTrainer        = machineLearningPSMAGa68CELoss('get');
            tPSMAGa68PETCTFullAI.options.classifySegmentation = machineLearningPSMAGa68ClassifySegmentation('get');
            tPSMAGa68PETCTFullAI.options.smoothMask           = machineLearningPSMAGa68SmoothMask('get');
            tPSMAGa68PETCTFullAI.options.smallestVoiValue     = machineLearningPSMAGa68SmallestVoiValue('get');
            tPSMAGa68PETCTFullAI.options.pixelEdge            = pixelEdge('get');
    
            setMachineLearningPSMAGa68PETCTFullAI(sPredictScript, tPSMAGa68PETCTFullAI); 
        end
    end

    function chkPSMAGa68PETCTFullAICELossCallback(hObject, ~)

        bObjectValue = get(chkPSMAGa68PETCTFullAICELoss, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkPSMAGa68PETCTFullAICELoss, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkPSMAGa68PETCTFullAICELoss, 'Value');

        machineLearningPSMAGa68CELoss('set', bObjectValue);
    end

    function chkPSMAGa68PETCTFullAIClassifySegmentationCallback(hObject, ~)

        bObjectValue = get(chkPSMAGa68PETCTFullAIClassifySegmentation, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkPSMAGa68PETCTFullAIClassifySegmentation, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkPSMAGa68PETCTFullAIClassifySegmentation, 'Value');

        machineLearningPSMAGa68ClassifySegmentation('set', bObjectValue);
    end

    function chkPSMAGa68PETCTFullAISmoothMaskCallback(hObject, ~)

        bObjectValue = get(chkPSMAGa68PETCTFullAISmoothMask, 'Value');

        if strcmpi(get(hObject, 'Style'), 'text')

            set(chkPSMAGa68PETCTFullAISmoothMask, 'Value', ~bObjectValue);
        end

        bObjectValue = get(chkPSMAGa68PETCTFullAISmoothMask, 'Value');

        machineLearningPSMAGa68SmoothMask('set', bObjectValue);
    end

    function edtPSMAGa68PETCTFullAISmallestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtPSMAGa68PETCTFullAISmallestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtPSMAGa68PETCTFullAISmallestVoiValue, 'String', num2str(dObjectValue));
        end

        machineLearningPSMAGa68SmallestVoiValue('set', dObjectValue);

    end

    function chkPSMAGa68PETCTFullAIPixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkPSMAGa68PETCTFullAIPixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkPSMAGa68PETCTFullAIPixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkPSMAGa68PETCTFullAIPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox

        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end

    function cancelPSMAGa68PETCTFullAISegmentationCallback(~, ~)   

        delete(dlgPSMAGa68PETCTFullAISegmentation);
    end
    
    function proceedPSMAGa68PETCTFullAISegmentationCallback(~, ~)

        % Options

        tPSMAGa68PETCTFullAI.options.CELossTrainer        =            get(chkPSMAGa68PETCTFullAICELoss, 'Value');
        tPSMAGa68PETCTFullAI.options.classifySegmentation =            get(chkPSMAGa68PETCTFullAIClassifySegmentation, 'Value');
        tPSMAGa68PETCTFullAI.options.smoothMask           =            get(chkPSMAGa68PETCTFullAISmoothMask, 'Value');
        tPSMAGa68PETCTFullAI.options.smallestVoiValue     = str2double(get(edtPSMAGa68PETCTFullAISmallestVoiValue , 'String'));

        delete(dlgPSMAGa68PETCTFullAISegmentation);

        setMachineLearningPSMAGa68PETCTFullAI(sPredictScript, tPSMAGa68PETCTFullAI); 
    end

end