function setMachineLearningGa68DOTATATECallback(hObject, ~)
%function setMachineLearningGa68DOTATATECallback(hObject)
%Run machine learning Ga68 DOTATATE Segmentation, The tool is called from the main menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2023, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    [sSegmentatorScript, ~] = validateSegmentatorInstallation();

    dlgGa68DOTATATE  = [];
  
    if ~isempty(sSegmentatorScript) % External Segmentor is installed
        
        if exist('hObject', 'var')
    
            DLG_Ga68DOTATATE_X = 380;
            DLG_Ga68DOTATATE_Y = 650;
        
            dlgGa68DOTATATE = ...
                dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_Ga68DOTATATE_X/2) ...
                                    (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_Ga68DOTATATE_Y/2) ...
                                    DLG_Ga68DOTATATE_X ...
                                    DLG_Ga68DOTATATE_Y ...
                                    ],...
                       'MenuBar', 'none',...
                       'Resize', 'off', ...    
                       'NumberTitle','off',...
                       'MenuBar', 'none',...
                       'Color', viewerBackgroundColor('get'), ...
                       'Name', 'Ga68 DOTATATE Machine Learning Segmentation',...
                       'Toolbar','none'...               
                       );           
                   
                axes(dlgGa68DOTATATE, ...
                     'Units'   , 'pixels', ...
                     'Position', [0 0 DLG_Ga68DOTATATE_X DLG_Ga68DOTATATE_Y], ...
                     'Color'   , viewerBackgroundColor('get'),...
                     'XColor'  , viewerForegroundColor('get'),...
                     'YColor'  , viewerForegroundColor('get'),...
                     'ZColor'  , viewerForegroundColor('get'),...             
                     'Visible' , 'off'...             
                     ); 
        
        % Other Organs
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'FontWeight','bold'  ,...
                      'string'  , 'Exclude organ list',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 615 300 20]...
                      );
    
        % Brain
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Brain',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEBrainCallback, ...
                      'position', [60 587 150 20]...
                      );
    
        chkGa68DOTATATEBrain = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATEBrain('get'),...
                      'position', [40 590 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEBrainCallback...
                      );
    
        % Trachea
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Trachea',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATETracheaCallback, ...
                      'position', [60 562 150 20]...
                      );
    
        chkGa68DOTATATETrachea = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATETrachea('get'),...
                      'position', [40 565 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATETracheaCallback...
                      );
        
        % Adrenal gland left
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Adrenal gland left',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEAdrenalGlandLeftCallback, ...
                      'position', [60 537 150 20]...
                      );
    
        chkGa68DOTATATEAdrenalGlandLeft = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATEAdrenalGlandLeft('get'),...
                      'position', [40 540 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEAdrenalGlandLeftCallback...
                      );
    
        % Adrenal gland right
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Adrenal gland right',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEAdrenalGlandRightCallback, ...
                      'position', [60 512 150 20]...
                      );
    
        chkGa68DOTATATEAdrenalGlandRight = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATEAdrenalGlandRight('get'),...
                      'position', [40 515 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEAdrenalGlandRightCallback...
                      );
    
        % Spleen
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Spleen',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATESpleenCallback, ...
                      'position', [60 487 150 20]...
                      );
    
        chkGa68DOTATATESpleen = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATESpleen('get'),...
                      'position', [40 490 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATESpleenCallback...
                      );
    
        % Gallbladder
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Gallbladder',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEGallbladderCallback, ...
                      'position', [60 462 150 20]...
                      );
    
        chkGa68DOTATATEGallbladder = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATEGallbladder('get'),...
                      'position', [40 465 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEGallbladderCallback...
                      );
    
        % Pancreas
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Pancreas',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEPancreasCallback, ...
                      'position', [60 437 150 20]...
                      );
    
        chkGa68DOTATATEPancreas = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATEPancreas('get'),...
                      'position', [40 440 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEPancreasCallback...
                      );
    
        % Kidney left
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Kidney left',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEKidneyLeftCallback, ...
                      'position', [60 412 150 20]...
                      );
    
        chkGa68DOTATATEKidneyLeft = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATEKidneyLeft('get'),...
                      'position', [40 415 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEKidneyLeftCallback...
                      );
    
        % Kidney right
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Kidney right',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEKidneyRightCallback, ...
                      'position', [60 387 150 20]...
                      );
    
        chkGa68DOTATATEKidneyRight = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATEKidneyRight('get'),...
                      'position', [40 390 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEKidneyRightCallback...
                      );
    
        % Gastrointestinal Tract Name
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'FontWeight','bold'  ,...
                      'string'  , 'Exclude gastrointestinal tract list',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 340 300 20]...
                      );
        % Esophagus
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Esophagus',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEEsophagusCallback, ...
                      'position', [60 312 150 20]...
                      );
    
        chkGa68DOTATATEEsophagus = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATEEsophagus('get'),...
                      'position', [40 315 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEEsophagusCallback...
                      );
    
        % Stomach
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Stomach',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEStomachCallback, ...
                      'position', [60 287 150 20]...
                      );
    
        chkGa68DOTATATEStomach = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATEStomach('get'),...
                      'position', [40 290 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEStomachCallback...
                      );
    
        % Duodenum
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Duodenum',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEDuodenumCallback, ...
                      'position', [60 262 150 20]...
                      );
    
        chkGa68DOTATATEDuodenum = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATEDuodenum('get'),...
                      'position', [40 265 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEDuodenumCallback...
                      );
    
        % Small bowel
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Small bowel',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATESmallBowelCallback, ...
                      'position', [60 237 150 20]...
                      );
    
        chkGa68DOTATATESmallBowel = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATESmallBowel('get'),...
                      'position', [40 240 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATESmallBowelCallback...
                      );
    
        % Colon
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Colon',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEColonCallback, ...
                      'position', [60 212 150 20]...
                      );
    
        chkGa68DOTATATEColon = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATEColon('get'),...
                      'position', [40 215 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEColonCallback...
                      );
    
        % Urinary bladder
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Urinary bladder',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEUrinaryBladderCallback, ...
                      'position', [60 187 150 20]...
                      );
    
        chkGa68DOTATATEUrinaryBladder = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , excludeGa68DOTATATEUrinaryBladder('get'),...
                      'position', [40 190 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEUrinaryBladderCallback...
                      );
    
        % Options
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'FontWeight','bold'  ,...
                      'string'  , 'Options',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 140 300 20]...
                      );
    
        % Smallest Contour (ml)
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Smallest Contour (ml)',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 112 250 20]...
                      );
    
        edtGa68DOTATATESmalestVoiValue = ...
            uicontrol(dlgGa68DOTATATE, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 115 75 20], ...
                      'String'  , num2str(Ga68DOTATATESmalestVoiValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtGa68DOTATATESmalestVoiValueCallback ...
                      );        
    
        % Pixel Edge
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'Inactive',...
                      'string'  , 'Pixel Edge',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'ButtonDownFcn'  , @chkGa68DOTATATEPixelEdgeCallback, ...
                      'position', [40 87 150 20]...
                      );
    
        chkGa68DOTATATEPixelEdge = ...
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'checkbox',...
                      'enable'  , 'on',...
                      'value'   , pixelEdge('get'),...
                      'position', [20 90 20 20],...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'Callback', @chkGa68DOTATATEPixelEdgeCallback...
                      );
    
        % Normal Liver Treshold Multiplier
    
            uicontrol(dlgGa68DOTATATE,...
                      'style'   , 'text',...
                      'Enable'  , 'On',...
                      'string'  , 'Normal Liver Treshold Multiplier',...
                      'horizontalalignment', 'left',...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...                   
                      'position', [20 62 250 20]...
                      );
    
        edtGa68DOTATATENormalLiverTresholdMultiplierValue = ...
            uicontrol(dlgGa68DOTATATE, ...
                      'Style'   , 'Edit', ...
                      'Position', [285 65 75 20], ...
                      'String'  , num2str(Ga68DOTATATENormalLiverTresholdMultiplierValue('get')), ...
                      'Enable'  , 'on', ...
                      'BackgroundColor', viewerBackgroundColor('get'), ...
                      'ForegroundColor', viewerForegroundColor('get'), ...
                      'CallBack', @edtGa68DOTATATENormalLiverTresholdMultiplierValueCallback ...
                      );  
    
                 % Cancel or Proceed
            
                 uicontrol(dlgGa68DOTATATE,...
                           'String','Cancel',...
                           'Position',[285 7 75 25],...
                           'BackgroundColor', viewerBackgroundColor('get'), ...
                           'ForegroundColor', viewerForegroundColor('get'), ...                
                           'Callback', @cancelGa68DOTATATECallback...
                           );
            
                 uicontrol(dlgGa68DOTATATE,...
                          'String','Proceed',...
                          'Position',[200 7 75 25],...
                          'BackgroundColor', viewerBackgroundColor('get'), ...
                          'ForegroundColor', viewerForegroundColor('get'), ...               
                          'Callback', @proceedGa68DOTATATECallback...
                          );
        else

            % Exclusion

            % Other Organs
    
            tGa68DOTATATE.exclude.organ.brain             = excludeGa68DOTATATEBrain('get');
            tGa68DOTATATE.exclude.organ.trachea           = excludeGa68DOTATATETrachea('get');
            tGa68DOTATATE.exclude.organ.adrenalGlandLeft  = excludeGa68DOTATATEAdrenalGlandLeft('get');
            tGa68DOTATATE.exclude.organ.adrenalGlandRight = excludeGa68DOTATATEAdrenalGlandRight('get');
            tGa68DOTATATE.exclude.organ.spleen            = excludeGa68DOTATATESpleen('get');
            tGa68DOTATATE.exclude.organ.gallbladder       = excludeGa68DOTATATEGallbladder('get');
            tGa68DOTATATE.exclude.organ.pancreas          = excludeGa68DOTATATEPancreas('get');
            tGa68DOTATATE.exclude.organ.kidneyLeft        = excludeGa68DOTATATEKidneyLeft('get');
            tGa68DOTATATE.exclude.organ.kidneyRight       = excludeGa68DOTATATEKidneyRight('get');
    
            % Gastrointestinal Tract Name
    
            tGa68DOTATATE.exclude.gastrointestinal.esophagus      = excludeGa68DOTATATEEsophagus('get');
            tGa68DOTATATE.exclude.gastrointestinal.stomach        = excludeGa68DOTATATEStomach('get');
            tGa68DOTATATE.exclude.gastrointestinal.duodenum       = excludeGa68DOTATATEDuodenum('get');
            tGa68DOTATATE.exclude.gastrointestinal.smallBowel     = excludeGa68DOTATATESmallBowel('get');
            tGa68DOTATATE.exclude.gastrointestinal.colon          = excludeGa68DOTATATEColon('get');
            tGa68DOTATATE.exclude.gastrointestinal.urinaryBladder = excludeGa68DOTATATEUrinaryBladder('get');
    
            tGa68DOTATATE.options.smalestVoiValue               = Ga68DOTATATESmalestVoiValue('get');
            tGa68DOTATATE.options.pixelEdge                     = pixelEdge('get');
            tGa68DOTATATE.options.normalLiverTresholdMultiplier = Ga68DOTATATENormalLiverTresholdMultiplierValue('get');
            
            setMachineLearningGa68DOTATATE(sSegmentatorScript, tGa68DOTATATE, true);            
        end

    end

    % Other Organs

    % Brain

    function chkGa68DOTATATEBrainCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEBrain, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEBrain, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEBrain, 'Value');

        excludeGa68DOTATATEBrain('set', bObjectValue);

    end

    % Trachea

    function chkGa68DOTATATETracheaCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATETrachea, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATETrachea, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATETrachea, 'Value');

        excludeGa68DOTATATETrachea('set', bObjectValue);

    end

    % Adrenal Gland Left

    function chkGa68DOTATATEAdrenalGlandLeftCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEAdrenalGlandLeft, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEAdrenalGlandLeft, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEAdrenalGlandLeft, 'Value');

        excludeGa68DOTATATEAdrenalGlandLeft('set', bObjectValue);

    end

    % Adrenal Gland Right

    function chkGa68DOTATATEAdrenalGlandRightCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEAdrenalGlandRight, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEAdrenalGlandRight, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEAdrenalGlandRight, 'Value');

        excludeGa68DOTATATEAdrenalGlandRight('set', bObjectValue);

    end

    % Spleen

    function chkGa68DOTATATESpleenCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATESpleen, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATESpleen, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATESpleen, 'Value');

        excludeGa68DOTATATESpleen('set', bObjectValue);

    end

    % Gallbladder

    function chkGa68DOTATATEGallbladderCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEGallbladder, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEGallbladder, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEGallbladder, 'Value');

        excludeGa68DOTATATEGallbladder('set', bObjectValue);

    end

    % Pancreas

    function chkGa68DOTATATEPancreasCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEPancreas, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEPancreas, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEPancreas, 'Value');

        excludeGa68DOTATATEPancreas('set', bObjectValue);

    end

    % Kidney Left

    function chkGa68DOTATATEKidneyLeftCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEKidneyLeft, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEKidneyLeft, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEKidneyLeft, 'Value');

        excludeGa68DOTATATEKidneyLeft('set', bObjectValue);

    end

    % Kidney Right

    function chkGa68DOTATATEKidneyRightCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEKidneyRight, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEKidneyRight, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEKidneyRight, 'Value');

        excludeGa68DOTATATEKidneyRight('set', bObjectValue);

    end

    % Gastrointestinal Tract Name

    % Esophagus

    function chkGa68DOTATATEEsophagusCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEEsophagus, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEEsophagus, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEEsophagus, 'Value');

        excludeGa68DOTATATEEsophagus('set', bObjectValue);

    end

    % Stomach

    function chkGa68DOTATATEStomachCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEStomach, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEStomach, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEStomach, 'Value');

        excludeGa68DOTATATEStomach('set', bObjectValue);

    end

    % Duodenum

    function chkGa68DOTATATEDuodenumCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEDuodenum, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEDuodenum, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEDuodenum, 'Value');

        excludeGa68DOTATATEDuodenum('set', bObjectValue);

    end

    % Small Bowel

    function chkGa68DOTATATESmallBowelCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATESmallBowel, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATESmallBowel, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATESmallBowel, 'Value');

        excludeGa68DOTATATESmallBowel('set', bObjectValue);

    end

    % Colon

    function chkGa68DOTATATEColonCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEColon, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEColon, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEColon, 'Value');

        excludeGa68DOTATATEColon('set', bObjectValue);

    end

    % Urinary Bladder

    function chkGa68DOTATATEUrinaryBladderCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEUrinaryBladder, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEUrinaryBladder, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEUrinaryBladder, 'Value');

        excludeGa68DOTATATEUrinaryBladder('set', bObjectValue);

    end

    function edtGa68DOTATATESmalestVoiValueCallback(~, ~)

        dObjectValue = str2double(get(edtGa68DOTATATESmalestVoiValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 0;

            set(edtGa68DOTATATESmalestVoiValue, 'String', num2str(dObjectValue));
        end

        Ga68DOTATATESmalestVoiValue('set', dObjectValue);

    end

    function edtGa68DOTATATENormalLiverTresholdMultiplierValueCallback(~, ~)

        dObjectValue = str2double(get(edtGa68DOTATATENormalLiverTresholdMultiplierValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 1;

            set(edtGa68DOTATATENormalLiverTresholdMultiplierValue, 'String', num2str(dObjectValue));
        end

        Ga68DOTATATENormalLiverTresholdMultiplierValue('set', dObjectValue);

    end


    function chkGa68DOTATATEPixelEdgeCallback(hObject, ~)  
                
        bObjectValue = get(chkGa68DOTATATEPixelEdge, 'Value');
        
        if strcmpi(get(hObject, 'Style'), 'text')
            
            set(chkGa68DOTATATEPixelEdge, 'Value', ~bObjectValue);
        end        
        
        bObjectValue = get(chkGa68DOTATATEPixelEdge, 'Value');

        pixelEdge('set', bObjectValue);
        
        % Set contour panel checkbox
        set(chkPixelEdgePtr('get'), 'Value', pixelEdge('get'));
    end


    % Cancel

    function cancelGa68DOTATATECallback(~, ~)
    
        delete(dlgGa68DOTATATE);
    end

    % Proceed
    
    function proceedGa68DOTATATECallback(~, ~)

        % Other Organs

        tGa68DOTATATE.exclude.organ.brain             = get(chkGa68DOTATATEBrain            , 'value');
        tGa68DOTATATE.exclude.organ.trachea           = get(chkGa68DOTATATETrachea          , 'value');
        tGa68DOTATATE.exclude.organ.adrenalGlandLeft  = get(chkGa68DOTATATEAdrenalGlandLeft , 'value');
        tGa68DOTATATE.exclude.organ.adrenalGlandRight = get(chkGa68DOTATATEAdrenalGlandRight, 'value');
        tGa68DOTATATE.exclude.organ.spleen            = get(chkGa68DOTATATESpleen           , 'value');
        tGa68DOTATATE.exclude.organ.gallbladder       = get(chkGa68DOTATATEGallbladder      , 'value');
        tGa68DOTATATE.exclude.organ.pancreas          = get(chkGa68DOTATATEPancreas         , 'value');
        tGa68DOTATATE.exclude.organ.kidneyLeft        = get(chkGa68DOTATATEKidneyLeft       , 'value');
        tGa68DOTATATE.exclude.organ.kidneyRight       = get(chkGa68DOTATATEKidneyRight      , 'value');

        % Gastrointestinal Tract Name

        tGa68DOTATATE.exclude.gastrointestinal.esophagus      = get(chkGa68DOTATATEEsophagus     , 'value');
        tGa68DOTATATE.exclude.gastrointestinal.stomach        = get(chkGa68DOTATATEStomach       , 'value');
        tGa68DOTATATE.exclude.gastrointestinal.duodenum       = get(chkGa68DOTATATEDuodenum      , 'value');
        tGa68DOTATATE.exclude.gastrointestinal.smallBowel     = get(chkGa68DOTATATESmallBowel    , 'value');
        tGa68DOTATATE.exclude.gastrointestinal.colon          = get(chkGa68DOTATATEColon         , 'value');
        tGa68DOTATATE.exclude.gastrointestinal.urinaryBladder = get(chkGa68DOTATATEUrinaryBladder, 'value');

        tGa68DOTATATE.options.smalestVoiValue               = str2double(get(edtGa68DOTATATESmalestVoiValue, 'String'));
        tGa68DOTATATE.options.pixelEdge                     = get(chkGa68DOTATATEPixelEdge, 'value');
        tGa68DOTATATE.options.normalLiverTresholdMultiplier = str2double(get(edtGa68DOTATATENormalLiverTresholdMultiplierValue, 'String'));
        
        delete(dlgGa68DOTATATE);

        setMachineLearningGa68DOTATATE(sSegmentatorScript, tGa68DOTATATE, false);
    end

end