function setOneWindowPosition(uiOneWindow)
%function setOneWindowPosition(uiOneWindow)
%Set One Window position.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2023, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    uiSegMainPanel    = uiSegMainPanelPtr('get');
    uiKernelMainPanel = uiKernelMainPanelPtr('get');
    uiRoiMainPanel    = uiRoiMainPanelPtr('get');

    if switchTo3DMode('get')     == true || ...
       switchToIsoSurface('get') == true || ...
       switchToMIPMode('get')    == true

        ui3DGateWindow = ui3DGateWindowObject('get');

        if view3DPanel('get') == false
            set(uiOneWindow, ...
                'position', [0 ...
                             addOnWidth('get')+30 ...
                             getMainWindowSize('xsize') ...
                             getMainWindowSize('ysize')-viewerToolbarHeight('get')-viewerTopBarHeight('get')-addOnWidth('get')-30 ...
                             ]...
               );    

            if ~isempty(ui3DGateWindow)
                for ww=1:numel(ui3DGateWindow)
                    set(ui3DGateWindow{ww}, ...
                        'position', [0 ...
                                     addOnWidth('get')+30 ...
                                     getMainWindowSize('xsize') ...
                                     getMainWindowSize('ysize')-viewerToolbarHeight('get')-viewerTopBarHeight('get')-addOnWidth('get')-30 ...
                                     ]...
                       );  
                end
           end
        else
            set(uiOneWindow, ...
                'position', [680 ...
                             addOnWidth('get')+30 ...
                             getMainWindowSize('xsize')-680 ...
                             getMainWindowSize('ysize')-viewerToolbarHeight('get')-viewerTopBarHeight('get')-addOnWidth('get')-30 ...
                             ]...
               );   

            if ~isempty(ui3DGateWindow)
                for ww=1:numel(ui3DGateWindow)
                    set(ui3DGateWindow{ww}, ...
                        'position', [680 ...
                                     addOnWidth('get')+30 ...
                                     getMainWindowSize('xsize')-680 ...
                                     getMainWindowSize('ysize')-viewerToolbarHeight('get')-viewerTopBarHeight('get')-addOnWidth('get')-30 ...
                                     ]...
                       );                                  
                end
            end
        end
         
        ptrViewer3d = viewer3dObject('get');
        if ~isempty(ptrViewer3d)

            uiOneWindowPosition = get(uiOneWindow, 'Position');

            xOffset = uiOneWindowPosition(1);
            yOffset = 0;
            xSize   = uiOneWindowPosition(3);
            ySize   = uiOneWindowPosition(4);

            if view3DPanel('get') == true
                xOffset = xOffset-680;
            end

            set(ptrViewer3d, 'Position', [xOffset yOffset xSize ySize]);                                               
        end

    else
        if viewSegPanel('get') == true 
            set(uiOneWindow, ...
                'position', [uiSegMainPanel.Position(3) ...
                             addOnWidth('get')+30 ...
                             getMainWindowSize('xsize')-uiSegMainPanel.Position(3) ...
                             getMainWindowSize('ysize')-viewerToolbarHeight('get')-viewerTopBarHeight('get')-addOnWidth('get')-30 ...
                             ]...
               );     
        elseif viewKernelPanel('get') == true 
            set(uiOneWindow, ...
                'position', [uiKernelMainPanel.Position(3) ...
                             addOnWidth('get')+30 ...
                             getMainWindowSize('xsize')-uiKernelMainPanel.Position(3) ...
                             getMainWindowSize('ysize')-viewerToolbarHeight('get')-viewerTopBarHeight('get')-addOnWidth('get')-30 ...
                             ]...
               );     
        elseif viewRoiPanel('get') == true 
            set(uiOneWindow, ...
                'position', [uiRoiMainPanel.Position(3) ...
                             addOnWidth('get')+30 ...
                             getMainWindowSize('xsize')-uiRoiMainPanel.Position(3) ...
                             getMainWindowSize('ysize')-viewerToolbarHeight('get')-viewerTopBarHeight('get')-addOnWidth('get')-30 ...
                             ]...
               );                 
        else                    
            set(uiOneWindow, ...
                'position', [0 ...
                             addOnWidth('get')+30 ...
                             getMainWindowSize('xsize') ...
                             getMainWindowSize('ysize')-viewerToolbarHeight('get')-viewerTopBarHeight('get')-addOnWidth('get')-30 ...
                             ]...
               );
        end

        txt = axesText('get', 'axe');
        if ~isempty(txt)
            if isvalid(txt.Parent)
                set(txt.Parent, ...
                    'Position', [5 ...
                                 uiOneWindow.Position(4)-getTopWindowSize('ysize')-55-10 ...
                                 100 ...
                                 200 ...
                                 ]...
                    );                                               
            end
        end
    end   

    % drawnow;
end