function Img = concatenateImages(I1, a, NFrames)

    if length(a) < 2
        error('a must have at least two indices for concatenation.');
    end

    % Img = cat(1, ...
    %     I1{a(1)}(1:end-2, :, :), ...
    %     I1{a(2)}(4:end, :, [ ...
    %         NFrames:-1:1, ...
    %         NFrames*2:-1:NFrames+1, ...
    %         NFrames*3:-1:NFrames*2+1, ...
    %         NFrames*4:-1:NFrames*3+1, ...
    %         NFrames*5:-1:NFrames*4+1, ...
    %         NFrames*6:-1:NFrames*5+1 ...
    %     ]) ...
    % );

    % Img = cat(1, ...
    %     I1{a(1)}(1:end-2, 5:end-4, :), ...
    %     I1{a(2)}(4:end, 5:end-4, [ ...
    %         NFrames:-1:1, ...
    %         NFrames*2:-1:NFrames+1, ...
    %         NFrames*3:-1:NFrames*2+1, ...
    %         NFrames*4:-1:NFrames*3+1, ...
    %         NFrames*5:-1:NFrames*4+1, ...
    %         NFrames*6:-1:NFrames*5+1 ...
    %     ]) ...
    % );

    % Img = cat(1, ...
    %     I1{a(1)}(1:end-2, :, :), ...
    %     I1{a(2)}(4:end, :, [ ...
    %         NFrames:-1:1, ...
    %         NFrames*2:-1:NFrames+1, ...
    %         NFrames*3:-1:NFrames*2+1, ...
    %         NFrames*4:-1:NFrames*3+1, ...
    %         NFrames*5:-1:NFrames*4+1, ...
    %         NFrames*6:-1:NFrames*5+1 ...
    %     ]) ...
    % );
    
    Img = cat(1, ...
        I1{a(1)}(2:end-2, :, :), ...
        I1{a(2)}(4:end-1, :, [ ...
            NFrames:-1:1, ...
            NFrames*2:-1:NFrames+1, ...
            NFrames*3:-1:NFrames*2+1, ...
            NFrames*4:-1:NFrames*3+1, ...
            NFrames*5:-1:NFrames*4+1, ...
            NFrames*6:-1:NFrames*5+1 ...
        ]) ...
    );

end