function setViewRoiPanel(~, ~)
%function setViewRoiPanel(~, ~)   
%Set 2D ROIs Panel.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2020, Daniel Lafontaine, on behalf of the TriDFusion development team.
% 
% This file is part of The Triple Dimention Fusion (TriDFusion).
% 
% TriDFusion development has been led by:  Daniel Lafontaine
% 
% TriDFusion is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>. 

    hObject = viewRoiPanelMenuObject('get');            

    if switchTo3DMode('get')     == false && ...
       switchToIsoSurface('get') == false && ...
       switchToMIPMode('get')    == false        

        releaseRoiWait();

        if strcmp(hObject.Checked, 'on')

            viewRoiPanel('set', false);

            hObject.Checked = 'off';

            uiRoiMainPanel = uiRoiMainPanelPtr('get');
            if ~isempty(uiRoiMainPanel)
                uiRoiMainPanel.Visible = 'off'; 

                uiOneWindow = uiOneWindowPtr('get');
                if ~isempty(uiOneWindow)
                    set(uiOneWindow, ...
                        'position', [0,...
                                     addOnWidth('get')+30 ...
                                     getMainWindowSize('xsize') ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                     ]...
                        );                                                     
                end

                uiCorWindow = uiCorWindowPtr('get');
                if ~isempty(uiCorWindow)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')    
                        set(uiCorWindow, ...
                            'position', [0 ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize') ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );                   
                    else
                        if isVsplash('get') == true 
                            set(uiCorWindow, ...
                                'position', [0 ...
                                             addOnWidth('get')+30+15 ...
                                             getMainWindowSize('xsize')/4 ...
                                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                             ]...
                               );                            
                        else
                            set(uiCorWindow, ...
                                'position', [0 ...
                                             addOnWidth('get')+30+15 ...
                                             getMainWindowSize('xsize')/5 ...
                                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                             ]...
                               );
                        end
                    end
                end   

                uiSliderCor = uiSliderCorPtr('get');
                if ~isempty(uiSliderCor)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')   
                        set(uiSliderCor, ...
                            'Position', [0 ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize') ...
                                         15 ...
                                         ]...
                           );                    
                    else
                        if isVsplash('get') == true
                            set(uiSliderCor, ...
                                'Position', [0 ...
                                             addOnWidth('get')+30 ...
                                             getMainWindowSize('xsize')/4 ...
                                             15 ...
                                             ]...
                               );                              
                        else
                            set(uiSliderCor, ...
                                'Position', [0 ...
                                             addOnWidth('get')+30 ...
                                             getMainWindowSize('xsize')/5 ...
                                             15 ...
                                             ]...
                               );                                            
                        end
                    end
                end                     

                uiSagWindow = uiSagWindowPtr('get');
                if ~isempty(uiSagWindow)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all') 
                        set(uiSagWindow, ...
                            'position', [0 ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize') ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );
                    else
                        if isVsplash('get') == true
                            set(uiSagWindow, ...
                                'position', [getMainWindowSize('xsize')/4 ...
                                             addOnWidth('get')+30+15 ...
                                             getMainWindowSize('xsize')/4 ...
                                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                             ]...
                               );                            
                        else
                            set(uiSagWindow, ...
                                'position', [getMainWindowSize('xsize')/5 ...
                                             addOnWidth('get')+30+15 ...
                                             getMainWindowSize('xsize')/5 ...
                                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                             ]...
                               );
                        end
                   end
                end 

                uiSliderSag = uiSliderSagPtr('get');
                if ~isempty(uiSliderSag)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')  
                        set(uiSliderSag, ...
                            'Position', [0 ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize') ...
                                         15 ...
                                         ]...
                           );                      
                    else
                        if isVsplash('get') == true
                           set(uiSliderSag, ...
                                'Position', [(getMainWindowSize('xsize')/4) ...
                                              addOnWidth('get')+30 ...
                                              getMainWindowSize('xsize')/4 ...
                                              15 ...
                                              ]...
                               );                               
                        else
                            set(uiSliderSag, ...
                                'Position', [(getMainWindowSize('xsize')/5) ...
                                              addOnWidth('get')+30 ...
                                              getMainWindowSize('xsize')/5 ...
                                              15 ...
                                              ]...
                               );               
                        end
                    end      
                end

                uiTraWindow = uiTraWindowPtr('get');
                if ~isempty(uiTraWindow)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all') 
                        set(uiTraWindow, ...
                            'position', [0 ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize') ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );                        
                    else
                        if isVsplash('get') == true
                            set(uiTraWindow, ...
                                'position', [(getMainWindowSize('xsize')/2) ...
                                             addOnWidth('get')+30+15 ...
                                             getMainWindowSize('xsize')/2 ...
                                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                             ]...
                               );                             
                        else
                            set(uiTraWindow, ...
                                'position', [(getMainWindowSize('xsize')/2.5) ...
                                             addOnWidth('get')+30+15 ...
                                             getMainWindowSize('xsize')/2.5 ...
                                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                             ]...
                               ); 
                        end
                     end
                end

                uiSliderTra = uiSliderTraPtr('get');
                if ~isempty(uiSliderTra) 
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')  
                        set(uiSliderTra, ...
                            'Position', [0 ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize') ...
                                         15 ...
                                         ]...
                           );   
                    else
                       if isVsplash('get') == true
                           set(uiSliderTra, ...
                                'Position', [(getMainWindowSize('xsize')/2) ...
                                              addOnWidth('get')+30 ...
                                              getMainWindowSize('xsize')/2 ...
                                              15 ...
                                              ]...
                               );                            
                       else 
                           set(uiSliderTra, ...
                                'Position', [(getMainWindowSize('xsize')/2.5) ...
                                              addOnWidth('get')+30 ...
                                              getMainWindowSize('xsize')/2.5 ...
                                              15 ...
                                              ]...
                               );                                 
                       end
                    end
                end  
                
                uiMipWindow = uiMipWindowPtr('get');
                if ~isempty(uiMipWindow)                     
                    set(uiMipWindow, ...
                        'position', [(getMainWindowSize('xsize')/1.25) ...
                                     addOnWidth('get')+30+15 ...
                                     getMainWindowSize('xsize')/5 ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       ); 
                end

                uiSliderMip = uiSliderMipPtr('get');
                if ~isempty(uiSliderMip) 
                   set(uiSliderMip, ...
                        'Position', [(getMainWindowSize('xsize')/1.25) ...
                                      addOnWidth('get')+30 ...
                                      getMainWindowSize('xsize')/5 ...
                                      15 ...
                                      ]...
                       );                                 
                end  
                
                if isFusion('get') == true
                    uiAlphaSlider = uiAlphaSliderPtr('get');
                    if ~isempty(uiAlphaSlider) 

                        aAxePosition = uiAlphaSlider.Parent.Position;                                                                 
                        if size(dicomBuffer('get'), 3) == 1
                            set(uiAlphaSlider, ...
                                'Position', [10 ...
                                             35 ...
                                             aAxePosition(3)-20 ...
                                             15 ...
                                             ] ...
                                );
                        else
                            if isVsplash('get') == true && ...
                               ~strcmpi(vSplahView('get'), 'all')

                                    set(uiAlphaSlider, ...
                                        'Position', [10 ...
                                                     addOnWidth('get')+50 ...
                                                     aAxePosition(3)-20 ...
                                                     15 ...
                                                     ] ...
                                        );
                            else
                                if isVsplash('get') == true
                                    set(uiAlphaSlider, ...
                                        'Position', [aAxePosition(3)/2+10 ...
                                                     addOnWidth('get')+50 ...
                                                     aAxePosition(3)/2-20 ...
                                                     15 ...
                                                     ] ...
                                        );                                    
                                else
                                    set(uiAlphaSlider, ...
                                        'Position', [aAxePosition(3)/2.5+10 ...
                                                     addOnWidth('get')+50 ...
                                                     aAxePosition(3)/2.5-20 ...
                                                     15 ...
                                                     ] ...
                                        );
                                end
                            end
                        end
                    end   

                    ptrFusionColorbar = uiFusionColorbarPtr('get');
                    if ~isempty(ptrFusionColorbar) 

                        aAxePosition = ptrFusionColorbar.Parent.Position;
                        if size(dicomBuffer('get'), 3) == 1
                            set(ptrFusionColorbar, ...
                                'Position', [aAxePosition(3)-48 ...
                                             27 ...
                                             40 ...
                                             ((aAxePosition(4))/2)-41  ...
                                             ] ...
                                );
                        else
                            if isVsplash('get') == true && ...
                              ~strcmpi(vSplahView('get'), 'all')
                                set(ptrFusionColorbar, ...
                                    'Position', [aAxePosition(3)-48 ...
                                                 29 ...
                                                 40 ...
                                                 ((aAxePosition(4))/2)-35  ...
                                                 ] ...
                                    );
                            else
                                set(ptrFusionColorbar, ...
                                    'Position', [aAxePosition(3)-48 ...
                                                 29 ...
                                                 40 ...
                                                 ((aAxePosition(4))/2)-35  ...
                                                 ] ...
                                    );
                            end
                        end                   
                    end 

                    ptrColorbar = uiColorbarPtr('get');
                    if ~isempty(ptrColorbar) 

                        aAxePosition = ptrColorbar.Parent.Position;
                        if size(dicomBuffer('get'), 3) == 1
                            set(ptrColorbar, ...
                                'Position', [aAxePosition(3)-48 ...
                                             (aAxePosition(4)/2)-9 ...
                                             40 ...
                                             (aAxePosition(4)/2)+5  ...
                                             ] ...
                                );                  
                        else  
                            if isVsplash('get') == true && ...
                              ~strcmpi(vSplahView('get'), 'all')
                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-48 ...
                                                 (aAxePosition(4)/2) ...
                                                 40 ...
                                                 (aAxePosition(4)/2)-4  ...
                                                 ] ...
                                    );
                            else                        
                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-48 ...
                                                 (aAxePosition(4)/2) ...
                                                 40 ...
                                                 (aAxePosition(4)/2)-4  ...
                                                 ] ...
                                   );
                            end
                        end
                    end                             
                else
                    ptrColorbar = uiColorbarPtr('get');
                    if ~isempty(ptrColorbar) 

                        aAxePosition = ptrColorbar.Parent.Position;
                        if size(dicomBuffer('get'), 3) == 1
                            set(ptrColorbar, ...
                                'Position', [aAxePosition(3)-48 ...
                                             7 ...
                                             40 ...
                                             aAxePosition(4)-11  ...
                                             ] ...
                                );                    
                        else  
                            if isVsplash('get') == true && ...
                              ~strcmpi(vSplahView('get'), 'all')

                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-48 ...
                                                 7 ...
                                                 40 ...
                                                 aAxePosition(4)-11  ...
                                                 ] ...
                                    );
                            else                             
                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-48 ...
                                                 7 ...
                                                 40 ...
                                                 aAxePosition(4)-11  ...
                                                 ] ...
                                    );
                            end
                        end
                    end                            
               end                        
            end 
        else
            uiSegMainPanel = uiSegMainPanelPtr('get');
             if ~isempty(uiSegMainPanel)
                uiSegMainPanel.Visible = 'off'; 
            end

            objSegPanel = viewSegPanelMenuObject('get');
            if ~isempty(objSegPanel)
                objSegPanel.Checked = 'off';
            end  
            
            uiKernelMainPanel = uiKernelMainPanelPtr('get');
             if ~isempty(uiKernelMainPanel)
                uiKernelMainPanel.Visible = 'off'; 
            end

            objKernelPanel = viewKernelPanelMenuObject('get');
            if ~isempty(objKernelPanel)
                objKernelPanel.Checked = 'off';
            end  
            
            viewKernelPanel('set', false);           
            viewSegPanel   ('set', false);         
            viewRoiPanel   ('set', true);            

            hObject.Checked = 'on';

            uiRoiMainPanel = uiRoiMainPanelPtr('get');
            if ~isempty(uiRoiMainPanel)
                uiRoiMainPanel.Visible = 'on'; 

                uiOneWindow = uiOneWindowPtr('get');
                if ~isempty(uiOneWindow)
                    set(uiOneWindow, ...
                        'position', [uiRoiMainPanel.Position(3)...
                                     addOnWidth('get')+30 ...
                                     getMainWindowSize('xsize')-uiRoiMainPanel.Position(3) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                     ]...
                        );                                                     
                end

                uiCorWindow = uiCorWindowPtr('get');
                if ~isempty(uiCorWindow)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')
                        set(uiCorWindow, ...
                            'position', [uiRoiMainPanel.Position(3) ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize')-(uiRoiMainPanel.Position(3)/2) ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );                     
                    else
                        if isVsplash('get') == true
                            set(uiCorWindow, ...
                                'position', [uiRoiMainPanel.Position(3) ...
                                             addOnWidth('get')+30+15 ...
                                             (getMainWindowSize('xsize')/4)-(uiRoiMainPanel.Position(3)/2) ...
                                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                             ]...
                               );                             
                        else
                            set(uiCorWindow, ...
                                'position', [uiRoiMainPanel.Position(3) ...
                                             addOnWidth('get')+30+15 ...
                                             (getMainWindowSize('xsize')/5)-(uiRoiMainPanel.Position(3)/2) ...
                                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                             ]...
                               );  
                        end
                    end
                end  

                uiSliderCor = uiSliderCorPtr('get');
                if ~isempty(uiSliderCor)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')     
                        set(uiSliderCor, ...
                            'position', [uiRoiMainPanel.Position(3)...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize')-(uiRoiMainPanel.Position(3)/2) ...
                                         15 ...
                                         ] ...
                           );                   
                    else       
                        if isVsplash('get') == true
                            set(uiSliderCor, ...
                                'position', [uiRoiMainPanel.Position(3)...
                                             addOnWidth('get')+30 ...
                                             (getMainWindowSize('xsize')/4)-(uiRoiMainPanel.Position(3)/2) ...
                                             15 ...
                                             ] ...
                               );                             
                        else
                            set(uiSliderCor, ...
                                'position', [uiRoiMainPanel.Position(3)...
                                             addOnWidth('get')+30 ...
                                             (getMainWindowSize('xsize')/5)-(uiRoiMainPanel.Position(3)/2) ...
                                             15 ...
                                             ] ...
                               );    
                        end
                    end
                end     

                uiSagWindow = uiSagWindowPtr('get');
                if ~isempty(uiSagWindow)
                   if isVsplash('get') == true && ...
                      ~strcmpi(vSplahView('get'), 'all') 
                       set(uiSagWindow, ...
                            'position', [uiRoiMainPanel.Position(3) ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize')-(uiRoiMainPanel.Position(3)/2) ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );                  
                   else
                       if isVsplash('get') == true
                           set(uiSagWindow, ...
                                'position', [(uiRoiMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                             addOnWidth('get')+30+15 ...
                                             (getMainWindowSize('xsize')/4)-(uiRoiMainPanel.Position(3)/2) ...
                                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                             ]...
                               );                           
                       else
                           set(uiSagWindow, ...
                                'position', [(uiRoiMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/5) ...
                                             addOnWidth('get')+30+15 ...
                                             (getMainWindowSize('xsize')/5)-(uiRoiMainPanel.Position(3)/2) ...
                                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                             ]...
                               );
                       end
                   end
                end 

                uiSliderSag = uiSliderSagPtr('get');
                if ~isempty(uiSliderSag)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')  
                       set(uiSliderSag, ...
                           'position', [uiRoiMainPanel.Position(3) ...
                                        addOnWidth('get')+30 ...
                                        getMainWindowSize('xsize')-(uiRoiMainPanel.Position(3)/2) ...
                                        15 ...
                                        ] ...
                           );                     
                    else
                       if isVsplash('get') == true
                           set(uiSliderSag, ...
                               'position', [(uiRoiMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                            addOnWidth('get')+30 ...
                                            (getMainWindowSize('xsize')/4)-(uiRoiMainPanel.Position(3)/2) ...
                                            15 ...
                                            ] ...
                               );                           
                       else 
                           set(uiSliderSag, ...
                               'position', [(uiRoiMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/5) ...
                                            addOnWidth('get')+30 ...
                                            (getMainWindowSize('xsize')/5)-(uiRoiMainPanel.Position(3)/2) ...
                                            15 ...
                                            ] ...
                               );  
                       end
                    end
                end   

                uiTraWindow = uiTraWindowPtr('get');
                if ~isempty(uiTraWindow)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')  

                        set(uiTraWindow, ...
                            'position', [uiRoiMainPanel.Position(3)  ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize')-(uiRoiMainPanel.Position(3)/2)...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );  
                    else
                        if isVsplash('get') == true
                            set(uiTraWindow, ...
                                'position', [(getMainWindowSize('xsize')/2) ...
                                             addOnWidth('get')+30+15 ...
                                             getMainWindowSize('xsize')/2 ...
                                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                             ]...
                               );                             
                        else
                            set(uiTraWindow, ...
                                'position', [(getMainWindowSize('xsize')/2.5) ...
                                             addOnWidth('get')+30+15 ...
                                             getMainWindowSize('xsize')/2.5 ...
                                             getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                             ]...
                               );                                
                        end
                    end
                end    

                uiSliderTra = uiSliderTraPtr('get');
                if ~isempty(uiSliderTra)  
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')  
                        set(uiSliderTra, ...
                            'Position', [uiRoiMainPanel.Position(3) ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize')-(uiRoiMainPanel.Position(3)/2) ...
                                         15 ...
                                         ]...
                           );   
                    else
                       if isVsplash('get') == true
                           set(uiSliderTra, ...
                                'Position', [(getMainWindowSize('xsize')/2) ...
                                              addOnWidth('get')+30 ...
                                              getMainWindowSize('xsize')/2 ...
                                              15 ...
                                              ]...
                               );                           
                       else 
                           set(uiSliderTra, ...
                                'Position', [(getMainWindowSize('xsize')/2.5) ...
                                              addOnWidth('get')+30 ...
                                              getMainWindowSize('xsize')/2.5 ...
                                              15 ...
                                              ]...
                               );                                 
                       end
                    end
                end
                
                uiMipWindow = uiMipWindowPtr('get');
                if ~isempty(uiMipWindow)
                    set(uiMipWindow, ...
                        'position', [(getMainWindowSize('xsize')/1.25) ...
                                     addOnWidth('get')+30+15 ...
                                     getMainWindowSize('xsize')/5 ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                     ]...
                       );                                
                end    

                uiSliderMip = uiSliderMipPtr('get');
                if ~isempty(uiSliderMip)  
                   set(uiSliderMip, ...
                        'Position', [(getMainWindowSize('xsize')/1.25) ...
                                      addOnWidth('get')+30 ...
                                      getMainWindowSize('xsize')/5 ...
                                      15 ...
                                      ]...
                       );                                 
                end
                
                if isFusion('get') == true
                    uiAlphaSlider = uiAlphaSliderPtr('get');
                    if ~isempty(uiAlphaSlider) 

                        aAxePosition = uiAlphaSlider.Parent.Position;                                                                 
                        if size(dicomBuffer('get'), 3) == 1
                            set(uiAlphaSlider, ...
                                'Position', [uiRoiMainPanel.Position(3)+10 ...
                                             35 ...
                                             aAxePosition(3)-uiRoiMainPanel.Position(3)-20 ...
                                             15]);
                        else
                            if isVsplash('get') == true && ...
                               ~strcmpi(vSplahView('get'), 'all')
                                set(uiAlphaSlider, ...
                                    'Position', [uiRoiMainPanel.Position(3)+10 ...
                                                 addOnWidth('get')+50 ...
                                                 aAxePosition(3)-uiRoiMainPanel.Position(3)-20 ...
                                                 15 ...
                                                 ] ...
                                   );
                            else
                                if isVsplash('get') == true
                                    set(uiAlphaSlider, ...
                                        'Position', [aAxePosition(3)/2+10 ...
                                                     addOnWidth('get')+50 ...
                                                     aAxePosition(3)/2-20 ...
                                                     15 ...
                                                     ] ...
                                        );                                    
                                else
                                    set(uiAlphaSlider, ...
                                        'Position', [aAxePosition(3)/2.5+10 ...
                                                     addOnWidth('get')+50 ...
                                                     aAxePosition(3)/2.5-20 ...
                                                     15 ...
                                                     ] ...
                                        );
                                end
                            end
                        end
                    end     

                    ptrFusionColorbar = uiFusionColorbarPtr('get');
                    if ~isempty(ptrFusionColorbar) 

                        aAxePosition = ptrFusionColorbar.Parent.Position;
                        if size(dicomBuffer('get'), 3) == 1
                            set(ptrFusionColorbar, ...
                                'Position', [aAxePosition(3)-48 ...
                                             27 ...
                                             40 ...
                                             ((aAxePosition(4))/2)-41  ...
                                             ] ...
                                );
                        else
                            if isVsplash('get') == true && ...
                              ~strcmpi(vSplahView('get'), 'all')
                                    set(ptrFusionColorbar, ...
                                        'Position', [aAxePosition(3)-(uiRoiMainPanel.Position(3)/2)-48 ...
                                                     29 ...
                                                     40 ... 
                                                     ((aAxePosition(4))/2)-35  ...
                                                     ] ...
                                        );
                            else
                                set(ptrFusionColorbar, ...
                                    'Position', [aAxePosition(3)-48 ...
                                                 29 ...
                                                 40 ...
                                                 ((aAxePosition(4))/2)-35  ...
                                                 ] ...
                                    );
                            end
                        end                   
                    end

                    ptrColorbar = uiColorbarPtr('get');
                    if ~isempty(ptrColorbar) 

                        aAxePosition = ptrColorbar.Parent.Position;
                        if size(dicomBuffer('get'), 3) == 1
                            set(ptrColorbar, ...
                                'Position', [aAxePosition(3)-48 ...
                                             (aAxePosition(4)/2)-9 ...
                                             40 ...
                                             (aAxePosition(4)/2)+5  ...
                                             ] ...
                                );                  
                        else  
                            if isVsplash('get') == true && ...
                              ~strcmpi(vSplahView('get'), 'all')

                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-(uiRoiMainPanel.Position(3)/2)-48 ...
                                                 (aAxePosition(4)/2) ...
                                                 40 ...
                                                 (aAxePosition(4)/2)-4  ...
                                                 ] ...
                                    );
                            else                        
                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-48 ...
                                                 (aAxePosition(4)/2) ...
                                                 40 ...
                                                 (aAxePosition(4)/2)-4  ...
                                                 ] ...
                                   );
                            end
                        end
                    end  
                else
                    ptrColorbar = uiColorbarPtr('get');
                    if ~isempty(ptrColorbar) 

                        aAxePosition = ptrColorbar.Parent.Position;
                        if size(dicomBuffer('get'), 3) == 1
                            set(ptrColorbar, ...
                                'Position', [aAxePosition(3)-48 ...
                                             7 ...
                                             40 ...
                                             aAxePosition(4)-11  ...
                                             ] ...
                                );                    
                        else  
                            if isVsplash('get') == true && ...
                              ~strcmpi(vSplahView('get'), 'all')
                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-(uiRoiMainPanel.Position(3)/2)-48 ...
                                                 7 ...
                                                 40 ...
                                                 aAxePosition(4)-11  ...
                                                 ] ...
                                   );
                            else                             
                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-48 ...
                                                 7 ...
                                                 40 ...
                                                 aAxePosition(4)-11  ...
                                                 ] ...
                                   );
                            end
                        end
                    end                               
               end
            end                    
        end
    end         
end
