function editContourMarginCallback(~, ~)
%function editContourMarginCallback(~, ~)
%Edit Marginal distance and joint type, the function is called from the roi/voi menu.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2024, Daniel Lafontaine, on behalf of the TriDFusion development team.
%
% This file is part of The Triple Dimention Fusion (TriDFusion).
%
% TriDFusion development has been led by:  Daniel Lafontaine
%
% TriDFusion is distributed under the terms of the Lesser GNU Public License.
%
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
%
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>.

    DLG_EDIT_MARGIN_X = 380;
    DLG_EDIT_MARGIN_Y = 145;

    if viewerUIFigure('get') == true

        dlgMarginEdit = ...
            uifigure('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_EDIT_MARGIN_X/2) ...
                                (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_EDIT_MARGIN_Y/2) ...
                                DLG_EDIT_MARGIN_X ...
                                DLG_EDIT_MARGIN_Y ...
                                ],...
                   'Resize', 'off', ...
                   'Color', viewerBackgroundColor('get'),...
                   'WindowStyle', 'modal', ...
                   'Name' , 'Contour Margin Adjustments'...
                   );
    else      
        dlgMarginEdit = ...
            dialog('Position', [(getMainWindowPosition('xpos')+(getMainWindowSize('xsize')/2)-DLG_EDIT_MARGIN_X/2) ...
                                (getMainWindowPosition('ypos')+(getMainWindowSize('ysize')/2)-DLG_EDIT_MARGIN_Y/2) ...
                                DLG_EDIT_MARGIN_X ...
                                DLG_EDIT_MARGIN_Y ...
                                ],...
                   'MenuBar', 'none',...
                   'Resize', 'off', ...    
                   'NumberTitle','off',...
                   'MenuBar', 'none',...
                   'Color', viewerBackgroundColor('get'), ...
                   'Name', 'Contour Margin Adjustments',...
                   'Toolbar','none'...               
                   );
    end

    % Joint Type

        uicontrol(dlgMarginEdit,...
                  'style'   , 'text',...
                  'Enable'  , 'On',...
                  'string'  , ' Joint styles at segment endpoints',...
                  'horizontalalignment', 'left',...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...                   
                  'position', [20 95 250 20]...
                  );


    switch lower(contourMarginJointType('get'))

        case 'round'
            dJointTypeoffset = 1;

        case 'miter'
            dJointTypeoffset = 2;

        otherwise
            dJointTypeoffset = 3;
    end

    popMarginJointType = ...
        uicontrol(dlgMarginEdit, ...
                  'enable'  , 'on',...
                  'Style'   , 'popup', ...
                  'position', [285 95 75 20],...
                  'String'  , {'Round', 'Miter', 'Square'}, ...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...
                  'Value'   , dJointTypeoffset ...
                  );

     % Margin Distance (mm)

        uicontrol(dlgMarginEdit,...
                  'style'   , 'text',...
                  'Enable'  , 'On',...
                  'string'  , 'Margin Distance (mm)',...
                  'horizontalalignment', 'left',...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...                   
                  'position', [20 65 250 20]...
                  );

    edtMarginMarginDistanceValue = ...
        uicontrol(dlgMarginEdit, ...
                  'Style'   , 'Edit', ...
                  'Position', [285 65 75 20], ...
                  'String'  , num2str(contourMarginDistanceValue('get')), ...
                  'Enable'  , 'on', ...
                  'BackgroundColor', viewerBackgroundColor('get'), ...
                  'ForegroundColor', viewerForegroundColor('get'), ...
                  'CallBack', @edtMarginMarginDistanceValueCallback ...
                  );        

     % Cancel or Proceed

     uicontrol(dlgMarginEdit,...
               'String','Cancel',...
               'Position',[285 7 75 25],...
               'BackgroundColor', viewerBackgroundColor('get'), ...
               'ForegroundColor', viewerForegroundColor('get'), ...                
               'Callback', @cancelMarginEditCallback...
               );

     uicontrol(dlgMarginEdit,...
              'String','Ok',...
              'Position',[200 7 75 25],...
              'BackgroundColor', viewerBackgroundColor('get'), ...
              'ForegroundColor', viewerForegroundColor('get'), ...               
              'Callback', @proceedMarginEditCallback...
              );   

    function edtMarginMarginDistanceValueCallback(~, ~)

        dObjectValue = str2double(get(edtMarginMarginDistanceValue, 'String'));

        if dObjectValue < 0

            dObjectValue = 1;

            set(edtMarginMarginDistanceValue, 'String', num2str(dObjectValue));
        end
    end

    function cancelMarginEditCallback(~, ~)

        delete(dlgMarginEdit);
    end

    function proceedMarginEditCallback(~, ~)

        dMarginSize = str2double(get(edtMarginMarginDistanceValue, 'String'));

        asJointType = get(popMarginJointType, 'string');
        dJointTypeOffset = get(popMarginJointType, 'value');

        sJointType = lower(asJointType{dJointTypeOffset});

        contourMarginDistanceValue('set', dMarginSize);
        contourMarginJointType('set', sJointType);

        delete(dlgMarginEdit);

    end
end