function setViewKernelPanel(~, ~)
%function setViewKernelPanel(~, ~)   
%Set 2D Kernel Panel.
%See TriDFuison.doc (or pdf) for more information about options.
%
%Author: Daniel Lafontaine, lafontad@mskcc.org
%
%Last specifications modified:
%
% Copyright 2020, Daniel Lafontaine, on behalf of the TriDFusion development team.
% 
% This file is part of The Triple Dimention Fusion (TriDFusion).
% 
% TriDFusion development has been led by:  Daniel Lafontaine
% 
% TriDFusion is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of TriDFusion is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% TriDFusion is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with TriDFusion.  If not, see <http://www.gnu.org/licenses/>. 

    hObject = viewKernelPanelMenuObject('get');            

    if switchTo3DMode('get')     == false && ...
       switchToIsoSurface('get') == false && ...
       switchToMIPMode('get')    == false        

        releaseRoiWait();

        if strcmp(hObject.Checked, 'on')

            viewKernelPanel('set', false);

            hObject.Checked = 'off';

            uiKernelMainPanel = uiKernelMainPanelPtr('get');
            if ~isempty(uiKernelMainPanel)
                uiKernelMainPanel.Visible = 'off'; 

                uiOneWindow = uiOneWindowPtr('get');
                if ~isempty(uiOneWindow)
                    set(uiOneWindow, ...
                        'position', [0,...
                                     addOnWidth('get')+30 ...
                                     getMainWindowSize('xsize') ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                     ]...
                        );                                                     
                end

                uiCorWindow = uiCorWindowPtr('get');
                if ~isempty(uiCorWindow)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')    
                        set(uiCorWindow, ...
                            'position', [0 ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize') ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );                   
                    else
                        set(uiCorWindow, ...
                            'position', [0 ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize')/4 ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );
                    end
                end   

                uiSliderCor = uiSliderCorPtr('get');
                if ~isempty(uiSliderCor)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')   
                        set(uiSliderCor, ...
                            'Position', [0 ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize') ...
                                         15 ...
                                         ]...
                           );                    
                    else
                        set(uiSliderCor, ...
                            'Position', [0 ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize')/4 ...
                                         15 ...
                                         ]...
                           );                                            
                    end
                end                     

                uiSagWindow = uiSagWindowPtr('get');
                if ~isempty(uiSagWindow)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all') 
                        set(uiSagWindow, ...
                            'position', [0 ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize') ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );
                    else
                        set(uiSagWindow, ...
                            'position', [getMainWindowSize('xsize')/4 ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize')/4 ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );
                   end
                end 

                uiSliderSag = uiSliderSagPtr('get');
                if ~isempty(uiSliderSag)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')  
                        set(uiSliderSag, ...
                            'Position', [0 ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize') ...
                                         15 ...
                                         ]...
                           );                      
                    else
                        set(uiSliderSag, ...
                            'Position', [(getMainWindowSize('xsize')/4) ...
                                          addOnWidth('get')+30 ...
                                          getMainWindowSize('xsize')/4 ...
                                          15 ...
                                          ]...
                           );               
                    end      
                end

                uiTraWindow = uiTraWindowPtr('get');
                if ~isempty(uiTraWindow)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all') 
                        set(uiTraWindow, ...
                            'position', [0 ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize') ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );                        
                    else
                        set(uiTraWindow, ...
                            'position', [(getMainWindowSize('xsize')/2) ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize')/2 ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           ); 
                     end
                end

                uiSliderTra = uiSliderTraPtr('get');
                if ~isempty(uiSliderTra) 
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')  
                        set(uiSliderTra, ...
                            'Position', [0 ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize') ...
                                         15 ...
                                         ]...
                           );   
                    else
                       set(uiSliderTra, ...
                            'Position', [(getMainWindowSize('xsize')/2) ...
                                          addOnWidth('get')+30 ...
                                          getMainWindowSize('xsize')/2 ...
                                          15 ...
                                          ]...
                           );                                 
                    end
                end  

                if isFusion('get') == true
                    uiAlphaSlider = uiAlphaSliderPtr('get');
                    if ~isempty(uiAlphaSlider) 

                        aAxePosition = uiAlphaSlider.Parent.Position;                                                                 
                        if size(dicomBuffer('get'), 3) == 1
                            set(uiAlphaSlider, ...
                                'Position', [10 ...
                                             35 ...
                                             aAxePosition(3)-20 ...
                                             15 ...
                                             ] ...
                                );
                        else
                            if isVsplash('get') == true && ...
                               ~strcmpi(vSplahView('get'), 'all')

                                    set(uiAlphaSlider, ...
                                        'Position', [10 ...
                                                     addOnWidth('get')+50 ...
                                                     aAxePosition(3)-20 ...
                                                     15 ...
                                                     ] ...
                                        );
                            else
                                set(uiAlphaSlider, ...
                                    'Position', [aAxePosition(3)/2+10 ...
                                                 addOnWidth('get')+50 ...
                                                 aAxePosition(3)/2-20 ...
                                                 15 ...
                                                 ] ...
                                    );
                            end
                        end
                    end   

                    ptrFusionColorbar = uiFusionColorbarPtr('get');
                    if ~isempty(ptrFusionColorbar) 

                        aAxePosition = ptrFusionColorbar.Parent.Position;
                        if size(dicomBuffer('get'), 3) == 1
                            set(ptrFusionColorbar, ...
                                'Position', [aAxePosition(3)-49 ...
                                             27 ...
                                             40 ...
                                             ((aAxePosition(4))/2)-41-20 ...
                                             ] ...
                                );
                        else
                            if isVsplash('get') == true && ...
                              ~strcmpi(vSplahView('get'), 'all')
                                set(ptrFusionColorbar, ...
                                    'Position', [aAxePosition(3)-49 ...
                                                 29 ...
                                                 40 ...
                                                 ((aAxePosition(4))/2)-35-20 ...
                                                 ] ...
                                    );
                            else
                                set(ptrFusionColorbar, ...
                                    'Position', [aAxePosition(3)-49 ...
                                                 29 ...
                                                 40 ...
                                                 ((aAxePosition(4))/2)-35-20 ...
                                                 ] ...
                                    );
                            end
                        end                   
                    end 

                    ptrColorbar = uiColorbarPtr('get');
                    if ~isempty(ptrColorbar) 

                        aAxePosition = ptrColorbar.Parent.Position;
                        if size(dicomBuffer('get'), 3) == 1
                            set(ptrColorbar, ...
                                'Position', [aAxePosition(3)-49 ...
                                             (aAxePosition(4)/2)-9 ...
                                             40 ...
                                             (aAxePosition(4)/2)+5-20 ...
                                             ] ...
                                );                  
                        else  
                            if isVsplash('get') == true && ...
                              ~strcmpi(vSplahView('get'), 'all')
                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-49 ...
                                                 (aAxePosition(4)/2) ...
                                                 40 ...
                                                 (aAxePosition(4)/2)-4-20 ...
                                                 ] ...
                                    );
                            else                        
                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-49 ...
                                                 (aAxePosition(4)/2) ...
                                                 40 ...
                                                 (aAxePosition(4)/2)-4-20 ...
                                                 ] ...
                                   );
                            end
                        end
                    end                             
                else
                    ptrColorbar = uiColorbarPtr('get');
                    if ~isempty(ptrColorbar) 

                        aAxePosition = ptrColorbar.Parent.Position;
                        if size(dicomBuffer('get'), 3) == 1
                            set(ptrColorbar, ...
                                'Position', [aAxePosition(3)-49 ...
                                             7 ...
                                             40 ...
                                             aAxePosition(4)-11-20 ...
                                             ] ...
                                );                    
                        else  
                            if isVsplash('get') == true && ...
                              ~strcmpi(vSplahView('get'), 'all')

                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-49 ...
                                                 7 ...
                                                 40 ...
                                                 aAxePosition(4)-11-20 ...
                                                 ] ...
                                    );
                            else                             
                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-49 ...
                                                 7 ...
                                                 40 ...
                                                 aAxePosition(4)-11-20 ...
                                                 ] ...
                                    );
                            end
                        end
                    end                            
               end                        
            end 
        else
            uiSegMainPanel = uiSegMainPanelPtr('get');
             if ~isempty(uiSegMainPanel)
                uiSegMainPanel.Visible = 'off'; 
            end

            objSegPanel = viewSegPanelMenuObject('get');
            if ~isempty(objSegPanel)
                objSegPanel.Checked = 'off';
            end  
            
            uiRoiMainPanel = uiRoiMainPanelPtr('get');
             if ~isempty(uiRoiMainPanel)
                uiRoiMainPanel.Visible = 'off'; 
            end

            objRoiPanel = viewRoiPanelMenuObject('get');
            if ~isempty(objRoiPanel)
                objRoiPanel.Checked = 'off';
            end  
            
            viewSegPanel   ('set', false);
            viewRoiPanel   ('set', false);            
            viewKernelPanel('set', true);

            hObject.Checked = 'on';

            uiKernelMainPanel = uiKernelMainPanelPtr('get');
            if ~isempty(uiKernelMainPanel)
                uiKernelMainPanel.Visible = 'on'; 

                uiOneWindow = uiOneWindowPtr('get');
                if ~isempty(uiOneWindow)
                    set(uiOneWindow, ...
                        'position', [uiKernelMainPanel.Position(3)...
                                     addOnWidth('get')+30 ...
                                     getMainWindowSize('xsize')-uiKernelMainPanel.Position(3) ...
                                     getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30 ...
                                     ]...
                        );                                                     
                end

                uiCorWindow = uiCorWindowPtr('get');
                if ~isempty(uiCorWindow)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')
                        set(uiCorWindow, ...
                            'position', [uiKernelMainPanel.Position(3) ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );                     
                    else
                        set(uiCorWindow, ...
                            'position', [uiKernelMainPanel.Position(3) ...
                                         addOnWidth('get')+30+15 ...
                                         (getMainWindowSize('xsize')/4)-(uiKernelMainPanel.Position(3)/2) ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );  
                    end
                end  

                uiSliderCor = uiSliderCorPtr('get');
                if ~isempty(uiSliderCor)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')     
                        set(uiSliderCor, ...
                            'position', [uiKernelMainPanel.Position(3)...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                         15 ...
                                         ] ...
                           );                   
                    else                   
                        set(uiSliderCor, ...
                            'position', [uiKernelMainPanel.Position(3)...
                                         addOnWidth('get')+30 ...
                                         (getMainWindowSize('xsize')/4)-(uiKernelMainPanel.Position(3)/2) ...
                                         15 ...
                                         ] ...
                           );    
                    end
                end     

                uiSagWindow = uiSagWindowPtr('get');
                if ~isempty(uiSagWindow)
                   if isVsplash('get') == true && ...
                      ~strcmpi(vSplahView('get'), 'all') 
                       set(uiSagWindow, ...
                            'position', [uiKernelMainPanel.Position(3) ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );                  
                   else
                       set(uiSagWindow, ...
                            'position', [(uiKernelMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                         addOnWidth('get')+30+15 ...
                                         (getMainWindowSize('xsize')/4)-(uiKernelMainPanel.Position(3)/2) ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );
                   end
                end 

                uiSliderSag = uiSliderSagPtr('get');
                if ~isempty(uiSliderSag)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')  
                       set(uiSliderSag, ...
                           'position', [uiKernelMainPanel.Position(3) ...
                                        addOnWidth('get')+30 ...
                                        getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                        15 ...
                                        ] ...
                           );                     
                    else
                       set(uiSliderSag, ...
                           'position', [(uiKernelMainPanel.Position(3)/2)+(getMainWindowSize('xsize')/4) ...
                                        addOnWidth('get')+30 ...
                                        (getMainWindowSize('xsize')/4)-(uiKernelMainPanel.Position(3)/2) ...
                                        15 ...
                                        ] ...
                           );  
                    end
                end   

                uiTraWindow = uiTraWindowPtr('get');
                if ~isempty(uiTraWindow)
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')  

                        set(uiTraWindow, ...
                            'position', [uiKernelMainPanel.Position(3)  ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2)...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );  
                    else
                        set(uiTraWindow, ...
                            'position', [(getMainWindowSize('xsize')/2) ...
                                         addOnWidth('get')+30+15 ...
                                         getMainWindowSize('xsize')/2 ...
                                         getMainWindowSize('ysize')-getTopWindowSize('ysize')-addOnWidth('get')-30-15 ...
                                         ]...
                           );                                
                    end
                end    

                uiSliderTra = uiSliderTraPtr('get');
                if ~isempty(uiSliderTra)  
                    if isVsplash('get') == true && ...
                       ~strcmpi(vSplahView('get'), 'all')  
                        set(uiSliderTra, ...
                            'Position', [uiKernelMainPanel.Position(3) ...
                                         addOnWidth('get')+30 ...
                                         getMainWindowSize('xsize')-(uiKernelMainPanel.Position(3)/2) ...
                                         15 ...
                                         ]...
                           );   
                    else
                       set(uiSliderTra, ...
                            'Position', [(getMainWindowSize('xsize')/2) ...
                                          addOnWidth('get')+30 ...
                                          getMainWindowSize('xsize')/2 ...
                                          15 ...
                                          ]...
                           );                                 
                    end
                end
                if isFusion('get') == true
                    uiAlphaSlider = uiAlphaSliderPtr('get');
                    if ~isempty(uiAlphaSlider) 

                        aAxePosition = uiAlphaSlider.Parent.Position;                                                                 
                        if size(dicomBuffer('get'), 3) == 1
                            set(uiAlphaSlider, ...
                                'Position', [uiKernelMainPanel.Position(3)+10 ...
                                             35 ...
                                             aAxePosition(3)-uiKernelMainPanel.Position(3)-20 ...
                                             15]);
                        else
                            if isVsplash('get') == true && ...
                               ~strcmpi(vSplahView('get'), 'all')
                                set(uiAlphaSlider, ...
                                    'Position', [uiKernelMainPanel.Position(3)+10 ...
                                                 addOnWidth('get')+50 ...
                                                 aAxePosition(3)-uiKernelMainPanel.Position(3)-20 ...
                                                 15 ...
                                                 ] ...
                                   );
                            else
                                set(uiAlphaSlider, ...
                                    'Position', [aAxePosition(3)/2+10 ...
                                                 addOnWidth('get')+50 ...
                                                 aAxePosition(3)/2-20 ...
                                                 15 ...
                                                 ] ...
                                    );
                            end
                        end
                    end     

                    ptrFusionColorbar = uiFusionColorbarPtr('get');
                    if ~isempty(ptrFusionColorbar) 

                        aAxePosition = ptrFusionColorbar.Parent.Position;
                        if size(dicomBuffer('get'), 3) == 1
                            set(ptrFusionColorbar, ...
                                'Position', [aAxePosition(3)-49 ...
                                             27 ...
                                             40 ...
                                             ((aAxePosition(4))/2)-41-20 ...
                                             ] ...
                                );
                        else
                            if isVsplash('get') == true && ...
                              ~strcmpi(vSplahView('get'), 'all')
                                    set(ptrFusionColorbar, ...
                                        'Position', [aAxePosition(3)-(uiKernelMainPanel.Position(3)/2)-49 ...
                                                     29 ...
                                                     40 ... 
                                                     ((aAxePosition(4))/2)-35-20 ...
                                                     ] ...
                                        );
                            else
                                set(ptrFusionColorbar, ...
                                    'Position', [aAxePosition(3)-49 ...
                                                 29 ...
                                                 40 ...
                                                 ((aAxePosition(4))/2)-35-20 ...
                                                 ] ...
                                    );
                            end
                        end                   
                    end

                    ptrColorbar = uiColorbarPtr('get');
                    if ~isempty(ptrColorbar) 

                        aAxePosition = ptrColorbar.Parent.Position;
                        if size(dicomBuffer('get'), 3) == 1
                            set(ptrColorbar, ...
                                'Position', [aAxePosition(3)-49 ...
                                             (aAxePosition(4)/2)-9 ...
                                             40 ...
                                             (aAxePosition(4)/2)+5-20 ...
                                             ] ...
                                );                  
                        else  
                            if isVsplash('get') == true && ...
                              ~strcmpi(vSplahView('get'), 'all')

                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-(uiKernelMainPanel.Position(3)/2)-49 ...
                                                 (aAxePosition(4)/2) ...
                                                 40 ...
                                                 (aAxePosition(4)/2)-4-20 ...
                                                 ] ...
                                    );
                            else                        
                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-49 ...
                                                 (aAxePosition(4)/2) ...
                                                 40 ...
                                                 (aAxePosition(4)/2)-4-20 ...
                                                 ] ...
                                   );
                            end
                        end
                    end  
                else
                    ptrColorbar = uiColorbarPtr('get');
                    if ~isempty(ptrColorbar) 

                        aAxePosition = ptrColorbar.Parent.Position;
                        if size(dicomBuffer('get'), 3) == 1
                            set(ptrColorbar, ...
                                'Position', [aAxePosition(3)-49 ...
                                             7 ...
                                             40 ...
                                             aAxePosition(4)-11-20 ...
                                             ] ...
                                );                    
                        else  
                            if isVsplash('get') == true && ...
                              ~strcmpi(vSplahView('get'), 'all')
                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-(uiKernelMainPanel.Position(3)/2)-49 ...
                                                 7 ...
                                                 40 ...
                                                 aAxePosition(4)-11-20 ...
                                                 ] ...
                                   );
                            else                             
                                set(ptrColorbar, ...
                                    'Position', [aAxePosition(3)-49 ...
                                                 7 ...
                                                 40 ...
                                                 aAxePosition(4)-11-20 ...
                                                 ] ...
                                   );
                            end
                        end
                    end                               
               end
            end                    
        end
    end         
end
